import {
  GUILDS_ACTIVITY_FACTS,
  GUILDS_AI_FACTS,
  GUILDS_CHAT_FACTS,
  GUILDS_LEADERBOARD_FACTS,
  GUILDS_MEMBERSHIP_FACTS,
  GUILDS_OVERVIEW_FACTS,
  GUILDS_ROLES_FACTS,
  GUILDS_SEARCH_JOINING_FACTS,
} from './trackerAiGuildsSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiGuildsCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_guilds_overview_01',
      source: 'Guilds Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Guilds',
      title: 'Guilds Overview',
      disambiguation: 'This chunk is about the Guilds Overview mechanic itself, not its interactions. It is not a gameplay guild-economy guide, an admin audit log, or a raw Appwrite schema note.',
      mechanics: ['Guilds Overview'],
      tags: ['trackerai', 'guilds', 'site feature', 'overview', 'social'],
      paragraphs: [...GUILDS_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_guilds_membership_01',
      source: 'Guilds Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Membership and Slots',
      title: 'Guild Membership and Slots',
      disambiguation: 'This chunk is about the Guild Membership and Slots mechanic itself, not its interactions. It is not a hidden moderation rule set or a backend membership table dump.',
      mechanics: ['Guild Membership and Slots'],
      tags: ['trackerai', 'guilds', 'membership', 'slots', 'limits'],
      paragraphs: [...GUILDS_MEMBERSHIP_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_guilds_joining_01',
      source: 'Guilds Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Search, Join, and Create',
      title: 'Guild Search Joining and Creation',
      disambiguation: 'This chunk is about the Guild Search Joining and Creation mechanic itself, not its interactions. It is not a guild-name policy document or an exhaustive permissions reference.',
      mechanics: ['Guild Search Joining and Creation'],
      tags: ['trackerai', 'guilds', 'search', 'join', 'create', 'private'],
      paragraphs: [...GUILDS_SEARCH_JOINING_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_guilds_roles_01',
      source: 'Guilds Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Roles and Management',
      title: 'Guild Roles and Management',
      disambiguation: 'This chunk is about the Guild Roles and Management mechanic itself, not its interactions. It is not an admin-only moderation spec or a complete legal permissions matrix.',
      mechanics: ['Guild Roles and Management'],
      tags: ['trackerai', 'guilds', 'roles', 'owner', 'officer', 'members'],
      paragraphs: [...GUILDS_ROLES_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_guilds_activity_01',
      source: 'Guilds Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Activity Snapshot',
      title: 'Guild Activity Snapshot',
      disambiguation: 'This chunk is about the Guild Activity Snapshot mechanic itself, not its interactions. It is not a leaderboard algorithm description or a raw run-export specification.',
      mechanics: ['Guild Activity Snapshot'],
      tags: ['trackerai', 'guilds', 'activity', 'member runs', 'charts', 'screenshots'],
      paragraphs: [...GUILDS_ACTIVITY_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_guilds_chat_01',
      source: 'Guilds Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Guild Chat',
      title: 'Guild Chat Drawer',
      disambiguation: 'This chunk is about the Guild Chat Drawer mechanic itself, not its interactions. It is not a full chat-policy manual or a promise that every AI response will run without limits.',
      mechanics: ['Guild Chat Drawer'],
      tags: ['trackerai', 'guilds', 'chat', 'drawer', 'ai prompts'],
      paragraphs: [...GUILDS_CHAT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_guilds_leaderboard_01',
      source: 'Guilds Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Leaderboard Visibility',
      title: 'Guild Leaderboard Visibility',
      disambiguation: 'This chunk is about the Guild Leaderboard Visibility mechanic itself, not its interactions. It is not a score-ranking formula or a public leaderboard data export.',
      mechanics: ['Guild Leaderboard Visibility'],
      tags: ['trackerai', 'guilds', 'leaderboard', 'visibility', 'member count'],
      paragraphs: [...GUILDS_LEADERBOARD_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_guilds_ai_01',
      source: 'Guilds Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on Guilds',
      title: 'Guilds AI Help Coverage',
      disambiguation: 'This chunk is about the Guilds AI Help Coverage mechanic itself, not its interactions. It is not a hidden command catalog or a claim that the assistant should bypass role or safety checks.',
      mechanics: ['Guilds AI Help Coverage'],
      tags: ['trackerai', 'guilds', 'ai help', 'guidance', 'actions'],
      paragraphs: [...GUILDS_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_guilds_faq_join_01',
      source: 'Guilds Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I find, join, or create a guild?',
      title: 'How do I find, join, or create a guild?',
      disambiguation: 'This chunk is about the interaction between guild access and guild join/create flows, not a gameplay guild progression guide.',
      mechanics: ['Guilds Overview', 'Guild Membership and Slots', 'Guild Search Joining and Creation'],
      tags: ['trackerai', 'guilds', 'faq', 'join', 'create', 'search'],
      interaction_type: 'cross_system',
      interaction_summary: 'Guilds Overview, Guild Membership and Slots, and Guild Search Joining and Creation work together to answer the practical first question: how a user gets into the right guild without losing track of membership limits.',
      paragraphs: [
        'Guilds Overview explains where the guild feature appears in the site, Guild Membership and Slots explains the three-guild limit and the one-owned-guild rule for normal users, and Guild Search Joining and Creation explains the actual search, join, request, and create flows.',
        'That combination matters because joining a public guild is different from requesting access to a private guild, and creating a guild is different from simply taking another open slot.',
        'For user-facing help, the clearest answer is to name those mechanics directly: start from Guilds Overview, check Guild Membership and Slots so you know whether you have room, and then use Guild Search Joining and Creation to join a public guild, request a private one, or make your own guild.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_guilds_faq_manage_01',
      source: 'Guilds Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can owners and officers do in a guild?',
      title: 'What can owners and officers do in a guild?',
      disambiguation: 'This chunk is about the interaction between guild roles and guild management surfaces, not a hidden admin escalation path.',
      mechanics: ['Guilds Overview', 'Guild Roles and Management', 'Guild Activity Snapshot'],
      tags: ['trackerai', 'guilds', 'faq', 'roles', 'owners', 'officers'],
      interaction_type: 'cross_system',
      interaction_summary: 'Guilds Overview, Guild Roles and Management, and Guild Activity Snapshot together explain what extra control owners and officers have and where that control shows up in practice.',
      paragraphs: [
        'Guilds Overview frames guilds as a shared coordination feature, Guild Roles and Management explains which actions belong to owners, officers, or regular members, and Guild Activity Snapshot shows the member-focused surface where much of that management becomes visible.',
        'That is why owners can handle heavier actions like ownership transfer or guild deletion, while officers help with member and invite management and regular members mostly work from the shared activity view.',
        'When users ask what their role allows, the answer should be grounded in those mechanics by name: Guild Roles and Management defines the permission level, and Guild Activity Snapshot is one of the places where those role-based actions are actually surfaced.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_guilds_faq_leaderboard_01',
      source: 'Guilds Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why is my guild missing from leaderboard filters?',
      title: 'Why is my guild missing from leaderboard filters?',
      disambiguation: 'This chunk is about the interaction between guild membership state and leaderboard visibility, not a score-sorting algorithm.',
      mechanics: ['Guilds Overview', 'Guild Membership and Slots', 'Guild Leaderboard Visibility'],
      tags: ['trackerai', 'guilds', 'faq', 'leaderboard', 'visibility', 'filters'],
      interaction_type: 'conditional',
      interaction_summary: 'Guilds Overview, Guild Membership and Slots, and Guild Leaderboard Visibility explain why a guild can exist normally but still be absent from leaderboard filters.',
      paragraphs: [
        'Guilds Overview tells the user that guilds are broader than leaderboard presence, Guild Membership and Slots explains the member-count side of guild structure, and Guild Leaderboard Visibility explains the rule that at least three members and leaderboard participation both matter.',
        'That means a guild can be real and usable without being leaderboard-visible yet, which is often the confusion behind this question.',
        'The friendly answer should identify Guild Leaderboard Visibility directly and then check whether Guild Membership and Slots shows enough members, because the blocker may be size, opt-in status, or both.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_guilds_faq_chat_01',
      source: 'Guilds Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How does guild chat work?',
      title: 'How does guild chat work?',
      disambiguation: 'This chunk is about the interaction between guild membership and the guild chat surface, not a full messaging-backend description.',
      mechanics: ['Guilds Overview', 'Guild Membership and Slots', 'Guild Chat Drawer'],
      tags: ['trackerai', 'guilds', 'faq', 'chat', 'drawer', 'messages'],
      interaction_type: 'cross_system',
      interaction_summary: 'Guilds Overview, Guild Membership and Slots, and Guild Chat Drawer connect guild membership to the header-based chat experience users actually see.',
      paragraphs: [
        'Guilds Overview explains that guilds are an ongoing social feature, Guild Membership and Slots explains why the chat surface depends on being in at least one guild, and Guild Chat Drawer explains the header button, per-guild tabs, unread counts, and cached recent messages.',
        'That relationship is why guild chat is not shown for every visitor by default: the user needs guild access and the feature enabled before Guild Chat Drawer appears.',
        'If someone asks why the chat button is missing or what it does, the clean answer is to name the mechanics directly: Guild Membership and Slots determines whether the user has guild access, and Guild Chat Drawer is the actual messaging surface once that access exists.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_guilds_faq_ai_01',
      source: 'Guilds Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do with guilds?',
      title: 'What can TrackerAI help me do with guilds?',
      disambiguation: 'This chunk is about the interaction between guild site knowledge and TrackerAI help boundaries, not unrestricted automation or admin bypasses.',
      mechanics: ['Guilds Overview', 'Guild Search Joining and Creation', 'Guild Activity Snapshot', 'Guild Chat Drawer', 'Guilds AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'guilds', 'faq', 'ai help', 'chat', 'actions'],
      interaction_type: 'conditional',
      interaction_summary: 'Guilds Overview, Guild Search Joining and Creation, Guild Activity Snapshot, Guild Chat Drawer, Guilds AI Help Coverage, and TrackerAI Safety Guardrails define both the useful guild help the assistant can provide and the limits it still has to respect.',
      paragraphs: [
        'Guilds Overview is the orientation layer, Guild Search Joining and Creation covers common setup questions, Guild Activity Snapshot covers member activity and run-review questions, and Guild Chat Drawer covers the live communication surface users see in the header.',
        'Guilds AI Help Coverage explains why those are good conversational domains for the assistant, especially when the user wants guidance, interpretation, or a clear next step instead of a raw dump of site internals.',
        'TrackerAI Safety Guardrails is the rule that keeps this bounded: the assistant can help explain, navigate, and support normal actions around those guild mechanics without turning risky actions into something it should fire blindly.',
      ],
    }),
  ]
}
