import {
  LEADERBOARD_AI_FACTS,
  LEADERBOARD_BEMERGED_FACTS,
  LEADERBOARD_CACHE_FACTS,
  LEADERBOARD_ENTRY_FACTS,
  LEADERBOARD_FILTERS_FACTS,
  LEADERBOARD_GUILD_FACTS,
  LEADERBOARD_LIFETIME_FACTS,
  LEADERBOARD_MODES_FACTS,
  LEADERBOARD_OVERVIEW_FACTS,
  LEADERBOARD_PARTICIPATION_FACTS,
  LEADERBOARD_USER_RANK_FACTS,
} from './trackerAiLeaderboardSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiLeaderboardCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_leaderboard_overview_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Leaderboard',
      title: 'Leaderboard Overview',
      disambiguation: 'This chunk is about the Leaderboard Overview mechanic itself, not its interactions. It is not a raw ranking export, a secret moderation dashboard, or a gameplay progression guide.',
      mechanics: ['Leaderboard Overview'],
      tags: ['trackerai', 'leaderboard', 'site page', 'overview', 'header'],
      paragraphs: [...LEADERBOARD_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_leaderboard_filters_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Filters and Columns',
      title: 'Leaderboard Filters and Columns',
      disambiguation: 'This chunk is about the Leaderboard Filters and Columns mechanic itself, not its interactions. It is not a data query language or a guarantee that every filter applies to every mode.',
      mechanics: ['Leaderboard Filters and Columns'],
      tags: ['trackerai', 'leaderboard', 'filters', 'search', 'columns', 'verified'],
      paragraphs: [...LEADERBOARD_FILTERS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_leaderboard_modes_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Modes and Tiers',
      title: 'Leaderboard Modes and Tiers',
      disambiguation: 'This chunk is about the Leaderboard Modes and Tiers mechanic itself, not its interactions. It is not a formula note about how every score is computed.',
      mechanics: ['Leaderboard Modes and Tiers'],
      tags: ['trackerai', 'leaderboard', 'tiers', 'tower', 'lifetime', 'bemerged'],
      paragraphs: [...LEADERBOARD_MODES_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_leaderboard_bemerged_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'BeMerged View',
      title: 'Leaderboard BeMerged View',
      disambiguation: 'This chunk is about the Leaderboard BeMerged View mechanic itself, not its interactions. It is not the full BeMerged game rules page or a Tower verification guide.',
      mechanics: ['Leaderboard BeMerged View'],
      tags: ['trackerai', 'leaderboard', 'bemerged', 'metrics', 'time', 'shards'],
      paragraphs: [...LEADERBOARD_BEMERGED_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_leaderboard_lifetime_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Lifetime Stats View',
      title: 'Leaderboard Lifetime Stats View',
      disambiguation: 'This chunk is about the Leaderboard Lifetime Stats View mechanic itself, not its interactions. It is not the lifetime tracker page or a tower-run ranking formula.',
      mechanics: ['Leaderboard Lifetime Stats View'],
      tags: ['trackerai', 'leaderboard', 'lifetime', 'metrics', 'totals', 'comparison'],
      paragraphs: [...LEADERBOARD_LIFETIME_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_leaderboard_participation_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Participation Settings',
      title: 'Leaderboard Participation Settings',
      disambiguation: 'This chunk is about the Leaderboard Participation Settings mechanic itself, not its interactions. It is not a blanket promise that every run is automatically published or visible.',
      mechanics: ['Leaderboard Participation Settings'],
      tags: ['trackerai', 'leaderboard', 'participation', 'settings', 'publish'],
      paragraphs: [...LEADERBOARD_PARTICIPATION_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_leaderboard_user_rank_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Your Rank Summary',
      title: 'Leaderboard Your Rank Summary',
      disambiguation: 'This chunk is about the Leaderboard Your Rank Summary mechanic itself, not its interactions. It is not a guarantee that the user will have a rank for every metric.',
      mechanics: ['Leaderboard Your Rank Summary'],
      tags: ['trackerai', 'leaderboard', 'rank', 'user rank', 'summary'],
      paragraphs: [...LEADERBOARD_USER_RANK_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_leaderboard_entries_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Entry Details and Reports',
      title: 'Leaderboard Entry Details and Reports',
      disambiguation: 'This chunk is about the Leaderboard Entry Details and Reports mechanic itself, not its interactions. It is not a full moderation manual or a guarantee that every entry has a screenshot.',
      mechanics: ['Leaderboard Entry Details and Reports'],
      tags: ['trackerai', 'leaderboard', 'entries', 'screenshots', 'reports', 'dialogs'],
      paragraphs: [...LEADERBOARD_ENTRY_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_leaderboard_guilds_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Guild Filtering',
      title: 'Leaderboard Guild Filtering',
      disambiguation: 'This chunk is about the Leaderboard Guild Filtering mechanic itself, not its interactions. It is not the same thing as guild membership management or general guild chat behavior.',
      mechanics: ['Leaderboard Guild Filtering'],
      tags: ['trackerai', 'leaderboard', 'guilds', 'filters', 'tower only'],
      paragraphs: [...LEADERBOARD_GUILD_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_leaderboard_cache_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Cache and Reload Behavior',
      title: 'Leaderboard Cache and Reload Behavior',
      disambiguation: 'This chunk is about the Leaderboard Cache and Reload Behavior mechanic itself, not its interactions. It is not a low-level storage implementation dump.',
      mechanics: ['Leaderboard Cache and Reload Behavior'],
      tags: ['trackerai', 'leaderboard', 'cache', 'offline', 'reload'],
      paragraphs: [...LEADERBOARD_CACHE_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_leaderboard_ai_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on Leaderboard',
      title: 'Leaderboard AI Help Coverage',
      disambiguation: 'This chunk is about the Leaderboard AI Help Coverage mechanic itself, not its interactions. It is not a promise of unrestricted moderation or hidden leaderboard commands.',
      mechanics: ['Leaderboard AI Help Coverage'],
      tags: ['trackerai', 'leaderboard', 'ai help', 'filters', 'rank', 'guidance'],
      paragraphs: [...LEADERBOARD_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_leaderboard_faq_lifetime_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How does the lifetime leaderboard work?',
      title: 'How does the lifetime leaderboard work?',
      disambiguation: 'This chunk is about the interaction between the lifetime tracker page and the lifetime leaderboard mode, not the full tracker edit workflow.',
      mechanics: ['Leaderboard Modes and Tiers', 'Leaderboard Lifetime Stats View', 'Lifetime Tracker and Lifetime Leaderboard'],
      tags: ['trackerai', 'leaderboard', 'faq', 'lifetime', 'metrics', 'tracker'],
      interaction_type: 'cross_system',
      interaction_summary: 'Leaderboard Modes and Tiers, Leaderboard Lifetime Stats View, and Lifetime Tracker and Lifetime Leaderboard explain why lifetime leaderboard is its own comparison mode and where those numbers come from conceptually.',
      paragraphs: [
        'Leaderboard Modes and Tiers explains that Lifetime Stats is its own mode, Leaderboard Lifetime Stats View explains the lifetime-only metric set, and Lifetime Tracker and Lifetime Leaderboard explains the broader relationship between the maintenance page and the comparison page.',
        'That relationship matters because users often think they are looking at a run leaderboard when the lifetime view is actually comparing accumulated account totals.',
        'The clear answer is to name those mechanics directly: switch with Leaderboard Modes and Tiers, read the columns through Leaderboard Lifetime Stats View, and use Lifetime Tracker and Lifetime Leaderboard when the real question is how the tracker page and leaderboard page fit together.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_leaderboard_faq_bemerged_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How does the BeMerged leaderboard work?',
      title: 'How does the BeMerged leaderboard work?',
      disambiguation: 'This chunk is about the interaction between BeMerged-specific leaderboard browsing and the dedicated BeMerged page, not the full internal game engine or moderation tooling.',
      mechanics: ['Leaderboard Modes and Tiers', 'Leaderboard BeMerged View', 'BeMerged Personal Bests and Publishing'],
      tags: ['trackerai', 'leaderboard', 'faq', 'bemerged', 'metrics', 'personal bests'],
      interaction_type: 'cross_system',
      interaction_summary: 'Leaderboard Modes and Tiers, Leaderboard BeMerged View, and BeMerged Personal Bests and Publishing explain why the BeMerged leaderboard behaves like its own mode and where those numbers come from.',
      paragraphs: [
        'Leaderboard Modes and Tiers explains that BeMerged is its own leaderboard mode, Leaderboard BeMerged View explains the BeMerged-specific columns users actually see there, and BeMerged Personal Bests and Publishing explains how BeMerged attempts feed those results.',
        'That connection matters because users often expect Tower-style filters or Tower-style metrics to keep working, but the BeMerged view is driven by different attempt data and a different metric set.',
        'The clean answer is to name those mechanics directly: switch with Leaderboard Modes and Tiers, read the BeMerged-specific columns through Leaderboard BeMerged View, and use BeMerged Personal Bests and Publishing when the question is really about where a score came from or why it has not appeared yet.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_leaderboard_faq_find_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I use the leaderboard page?',
      title: 'How do I use the leaderboard page?',
      disambiguation: 'This chunk is about the interaction between the leaderboard page and its normal browsing controls, not a gameplay optimization guide.',
      mechanics: ['Leaderboard Overview', 'Leaderboard Filters and Columns', 'Leaderboard Modes and Tiers', 'Leaderboard Lifetime Stats View', 'Leaderboard BeMerged View'],
      tags: ['trackerai', 'leaderboard', 'faq', 'use page', 'filters', 'tiers'],
      interaction_type: 'cross_system',
      interaction_summary: 'Leaderboard Overview, Leaderboard Filters and Columns, Leaderboard Modes and Tiers, Leaderboard Lifetime Stats View, and Leaderboard BeMerged View work together to explain how users browse the page without guessing which controls apply to which kind of leaderboard.',
      paragraphs: [
        'Leaderboard Overview explains what the page is for, Leaderboard Filters and Columns explains the search, verified, guild, and column controls, Leaderboard Modes and Tiers explains why Tower, Lifetime Stats, and BeMerged do not all behave the same way, Leaderboard Lifetime Stats View explains the lifetime-specific column set, and Leaderboard BeMerged View explains the BeMerged-specific column set once that mode is selected.',
        'That relationship matters because the page becomes much easier to understand once the user knows they are choosing both a viewing mode and the matching set of useful controls.',
        'The clearest answer is to name those mechanics directly: start with Leaderboard Overview, use Leaderboard Modes and Tiers to choose the right view, use Leaderboard Lifetime Stats View or Leaderboard BeMerged View when those are the selected modes, and then use Leaderboard Filters and Columns for the controls that still apply in that mode.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_leaderboard_faq_show_up_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why am I not showing up on the leaderboard?',
      title: 'Why am I not showing up on the leaderboard?',
      disambiguation: 'This chunk is about the interaction between leaderboard participation, run publication, and verification-related entry visibility, not a single bug condition.',
      mechanics: ['Leaderboard Overview', 'Leaderboard Participation Settings', 'Run Tracker Sync and Cloud', 'Run Tracker Screenshots and Verification'],
      tags: ['trackerai', 'leaderboard', 'faq', 'missing entry', 'participation', 'verification'],
      interaction_type: 'conditional',
      interaction_summary: 'Leaderboard Overview, Leaderboard Participation Settings, Run Tracker Sync and Cloud, and Run Tracker Screenshots and Verification explain the most common reasons a user can browse leaderboard normally but still not appear in it.',
      paragraphs: [
        'Leaderboard Overview frames the page the user is checking, Leaderboard Participation Settings covers whether they opted into leaderboard publication, Run Tracker Sync and Cloud covers whether the underlying data actually made it through the normal sync and publish path, and Run Tracker Screenshots and Verification covers why some entries have stronger verification support than others.',
        'That is why this question rarely has just one answer. A user may be missing because they turned participation off, because their data is not yet reflected through the normal sync path, or because the entry they expected is not in a usable leaderboard-ready state.',
        'For friendly help, the assistant should name those mechanics clearly instead of blaming one mystery failure: check Leaderboard Participation Settings first, then look at Run Tracker Sync and Cloud and Run Tracker Screenshots and Verification if the user expected a specific run to be visible.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_leaderboard_faq_rank_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I find my rank quickly?',
      title: 'How do I find my rank quickly?',
      disambiguation: 'This chunk is about the interaction between leaderboard browsing and the user-rank summary, not a promise that all metrics will always have a populated rank.',
      mechanics: ['Leaderboard Overview', 'Leaderboard Your Rank Summary', 'Leaderboard Filters and Columns'],
      tags: ['trackerai', 'leaderboard', 'faq', 'rank', 'your rank', 'search'],
      interaction_type: 'cross_system',
      interaction_summary: 'Leaderboard Overview, Leaderboard Your Rank Summary, and Leaderboard Filters and Columns explain the quickest way to check personal ranking without manually scanning every visible row.',
      paragraphs: [
        'Leaderboard Overview gives the page context, Leaderboard Your Rank Summary explains the personal summary row, and Leaderboard Filters and Columns explains the view controls that can make that summary easier to interpret.',
        'That matters because rank on this page is metric-specific, so a user may want to combine the summary row with a narrower mode, search term, or filter instead of assuming one global rank answers everything.',
        'When someone asks where to find their standing, the answer should point them to Leaderboard Your Rank Summary first and then use Leaderboard Filters and Columns if they need to narrow down which leaderboard view they actually care about.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_leaderboard_faq_guilds_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do guilds work on leaderboard?',
      title: 'How do guilds work on leaderboard?',
      disambiguation: 'This chunk is about the interaction between leaderboard guild filters and guild eligibility rules, not general guild membership management.',
      mechanics: ['Leaderboard Overview', 'Leaderboard Guild Filtering', 'Guild Leaderboard Visibility'],
      tags: ['trackerai', 'leaderboard', 'faq', 'guilds', 'filters', 'eligibility'],
      interaction_type: 'conditional',
      interaction_summary: 'Leaderboard Overview, Leaderboard Guild Filtering, and Guild Leaderboard Visibility explain how guild-based leaderboard browsing depends on both the leaderboard mode and the guild being eligible to appear.',
      paragraphs: [
        'Leaderboard Overview tells the user what page they are on, Leaderboard Guild Filtering explains that guild filtering only applies in supported tower views, and Guild Leaderboard Visibility explains why not every guild is eligible for those filters in the first place.',
        'That means a missing guild is not always a broken filter. Sometimes the selected mode does not support guild filtering, and sometimes the guild itself is not eligible because of its own visibility rules.',
        'For clear answers, the assistant should say those mechanics by name: use Leaderboard Guild Filtering to check whether the current view supports guilds at all, then use Guild Leaderboard Visibility to explain why a specific guild may still be absent.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_leaderboard_faq_entry_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Can I inspect or report a leaderboard entry?',
      title: 'Can I inspect or report a leaderboard entry?',
      disambiguation: 'This chunk is about the interaction between leaderboard entry dialogs and linked run evidence, not a hidden moderation-only flow.',
      mechanics: ['Leaderboard Overview', 'Leaderboard Entry Details and Reports', 'Run Tracker Screenshots and Verification'],
      tags: ['trackerai', 'leaderboard', 'faq', 'entry details', 'report', 'screenshots'],
      interaction_type: 'cross_system',
      interaction_summary: 'Leaderboard Overview, Leaderboard Entry Details and Reports, and Run Tracker Screenshots and Verification explain how a leaderboard number can lead into screenshot-backed context or into a suspicious-entry report flow.',
      paragraphs: [
        'Leaderboard Overview sets the page context, Leaderboard Entry Details and Reports explains the cell-to-dialog flow, and Run Tracker Screenshots and Verification explains why some entries can resolve to meaningful screenshot or verification evidence.',
        'That relationship is what makes the leaderboard feel inspectable instead of opaque. Users are not limited to a bare number when the underlying run details can be resolved.',
        'A helpful answer should name the mechanics directly: open the entry through Leaderboard Entry Details and Reports, then rely on Run Tracker Screenshots and Verification when the user wants proof, context, or stronger confidence in what the entry represents.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_leaderboard_faq_ai_01',
      source: 'Leaderboard Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do on leaderboard?',
      title: 'What can TrackerAI help me do on leaderboard?',
      disambiguation: 'This chunk is about the interaction between leaderboard page knowledge and TrackerAI help boundaries, not unrestricted moderation or backend access.',
      mechanics: ['Leaderboard Overview', 'Leaderboard Filters and Columns', 'Leaderboard Modes and Tiers', 'Leaderboard AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'leaderboard', 'faq', 'ai help', 'filters', 'modes'],
      interaction_type: 'conditional',
      interaction_summary: 'Leaderboard Overview, Leaderboard Filters and Columns, Leaderboard Modes and Tiers, Leaderboard AI Help Coverage, and TrackerAI Safety Guardrails define where the assistant is most useful on leaderboard and where it still needs to stay cautious.',
      paragraphs: [
        'Leaderboard Overview provides the page-level context, Leaderboard Filters and Columns and Leaderboard Modes and Tiers cover the most common navigation and interpretation questions, and Leaderboard AI Help Coverage explains why those are strong conversational tasks for the assistant.',
        'This is where TrackerAI is most useful for normal users: clarifying why a filter is locked, explaining what changed between modes, helping interpret personal rank, or pointing out why an entry or guild may be missing.',
        'TrackerAI Safety Guardrails is the limit that keeps the page help honest, because explaining and navigating leaderboard is very different from assuming permission to perform sensitive actions automatically.',
      ],
    }),
  ]
}
