import {
  EULA_PAGE_ACCOUNTS_FACTS,
  EULA_PAGE_ACCEPTABLE_USE_FACTS,
  EULA_PAGE_AI_FACTS,
  EULA_PAGE_CONTACT_FACTS,
  EULA_PAGE_CONTENT_FACTS,
  EULA_PAGE_GIVEAWAY_BOT_FACTS,
  EULA_PAGE_LIABILITY_FACTS,
  EULA_PAGE_OVERVIEW_FACTS,
  EULA_PAGE_PRIVACY_FACTS,
  EULA_PAGE_SCOPE_FACTS,
} from './trackerAiEulaSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiEulaCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_eula_overview_01',
      source: 'EULA Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'EULA Page Overview',
      title: 'EULA Page Overview',
      disambiguation: 'This chunk describes the EULA Page Overview mechanic itself, not its interactions. It is not a substitute for legal advice outside the route text.',
      mechanics: ['EULA Page Overview'],
      tags: ['trackerai', 'eula', 'terms', 'privacy', 'page', 'overview'],
      paragraphs: [...EULA_PAGE_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_eula_scope_01',
      source: 'EULA Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Covered Services',
      title: 'EULA Page Covered Services',
      disambiguation: 'This chunk describes the EULA Page Covered Services mechanic itself, not its interactions. It is not a generic statement about every external service on the internet.',
      mechanics: ['EULA Page Covered Services'],
      tags: ['trackerai', 'eula', 'terms', 'discord bots', 'scope'],
      paragraphs: [...EULA_PAGE_SCOPE_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_eula_use_01',
      source: 'EULA Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Acceptable Use',
      title: 'EULA Page Acceptable Use',
      disambiguation: 'This chunk describes the EULA Page Acceptable Use mechanic itself, not its interactions. It is not a technical anti-abuse implementation spec.',
      mechanics: ['EULA Page Acceptable Use'],
      tags: ['trackerai', 'eula', 'acceptable use', 'harassment', 'scraping'],
      paragraphs: [...EULA_PAGE_ACCEPTABLE_USE_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_eula_accounts_01',
      source: 'EULA Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Accounts and Verification',
      title: 'EULA Page Accounts and Verification',
      disambiguation: 'This chunk describes the EULA Page Accounts and Verification mechanic itself, not its interactions. It is not a login help article.',
      mechanics: ['EULA Page Accounts and Verification'],
      tags: ['trackerai', 'eula', 'accounts', 'verification', 'suspension'],
      paragraphs: [...EULA_PAGE_ACCOUNTS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_eula_content_01',
      source: 'EULA Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Content and Submissions',
      title: 'EULA Page Content and Submissions',
      disambiguation: 'This chunk describes the EULA Page Content and Submissions mechanic itself, not its interactions. It is not a full copyright policy handbook.',
      mechanics: ['EULA Page Content and Submissions'],
      tags: ['trackerai', 'eula', 'content', 'uploads', 'screenshots'],
      paragraphs: [...EULA_PAGE_CONTENT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_eula_giveaway_bot_01',
      source: 'EULA Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Giveaways and Bot Use',
      title: 'EULA Page Giveaways and Bot Use',
      disambiguation: 'This chunk describes the EULA Page Giveaways and Bot Use mechanic itself, not its interactions. It is not the separate giveaway rules page by itself.',
      mechanics: ['EULA Page Giveaways and Bot Use'],
      tags: ['trackerai', 'eula', 'giveaways', 'discord bots', 'permissions'],
      paragraphs: [...EULA_PAGE_GIVEAWAY_BOT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_eula_privacy_01',
      source: 'EULA Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Privacy and Retention',
      title: 'EULA Page Privacy and Retention',
      disambiguation: 'This chunk describes the EULA Page Privacy and Retention mechanic itself, not its interactions. It is not a generalized privacy-law interpretation.',
      mechanics: ['EULA Page Privacy and Retention'],
      tags: ['trackerai', 'eula', 'privacy', 'cookies', 'browser storage', 'retention'],
      paragraphs: [...EULA_PAGE_PRIVACY_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_eula_liability_01',
      source: 'EULA Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Liability and Changes',
      title: 'EULA Page Liability and Changes',
      disambiguation: 'This chunk describes the EULA Page Liability and Changes mechanic itself, not its interactions. It is not a promise that the terms never change.',
      mechanics: ['EULA Page Liability and Changes'],
      tags: ['trackerai', 'eula', 'liability', 'policy changes'],
      paragraphs: [...EULA_PAGE_LIABILITY_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_eula_contact_01',
      source: 'EULA Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Contact Guidance',
      title: 'EULA Page Contact Guidance',
      disambiguation: 'This chunk describes the EULA Page Contact Guidance mechanic itself, not its interactions. It is not a support-ticket workflow implementation spec.',
      mechanics: ['EULA Page Contact Guidance'],
      tags: ['trackerai', 'eula', 'contact', 'reporting system', 'discord'],
      paragraphs: [...EULA_PAGE_CONTACT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_eula_ai_01',
      source: 'EULA Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on EULA Page',
      title: 'EULA Page AI Help Coverage',
      disambiguation: 'This chunk describes the EULA Page AI Help Coverage mechanic itself, not its interactions. It is not legal advice beyond the page text.',
      mechanics: ['EULA Page AI Help Coverage'],
      tags: ['trackerai', 'eula', 'ai help', 'terms', 'privacy'],
      paragraphs: [...EULA_PAGE_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_eula_faq_scope_01',
      source: 'EULA Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Do the site terms also cover the Discord bots?',
      title: 'Do the site terms also cover the Discord bots?',
      disambiguation: 'This chunk is about the interaction between the EULA scope section and the bot-use section, not a guess based on external policy pages.',
      mechanics: ['EULA Page Covered Services', 'EULA Page Giveaways and Bot Use'],
      tags: ['trackerai', 'eula', 'faq', 'discord bots', 'scope'],
      interaction_type: 'cross_system',
      interaction_summary: 'EULA Page Covered Services and EULA Page Giveaways and Bot Use explain why the live terms page explicitly covers both the website and the Discord bots.',
      paragraphs: [
        'EULA Page Covered Services explains that the introduction explicitly includes the related Discord bots, and EULA Page Giveaways and Bot Use reinforces that those bots have their own policy section on the same route.',
        'That is why the correct page-level answer is not maybe or implied. The route says it directly.',
        'The clearest answer is to name those mechanics directly: yes, the terms page explicitly covers the website and the listed Discord bots together.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_eula_faq_privacy_01',
      source: 'EULA Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What does the EULA page say about privacy, cookies, and stored data?',
      title: 'What does the EULA page say about privacy, cookies, and stored data?',
      disambiguation: 'This chunk is about the interaction between the privacy section and the data-retention-and-cookies section, not a legal conclusion outside the route text.',
      mechanics: ['EULA Page Privacy and Retention', 'EULA Page Overview'],
      tags: ['trackerai', 'eula', 'faq', 'privacy', 'cookies', 'storage'],
      interaction_type: 'cross_system',
      interaction_summary: 'EULA Page Privacy and Retention and EULA Page Overview explain how the route presents privacy handling, browser storage, and cache-refresh behavior as part of one policy page.',
      paragraphs: [
        'EULA Page Privacy and Retention explains the no-sell-or-share statement, the functional and operational use of retained data, deletion or anonymization requests, and the cookies and browser-storage notice.',
        'EULA Page Overview matters because those policies are not hidden in a separate privacy-only route. They are part of this single Terms of Service and Privacy Policy page.',
        'The clearest answer is to name those mechanics directly: the page says data is not sold or shared, browser storage and cookies are used for persistence and experience, and cached assets may refresh automatically when the site updates.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_eula_faq_uploads_01',
      source: 'EULA Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What does the EULA page say about uploaded runs and screenshots?',
      title: 'What does the EULA page say about uploaded runs and screenshots?',
      disambiguation: 'This chunk is about the interaction between content submissions and accounts policy, not a broad copyright-law explanation.',
      mechanics: ['EULA Page Content and Submissions', 'EULA Page Accounts and Verification'],
      tags: ['trackerai', 'eula', 'faq', 'uploads', 'screenshots', 'content'],
      interaction_type: 'cross_system',
      interaction_summary: 'EULA Page Content and Submissions and EULA Page Accounts and Verification explain what rights the site receives for uploaded content and how that ties back to verified account use.',
      paragraphs: [
        'EULA Page Content and Submissions explains the non-exclusive hosting and display license for runs, screenshots, and other submitted content, while EULA Page Accounts and Verification explains that some site features are tied to account and verification context.',
        'That is why uploaded content is framed as both a user submission right issue and part of an account-governed service.',
        'The clearest answer is to name those mechanics directly: the page says uploaded runs and screenshots may be hosted and displayed by the site under a non-exclusive license, and users should only upload content they are allowed to share.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_eula_faq_contact_01',
      source: 'EULA Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How should I contact the site about terms or privacy questions?',
      title: 'How should I contact the site about terms or privacy questions?',
      disambiguation: 'This chunk is about the interaction between the EULA contact section and the page as a whole, not a hidden support process outside the route.',
      mechanics: ['EULA Page Contact Guidance', 'EULA Page Overview'],
      tags: ['trackerai', 'eula', 'faq', 'contact', 'privacy', 'terms'],
      interaction_type: 'cross_system',
      interaction_summary: 'EULA Page Contact Guidance and EULA Page Overview explain where the route tells users to raise terms or privacy questions and why that guidance is part of the main page body.',
      paragraphs: [
        'EULA Page Contact Guidance explains that users should reach the administrators through the reporting system or JD on Discord, and EULA Page Overview explains that this route is the central policy reference page where that escalation path is published.',
        'That is why a user does not need a separate hidden help document to know how policy questions should be escalated.',
        'The clearest answer is to name those mechanics directly: the EULA page directs users to the reporting system or JD on Discord for terms and privacy questions.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_eula_faq_ai_01',
      source: 'EULA Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do on the EULA and Terms page?',
      title: 'What can TrackerAI help me do on the EULA and Terms page?',
      disambiguation: 'This chunk is about the interaction between EULA-page knowledge and TrackerAI help boundaries, not binding legal advice beyond the route text.',
      mechanics: ['EULA Page Overview', 'EULA Page AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'eula', 'faq', 'ai help', 'terms', 'privacy'],
      interaction_type: 'conditional',
      interaction_summary: 'EULA Page Overview, EULA Page AI Help Coverage, and TrackerAI Safety Guardrails define the kinds of section-by-section explanation the assistant can provide on the policy route without pretending to replace legal counsel.',
      paragraphs: [
        'EULA Page Overview provides the route context, and EULA Page AI Help Coverage explains why this page is a good fit for section summaries and heading-level policy guidance.',
        'This is where TrackerAI is most useful for normal users: pointing to the right section for privacy, giveaways, bot use, content uploads, liability, or contact guidance when they do not want to read the full page top to bottom.',
        'TrackerAI Safety Guardrails is the boundary that keeps that help honest, because summarizing the page text is different from claiming to provide independent legal advice beyond what the route actually says.',
      ],
    }),
  ]
}
