import {
  BOTS_CALCULATOR_INPUT_FACTS,
  BOTS_CALCULATOR_OUTPUT_FACTS,
  BOTS_CALCULATOR_OVERVIEW_FACTS,
  BOTS_CALCULATOR_VIEW_FACTS,
  BOTS_TRACKER_AI_FACTS,
  BOTS_TRACKER_CALCULATOR_LINK_FACTS,
  BOTS_TRACKER_OVERVIEW_FACTS,
  BOTS_TRACKER_OVERVIEW_TAB_FACTS,
  BOTS_TRACKER_PROGRESS_FACTS,
  BOTS_TRACKER_SYNC_FACTS,
} from './trackerAiBotsSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiBotsCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bots_overview_01',
      source: 'Bots Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Bots Tracker',
      title: 'Bots Tracker Overview',
      disambiguation: 'This chunk describes the Bots Tracker Overview mechanic itself, not its interactions. It is not the general bot-mechanics encyclopedia or raw medal formulas outside the site tools.',
      mechanics: ['Bots Tracker Overview'],
      tags: ['trackerai', 'bots', 'tracker', 'site page', 'overview'],
      paragraphs: [...BOTS_TRACKER_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bots_progress_01',
      source: 'Bots Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Progress Planning Table',
      title: 'Bots Tracker Progress Planning Table',
      disambiguation: 'This chunk describes the Bots Tracker Progress Planning Table mechanic itself, not its interactions. It is not the calculator breakdown table or a generic medal strategy guide.',
      mechanics: ['Bots Tracker Progress Planning Table'],
      tags: ['trackerai', 'bots', 'tracker', 'progress', 'medals', 'events'],
      paragraphs: [...BOTS_TRACKER_PROGRESS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bots_overview_tab_01',
      source: 'Bots Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'All Bots Tab',
      title: 'Bots Tracker All Bots Tab',
      disambiguation: 'This chunk describes the Bots Tracker All Bots Tab mechanic itself, not its interactions. It is not the progress table or a standalone preset system outside the tracker page.',
      mechanics: ['Bots Tracker All Bots Tab'],
      tags: ['trackerai', 'bots', 'tracker', 'overview', 'presets', 'disabled'],
      paragraphs: [...BOTS_TRACKER_OVERVIEW_TAB_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bots_sync_01',
      source: 'Bots Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Local Save and Sync',
      title: 'Bots Tracker Local Save and Sync',
      disambiguation: 'This chunk describes the Bots Tracker Local Save and Sync mechanic itself, not its interactions. It is not a low-level sync protocol dump.',
      mechanics: ['Bots Tracker Local Save and Sync'],
      tags: ['trackerai', 'bots', 'tracker', 'sync', 'local save', 'cloud'],
      paragraphs: [...BOTS_TRACKER_SYNC_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bots_calculator_overview_01',
      source: 'Bot Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Bot Calculator',
      title: 'Bot Calculator Overview',
      disambiguation: 'This chunk describes the Bot Calculator Overview mechanic itself, not its interactions. It is not the whole tracker page or the general bot knowledge layer.',
      mechanics: ['Bot Calculator Overview'],
      tags: ['trackerai', 'bots', 'calculator', 'site page', 'overview'],
      paragraphs: [...BOTS_CALCULATOR_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bots_calculator_inputs_01',
      source: 'Bot Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Calculator Inputs and Filters',
      title: 'Bot Calculator Inputs and Filters',
      disambiguation: 'This chunk describes the Bot Calculator Inputs and Filters mechanic itself, not its interactions. It is not the tracker progress table or a hidden sync system.',
      mechanics: ['Bot Calculator Inputs and Filters'],
      tags: ['trackerai', 'bots', 'calculator', 'inputs', 'labs', 'filters'],
      paragraphs: [...BOTS_CALCULATOR_INPUT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bots_calculator_outputs_01',
      source: 'Bot Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Calculator Outputs',
      title: 'Bot Calculator Outputs',
      disambiguation: 'This chunk describes the Bot Calculator Outputs mechanic itself, not its interactions. It is not a tracker sync explanation or a promise that every bot uses identical stat shapes.',
      mechanics: ['Bot Calculator Outputs'],
      tags: ['trackerai', 'bots', 'calculator', 'outputs', 'medals', 'cumulative'],
      paragraphs: [...BOTS_CALCULATOR_OUTPUT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bots_calculator_views_01',
      source: 'Bot Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Calculator Views and Filters',
      title: 'Bot Calculator Views and Filters',
      disambiguation: 'This chunk describes the Bot Calculator Views and Filters mechanic itself, not its interactions. It is not the tracker progress table or a hidden export system.',
      mechanics: ['Bot Calculator Views and Filters'],
      tags: ['trackerai', 'bots', 'calculator', 'filters', 'views', 'cumulative'],
      paragraphs: [...BOTS_CALCULATOR_VIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bots_link_01',
      source: 'Bots Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Tracker and Calculator Link',
      title: 'Bots Tracker and Calculator Link',
      disambiguation: 'This chunk describes the Bots Tracker and Calculator Link mechanic itself, not its interactions. It is not a claim that the tracker and calculator are identical views.',
      mechanics: ['Bots Tracker and Calculator Link'],
      tags: ['trackerai', 'bots', 'tracker', 'calculator', 'shared context'],
      paragraphs: [...BOTS_TRACKER_CALCULATOR_LINK_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bots_ai_01',
      source: 'Bots Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on Bot Pages',
      title: 'Bots Tracker and Calculator AI Help Coverage',
      disambiguation: 'This chunk describes the Bots Tracker and Calculator AI Help Coverage mechanic itself, not its interactions. It is not unrestricted bulk editing or silent resets.',
      mechanics: ['Bots Tracker and Calculator AI Help Coverage'],
      tags: ['trackerai', 'bots', 'ai help', 'tracker', 'calculator'],
      paragraphs: [...BOTS_TRACKER_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bots_faq_use_01',
      source: 'Bots Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I use the Bots tracker page?',
      title: 'How do I use the Bots tracker page?',
      disambiguation: 'This chunk is about the interaction between the main Bots tracker tabs, not the deeper game meaning of each bot.',
      mechanics: ['Bots Tracker Overview', 'Bots Tracker Progress Planning Table', 'Bots Tracker All Bots Tab', 'Bots Tracker and Calculator Link'],
      tags: ['trackerai', 'bots', 'faq', 'tracker', 'tabs', 'workflow'],
      interaction_type: 'cross_system',
      interaction_summary: 'Bots Tracker Overview, Bots Tracker Progress Planning Table, Bots Tracker All Bots Tab, and Bots Tracker and Calculator Link explain how the tracker splits saved planning, broad roster editing, and calculator handoff into separate surfaces.',
      paragraphs: [
        'Bots Tracker Overview explains the page as a whole, Bots Tracker Progress Planning Table explains the day-to-day medal planning table, Bots Tracker All Bots Tab explains preset-based roster editing, and Bots Tracker and Calculator Link explains how calculator handoff fits into that workflow.',
        'That matters because users often ask where a specific bot task belongs before they ask about medal numbers themselves.',
        'The clearest answer is to name those mechanics directly: use Progress for target planning, use All Bots for broad saved-state maintenance and presets, and use the calculator link when the question becomes detailed medal math for one bot.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bots_faq_tracker_vs_calc_01',
      source: 'Bot Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What is the difference between the Bots tracker and calculator?',
      title: 'What is the difference between the Bots tracker and calculator?',
      disambiguation: 'This chunk is about the interaction between the Bots tracker and calculator, not a claim that one replaces the other.',
      mechanics: ['Bots Tracker Overview', 'Bot Calculator Overview', 'Bots Tracker and Calculator Link'],
      tags: ['trackerai', 'bots', 'faq', 'tracker', 'calculator', 'difference'],
      interaction_type: 'cross_system',
      interaction_summary: 'Bots Tracker Overview, Bot Calculator Overview, and Bots Tracker and Calculator Link explain why one page manages long-term saved progress while the other focuses on detailed per-bot medal planning.',
      paragraphs: [
        'Bots Tracker Overview explains the broader management page, Bot Calculator Overview explains the focused planning page, and Bots Tracker and Calculator Link explains why they share context instead of acting like unrelated tools.',
        'That relationship is the practical answer for users who want to know where to start.',
        'The clearest answer is to name those mechanics directly: use the tracker for long-term saved bot progress, use the calculator for one-bot medal planning, and use the shared-link mechanic for how the two surfaces stay aligned.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bots_faq_medals_01',
      source: 'Bots Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why does the Bots tracker ask for average medals per two weeks?',
      title: 'Why does the Bots tracker ask for average medals per two weeks?',
      disambiguation: 'This chunk is about the interaction between the Bots tracker overview and progress planning table, not a universal medal-income formula outside the site tools.',
      mechanics: ['Bots Tracker Overview', 'Bots Tracker Progress Planning Table'],
      tags: ['trackerai', 'bots', 'faq', 'medals', 'events', 'finish date'],
      interaction_type: 'conditional',
      interaction_summary: 'Bots Tracker Overview and Bots Tracker Progress Planning Table explain why event counts, time-to-target, and finish-date estimates need a personal medal pace input instead of one fixed assumption for everyone.',
      paragraphs: [
        'Bots Tracker Overview explains the page context, and Bots Tracker Progress Planning Table explains that the tracker estimates events needed, time to target, and finish dates from the user\'s own medals-per-two-weeks pace.',
        'That is why the field exists: those projections are only useful if they match the pace the user actually expects.',
        'The clearest answer is to name that mechanic directly: average medals per two weeks is the input that personalizes the tracker\'s event and finish-date estimates.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bots_faq_labs_01',
      source: 'Bot Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why does the Bot calculator ask for lab levels?',
      title: 'Why does the Bot calculator ask for lab levels?',
      disambiguation: 'This chunk is about the interaction between bot lab inputs and calculator outputs, not a generic answer about labs everywhere else on the site.',
      mechanics: ['Bot Calculator Inputs and Filters', 'Bot Calculator Outputs'],
      tags: ['trackerai', 'bots', 'faq', 'labs', 'calculator', 'stats'],
      interaction_type: 'conditional',
      interaction_summary: 'Bot Calculator Inputs and Filters and Bot Calculator Outputs explain why lab settings belong in the bot calculator before medal rows and stat values are interpreted.',
      paragraphs: [
        'Bot Calculator Inputs and Filters explains that each bot has Lab Levels inputs alongside starting and target levels, and Bot Calculator Outputs explains the detailed rows those inputs help shape.',
        'That matters because the calculator is not treating every bot stat as a fixed, context-free number.',
        'The clearest answer is to name those mechanics directly: lab levels are part of the calculator because they influence how the bot\'s normalized stat rows are presented and interpreted.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bots_faq_filters_01',
      source: 'Bot Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why does the Bot calculator table change when I filter stats?',
      title: 'Why does the Bot calculator table change when I filter stats?',
      disambiguation: 'This chunk is about the interaction between Bot Calculator Inputs and Filters, Bot Calculator Views and Filters, and Bot Calculator Outputs, not a display bug or a claim that the underlying costs changed.',
      mechanics: ['Bot Calculator Inputs and Filters', 'Bot Calculator Views and Filters', 'Bot Calculator Outputs'],
      tags: ['trackerai', 'bots', 'faq', 'filters', 'single stat', 'cumulative'],
      interaction_type: 'conditional',
      interaction_summary: 'Bot Calculator Inputs and Filters, Bot Calculator Views and Filters, and Bot Calculator Outputs explain why the bot calculator shifts between a focused one-stat table and a paired multi-stat table depending on the chosen filters.',
      paragraphs: [
        'Bot Calculator Inputs and Filters explains the stat filter and cumulative toggles, Bot Calculator Views and Filters explains the table-shape change, and Bot Calculator Outputs explains the totals and per-level rows users see afterward.',
        'That means a changed table layout usually reflects the current filter mode rather than a change to the saved bot plan itself.',
        'The clearest answer is to name those mechanics directly: filtering to one stat creates a focused one-stat medal path, while leaving multiple stats active keeps the broader comparison table.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bots_faq_sync_01',
      source: 'Bots Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Does the Bots tracker save and sync with the calculator?',
      title: 'Does the Bots tracker save and sync with the calculator?',
      disambiguation: 'This chunk is about the interaction between Bots tracker sync behavior and the shared tracker-calculator workflow, not a low-level store contract.',
      mechanics: ['Bots Tracker Local Save and Sync', 'Bots Tracker and Calculator Link', 'Bot Calculator Inputs and Filters', 'Bot Calculator Views and Filters'],
      tags: ['trackerai', 'bots', 'faq', 'sync', 'shared state', 'calculator'],
      interaction_type: 'conditional',
      interaction_summary: 'Bots Tracker Local Save and Sync, Bots Tracker and Calculator Link, Bot Calculator Inputs and Filters, and Bot Calculator Views and Filters explain how bot state persists and why calculator context often follows the tracker workflow.',
      paragraphs: [
        'Bots Tracker Local Save and Sync explains the persistence layer, Bots Tracker and Calculator Link explains the shared workflow, and Bot Calculator Inputs and Filters and Bot Calculator Views and Filters explain the calculator-side context that stays available across visits.',
        'That is why the calculator can feel like it already knows which bot and level ranges the tracker was working with.',
        'The cleanest answer is to name those mechanics directly: use the sync chunk for persistence, then use the tracker-calculator link and calculator-state chunk for how that saved context carries into the calculator.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bots_faq_presets_01',
      source: 'Bots Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do presets and disabled bots work on the Bots tracker?',
      title: 'How do presets and disabled bots work on the Bots tracker?',
      disambiguation: 'This chunk is about the interaction between the All Bots tab and the Progress planning table, not a claim that disabling a bot deletes its saved data.',
      mechanics: ['Bots Tracker All Bots Tab', 'Bots Tracker Progress Planning Table'],
      tags: ['trackerai', 'bots', 'faq', 'presets', 'disabled', 'tracker'],
      interaction_type: 'cross_system',
      interaction_summary: 'Bots Tracker All Bots Tab and Bots Tracker Progress Planning Table explain how presets preserve different saved bot setups and how disabled bots are treated as inactive planning rows rather than deleted progress.',
      paragraphs: [
        'Bots Tracker All Bots Tab explains where presets, renaming, and enable-or-disable controls live, while Bots Tracker Progress Planning Table shows how those choices affect the active medal-planning view.',
        'That matters because users often want different bot plans without wiping out older saved setups.',
        'The clearest answer is to name those mechanics directly: presets store alternate saved bot setups, and disabling a bot marks it inactive in planning views without deleting the saved levels inside that preset.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bots_faq_ai_01',
      source: 'Bots Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do with the Bots tracker and calculator?',
      title: 'What can TrackerAI help me do with the Bots tracker and calculator?',
      disambiguation: 'This chunk is about the interaction between bot page knowledge and TrackerAI help boundaries, not unrestricted bulk edits or sync control.',
      mechanics: ['Bots Tracker Overview', 'Bot Calculator Overview', 'Bots Tracker and Calculator Link', 'Bots Tracker and Calculator AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'bots', 'faq', 'ai help', 'tracker', 'calculator'],
      interaction_type: 'conditional',
      interaction_summary: 'Bots Tracker Overview, Bot Calculator Overview, Bots Tracker and Calculator Link, Bots Tracker and Calculator AI Help Coverage, and TrackerAI Safety Guardrails define the kinds of bot-page help the assistant can give without pretending it should silently rewrite saved progress.',
      paragraphs: [
        'Bots Tracker Overview and Bot Calculator Overview provide the two page contexts, Bots Tracker and Calculator Link explains why users move between them, and Bots Tracker and Calculator AI Help Coverage explains why this is a strong explanation-and-guidance area for the assistant.',
        'This is where TrackerAI is most useful for normal users: deciding which bot surface to use, understanding medal and finish-date columns, and explaining why a tracker total and a calculator table are related.',
        'TrackerAI Safety Guardrails is the boundary that keeps that help honest, because explanation and interpretation are different from silently changing saved progress, running sync, or clearing all bot levels on the user\'s behalf.',
      ],
    }),
  ]
}
