import {
  LAB_CALCULATOR_INPUT_FACTS,
  LAB_CALCULATOR_OUTPUT_FACTS,
  LAB_CALCULATOR_OVERVIEW_FACTS,
  LAB_CALCULATOR_VIEW_FACTS,
  LAB_TRACKER_ACTIVE_FACTS,
  LAB_TRACKER_AI_FACTS,
  LAB_TRACKER_CALCULATOR_LINK_FACTS,
  LAB_TRACKER_OVERVIEW_FACTS,
  LAB_TRACKER_OVERVIEW_TAB_FACTS,
  LAB_TRACKER_PROGRESS_FACTS,
  LAB_TRACKER_SYNC_FACTS,
  LAB_TRACKER_UPLOAD_FACTS,
} from './trackerAiLabsSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiLabsCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_labs_overview_01',
      source: 'Lab Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Lab Tracker',
      title: 'Lab Tracker Overview',
      disambiguation: 'This chunk is about the Lab Tracker Overview mechanic itself, not its interactions. It is not raw lab formulas or the game-lore meaning of labs.',
      mechanics: ['Lab Tracker Overview'],
      tags: ['trackerai', 'labs', 'tracker', 'site page', 'overview'],
      paragraphs: [...LAB_TRACKER_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_labs_overview_tab_01',
      source: 'Lab Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'All Labs Tab',
      title: 'Lab Tracker All Labs Tab',
      disambiguation: 'This chunk is about the Lab Tracker All Labs Tab mechanic itself, not its interactions. It is not the active-lab timer system or the calculator math view.',
      mechanics: ['Lab Tracker All Labs Tab'],
      tags: ['trackerai', 'labs', 'all labs', 'favorites', 'search', 'levels'],
      paragraphs: [...LAB_TRACKER_OVERVIEW_TAB_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_labs_active_01',
      source: 'Lab Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Active Slots',
      title: 'Lab Tracker Active Slots',
      disambiguation: 'This chunk is about the Lab Tracker Active Slots mechanic itself, not its interactions. It is not the full calculator output table or a generic timer app.',
      mechanics: ['Lab Tracker Active Slots'],
      tags: ['trackerai', 'labs', 'active', 'slots', 'speedup', 'timers'],
      paragraphs: [...LAB_TRACKER_ACTIVE_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_labs_progress_01',
      source: 'Lab Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Progress Planning Table',
      title: 'Lab Tracker Progress Planning Table',
      disambiguation: 'This chunk is about the Lab Tracker Progress Planning Table mechanic itself, not its interactions. It is not a one-line gem formula note or a static completed-labs list.',
      mechanics: ['Lab Tracker Progress Planning Table'],
      tags: ['trackerai', 'labs', 'progress', 'planning', 'gems', 'targets'],
      paragraphs: [...LAB_TRACKER_PROGRESS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_labs_upload_01',
      source: 'Lab Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Upload and OCR Review',
      title: 'Lab Tracker Upload and OCR Review',
      disambiguation: 'This chunk is about the Lab Tracker Upload and OCR Review mechanic itself, not its interactions. It is not a claim that screenshot OCR is fully automatic and error-free.',
      mechanics: ['Lab Tracker Upload and OCR Review'],
      tags: ['trackerai', 'labs', 'upload', 'ocr', 'screenshots', 'review'],
      paragraphs: [...LAB_TRACKER_UPLOAD_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_labs_sync_01',
      source: 'Lab Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Local Save and Sync',
      title: 'Lab Tracker Local Save and Sync',
      disambiguation: 'This chunk is about the Lab Tracker Local Save and Sync mechanic itself, not its interactions. It is not a low-level sync protocol dump.',
      mechanics: ['Lab Tracker Local Save and Sync'],
      tags: ['trackerai', 'labs', 'sync', 'local save', 'cloud', 'autosave'],
      paragraphs: [...LAB_TRACKER_SYNC_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_labs_calculator_overview_01',
      source: 'Lab Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Lab Calculator',
      title: 'Lab Calculator Overview',
      disambiguation: 'This chunk is about the Lab Calculator Overview mechanic itself, not its interactions. It is not the full lab tracker page or a hidden simulator backend.',
      mechanics: ['Lab Calculator Overview'],
      tags: ['trackerai', 'labs', 'calculator', 'site page', 'overview'],
      paragraphs: [...LAB_CALCULATOR_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_labs_calculator_inputs_01',
      source: 'Lab Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Calculator Inputs',
      title: 'Lab Calculator Inputs and Controls',
      disambiguation: 'This chunk is about the Lab Calculator Inputs and Controls mechanic itself, not its interactions. It is not the output tables or a promise that every input is always shared globally.',
      mechanics: ['Lab Calculator Inputs and Controls'],
      tags: ['trackerai', 'labs', 'calculator', 'inputs', 'speedup', 'discounts'],
      paragraphs: [...LAB_CALCULATOR_INPUT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_labs_calculator_outputs_01',
      source: 'Lab Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Calculator Outputs',
      title: 'Lab Calculator Outputs',
      disambiguation: 'This chunk is about the Lab Calculator Outputs mechanic itself, not its interactions. It is not an always-populated report or a screenshot verification system.',
      mechanics: ['Lab Calculator Outputs'],
      tags: ['trackerai', 'labs', 'calculator', 'outputs', 'per level', 'cumulative'],
      paragraphs: [...LAB_CALCULATOR_OUTPUT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_labs_calculator_views_01',
      source: 'Lab Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Calculator Views and Filters',
      title: 'Lab Calculator Views and Filters',
      disambiguation: 'This chunk is about the Lab Calculator Views and Filters mechanic itself, not its interactions. It is not the tracker progress table or a hidden export system.',
      mechanics: ['Lab Calculator Views and Filters'],
      tags: ['trackerai', 'labs', 'calculator', 'filters', 'cumulative', 'views'],
      paragraphs: [...LAB_CALCULATOR_VIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_labs_link_01',
      source: 'Lab Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Tracker and Calculator Link',
      title: 'Lab Tracker and Calculator Link',
      disambiguation: 'This chunk is about the Lab Tracker and Calculator Link mechanic itself, not its interactions. It is not a claim that both pages are identical views.',
      mechanics: ['Lab Tracker and Calculator Link'],
      tags: ['trackerai', 'labs', 'tracker', 'calculator', 'shared state'],
      paragraphs: [...LAB_TRACKER_CALCULATOR_LINK_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_labs_ai_01',
      source: 'Lab Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on Labs',
      title: 'Lab Tracker and Calculator AI Help Coverage',
      disambiguation: 'This chunk is about the Lab Tracker and Calculator AI Help Coverage mechanic itself, not its interactions. It is not a promise of unrestricted bulk edits or sync automation.',
      mechanics: ['Lab Tracker and Calculator AI Help Coverage'],
      tags: ['trackerai', 'labs', 'ai help', 'tracker', 'calculator', 'guidance'],
      paragraphs: [...LAB_TRACKER_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_labs_faq_use_01',
      source: 'Lab Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I use the lab tracker page?',
      title: 'How do I use the lab tracker page?',
      disambiguation: 'This chunk is about the interaction between the main lab tracker tabs, not the deep game meaning of lab values.',
      mechanics: ['Lab Tracker Overview', 'Lab Tracker All Labs Tab', 'Lab Tracker Active Slots', 'Lab Tracker Progress Planning Table', 'Lab Tracker Upload and OCR Review'],
      tags: ['trackerai', 'labs', 'faq', 'tracker', 'tabs', 'workflow'],
      interaction_type: 'cross_system',
      interaction_summary: 'Lab Tracker Overview, Lab Tracker All Labs Tab, Lab Tracker Active Slots, Lab Tracker Progress Planning Table, and Lab Tracker Upload and OCR Review explain how the tracker splits broad lab work into different tabs instead of forcing one crowded view.',
      paragraphs: [
        'Lab Tracker Overview explains the page as a whole, Lab Tracker All Labs Tab covers browsing and cleanup, Lab Tracker Active Slots covers currently running labs, Lab Tracker Progress Planning Table covers target planning, and Lab Tracker Upload and OCR Review covers screenshot-based import.',
        'That matters because users often ask where a lab action belongs before they ask about the action itself.',
        'The clearest answer is to name those mechanics directly: use All Labs for broad maintenance, Active Slots for current timers, Progress Planning Table for goal planning, and Upload and OCR Review when the user is starting from screenshots.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_labs_faq_active_01',
      source: 'Lab Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do active labs work on the tracker?',
      title: 'How do active labs work on the tracker?',
      disambiguation: 'This chunk is about the interaction between active slots, progress timing, and calculator handoff, not a hidden timer engine.',
      mechanics: ['Lab Tracker Active Slots', 'Lab Tracker and Calculator Link'],
      tags: ['trackerai', 'labs', 'faq', 'active labs', 'slots', 'timers'],
      interaction_type: 'cross_system',
      interaction_summary: 'Lab Tracker Active Slots and Lab Tracker and Calculator Link explain how currently running labs are tracked and how users can pivot from a live slot into planning math.',
      paragraphs: [
        'Lab Tracker Active Slots explains the up-to-five running-lab workflow, while Lab Tracker and Calculator Link explains why those slots can jump directly into calculator context instead of starting over from scratch.',
        'That relationship is what makes the active tab practical instead of isolated.',
        'The most useful answer is to name those mechanics directly: use Lab Tracker Active Slots for how running labs are timed and managed, and use Lab Tracker and Calculator Link for how planning continues from there.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_labs_faq_gems_01',
      source: 'Lab Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why do lab gem totals change as I complete labs?',
      title: 'Why do lab gem totals change as I complete labs?',
      disambiguation: 'This chunk is about the interaction between lab completion state, progress planning, and calculator modifiers, not a random display bug.',
      mechanics: ['Lab Tracker Progress Planning Table', 'Lab Calculator Inputs and Controls', 'Lab Tracker and Calculator Link'],
      tags: ['trackerai', 'labs', 'faq', 'gems', 'discount', 'calculator'],
      interaction_type: 'conditional',
      interaction_summary: 'Lab Tracker Progress Planning Table, Lab Calculator Inputs and Controls, and Lab Tracker and Calculator Link explain why gem-facing lab numbers depend on current completion state and calculator settings.',
      paragraphs: [
        'Lab Tracker Progress Planning Table explains that the tracker applies gem-oriented progress fields using current completion context, Lab Calculator Inputs and Controls explains the gem discount multiplier side of the calculator, and Lab Tracker and Calculator Link explains why those two views stay related.',
        'That means gem totals are not meant to be read as context-free constants once the tracker knows more about completed labs and calculator settings.',
        'The clearest answer is to name those mechanics directly: start with Lab Tracker Progress Planning Table for tracker-side gem numbers, then use Lab Calculator Inputs and Controls when the question is really about the calculator modifiers behind those totals.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_labs_faq_calculator_01',
      source: 'Lab Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What is the difference between the lab tracker and the lab calculator?',
      title: 'What is the difference between the lab tracker and the lab calculator?',
      disambiguation: 'This chunk is about the interaction between the lab tracker and the lab calculator, not a claim that one replaces the other.',
      mechanics: ['Lab Tracker Overview', 'Lab Calculator Overview', 'Lab Tracker and Calculator Link'],
      tags: ['trackerai', 'labs', 'faq', 'tracker', 'calculator', 'difference'],
      interaction_type: 'cross_system',
      interaction_summary: 'Lab Tracker Overview, Lab Calculator Overview, and Lab Tracker and Calculator Link explain why one lab surface manages broader progress while the other focuses on one-lab planning math.',
      paragraphs: [
        'Lab Tracker Overview explains the broader management page, Lab Calculator Overview explains the focused planning page, and Lab Tracker and Calculator Link explains why they share state instead of acting like unrelated tools.',
        'That relationship is the easiest way to answer users who ask which page they should use first.',
        'The practical answer is to name those mechanics directly: use Lab Tracker Overview for broad progress management, use Lab Calculator Overview for per-lab planning, and use Lab Tracker and Calculator Link for how the two surfaces stay aligned.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_labs_faq_save_progress_01',
      source: 'Lab Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What does Save to Progress do on the lab calculator?',
      title: 'What does Save to Progress do on the lab calculator?',
      disambiguation: 'This chunk is about the interaction between the embedded lab calculator and tracker progress, not a promise that the standalone calculator always behaves the same way.',
      mechanics: ['Lab Calculator Inputs and Controls', 'Lab Calculator Views and Filters', 'Lab Tracker and Calculator Link', 'Lab Tracker Progress Planning Table'],
      tags: ['trackerai', 'labs', 'faq', 'save to progress', 'calculator', 'tracker'],
      interaction_type: 'cross_system',
      interaction_summary: 'Lab Calculator Inputs and Controls, Lab Calculator Views and Filters, Lab Tracker and Calculator Link, and Lab Tracker Progress Planning Table explain how a calculator plan becomes tracked lab progress on the tracker page.',
      paragraphs: [
        'Lab Calculator Inputs and Controls explains the editable planning state, Lab Calculator Views and Filters explains the calculator reading context around that plan, Lab Tracker and Calculator Link explains the shared tracker-calculator handoff, and Lab Tracker Progress Planning Table explains where the saved result becomes meaningful as tracker progress.',
        'That matters because users often want to know whether the calculator is only a temporary estimate or part of the tracker workflow.',
        'The clearest answer is to name those mechanics directly: Save to Progress is the bridge from calculator planning into Lab Tracker Progress Planning Table, and Lab Tracker and Calculator Link explains why that bridge exists at all.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_labs_faq_upload_01',
      source: 'Lab Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Can I import lab progress from screenshots?',
      title: 'Can I import lab progress from screenshots?',
      disambiguation: 'This chunk is about the interaction between lab screenshot import and lab progress management, not blind OCR automation.',
      mechanics: ['Lab Tracker Upload and OCR Review', 'Lab Tracker Progress Planning Table'],
      tags: ['trackerai', 'labs', 'faq', 'upload', 'ocr', 'screenshots'],
      interaction_type: 'cross_system',
      interaction_summary: 'Lab Tracker Upload and OCR Review and Lab Tracker Progress Planning Table explain how screenshot-detected lab rows can become usable planning data after review.',
      paragraphs: [
        'Lab Tracker Upload and OCR Review explains the screenshot import and editable review step, while Lab Tracker Progress Planning Table explains where that cleaned-up progress becomes meaningful as planned lab state.',
        'That pairing matters because users usually want to know not just whether screenshots can be read, but whether the result becomes useful on the tracker afterward.',
        'The clearest answer is to name those mechanics directly: use Lab Tracker Upload and OCR Review for the import path, then use Lab Tracker Progress Planning Table for the planning view that benefits from that imported progress.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_labs_faq_sync_01',
      source: 'Lab Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Does the lab tracker save and sync with the calculator?',
      title: 'Does the lab tracker save and sync with the calculator?',
      disambiguation: 'This chunk is about the interaction between lab sync behavior and shared tracker-calculator state, not a low-level store contract.',
      mechanics: ['Lab Tracker Local Save and Sync', 'Lab Tracker and Calculator Link', 'Lab Calculator Inputs and Controls'],
      tags: ['trackerai', 'labs', 'faq', 'sync', 'shared state', 'calculator'],
      interaction_type: 'conditional',
      interaction_summary: 'Lab Tracker Local Save and Sync, Lab Tracker and Calculator Link, and Lab Calculator Inputs and Controls explain how lab state can persist and why calculator defaults often follow the tracker context.',
      paragraphs: [
        'Lab Tracker Local Save and Sync explains the persistence layer, Lab Tracker and Calculator Link explains the shared-state idea, and Lab Calculator Inputs and Controls explains the practical settings users see being reused.',
        'That is why the calculator often feels like it already knows the lab context the tracker was using.',
        'The cleanest answer is to name those mechanics directly: use Lab Tracker Local Save and Sync for the save path, then use Lab Tracker and Calculator Link and Lab Calculator Inputs and Controls for the tracker-to-calculator carryover.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_labs_faq_ai_01',
      source: 'Lab Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do with labs?',
      title: 'What can TrackerAI help me do with labs?',
      disambiguation: 'This chunk is about the interaction between lab page knowledge and TrackerAI help boundaries, not unrestricted bulk editing or sync control.',
      mechanics: ['Lab Tracker Overview', 'Lab Calculator Overview', 'Lab Tracker and Calculator Link', 'Lab Tracker and Calculator AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'labs', 'faq', 'ai help', 'tracker', 'calculator'],
      interaction_type: 'conditional',
      interaction_summary: 'Lab Tracker Overview, Lab Calculator Overview, Lab Tracker and Calculator Link, Lab Tracker and Calculator AI Help Coverage, and TrackerAI Safety Guardrails define the kinds of lab help the assistant can give without pretending it should silently change tracked progress.',
      paragraphs: [
        'Lab Tracker Overview and Lab Calculator Overview provide the two page contexts, Lab Tracker and Calculator Link explains why users keep moving between them, and Lab Tracker and Calculator AI Help Coverage explains why this is a strong explanation-and-guidance area for the assistant.',
        'This is where TrackerAI is most useful for normal users: deciding which lab surface to use, understanding gem and time totals, and clarifying why a tracker value and a calculator value are related.',
        'TrackerAI Safety Guardrails is the boundary that keeps the help honest, because explanation and interpretation are very different from pretending the assistant should perform every saved lab action automatically.',
      ],
    }),
  ]
}
