import {
  DAMAGE_REDUCTION_CALCULATOR_AI_FACTS,
  DAMAGE_REDUCTION_CALCULATOR_BREAKDOWN_FACTS,
  DAMAGE_REDUCTION_CALCULATOR_CT_FACTS,
  DAMAGE_REDUCTION_CALCULATOR_INPUT_FACTS,
  DAMAGE_REDUCTION_CALCULATOR_OVERVIEW_FACTS,
  DAMAGE_REDUCTION_CALCULATOR_PERKS_FACTS,
  DAMAGE_REDUCTION_CALCULATOR_PERSISTENCE_FACTS,
  DAMAGE_REDUCTION_CALCULATOR_RESULTS_FACTS,
} from './trackerAiDamageReductionSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiDamageReductionCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_damage_reduction_overview_01',
      source: 'Damage Reduction Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Damage Reduction Calculator Workspace',
      title: 'Damage Reduction Calculator Workspace Overview',
      disambiguation: 'This chunk describes the Damage Reduction Calculator Workspace Overview mechanic itself, not its interactions. It is not a generic combat-reduction article or a full game-mechanics encyclopedia.',
      mechanics: ['Damage Reduction Calculator Workspace Overview'],
      tags: ['trackerai', 'damage reduction', 'calculator', 'site page', 'overview'],
      paragraphs: [...DAMAGE_REDUCTION_CALCULATOR_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_damage_reduction_inputs_01',
      source: 'Damage Reduction Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Reduction Inputs',
      title: 'Damage Reduction Calculator Reduction Inputs',
      disambiguation: 'This chunk describes the Damage Reduction Calculator Reduction Inputs mechanic itself, not its interactions. It is not the per-enemy breakdown table or the perks panel by itself.',
      mechanics: ['Damage Reduction Calculator Reduction Inputs'],
      tags: ['trackerai', 'damage reduction', 'calculator', 'inputs', 'defense', 'chrono field', 'flamebot'],
      paragraphs: [...DAMAGE_REDUCTION_CALCULATOR_INPUT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_damage_reduction_ct_01',
      source: 'Damage Reduction Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Chain Thunder Branch',
      title: 'Damage Reduction Calculator Chain Thunder Branch',
      disambiguation: 'This chunk describes the Damage Reduction Calculator Chain Thunder Branch mechanic itself, not its interactions. It is not a claim that all damage reduction on the page depends on Chain Thunder.',
      mechanics: ['Damage Reduction Calculator Chain Thunder Branch'],
      tags: ['trackerai', 'damage reduction', 'calculator', 'chain thunder', 'cl+', 'hp reduction'],
      paragraphs: [...DAMAGE_REDUCTION_CALCULATOR_CT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_damage_reduction_perks_01',
      source: 'Damage Reduction Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Active Perks Panel',
      title: 'Damage Reduction Calculator Active Perks Panel',
      disambiguation: 'This chunk describes the Damage Reduction Calculator Active Perks Panel mechanic itself, not its interactions. It is not a permanent profile editor for perks outside the page model.',
      mechanics: ['Damage Reduction Calculator Active Perks Panel'],
      tags: ['trackerai', 'damage reduction', 'calculator', 'perks', 'enemy hp', 'enemy damage'],
      paragraphs: [...DAMAGE_REDUCTION_CALCULATOR_PERKS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_damage_reduction_results_01',
      source: 'Damage Reduction Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Summary Cards and Enemy Results',
      title: 'Damage Reduction Calculator Summary Cards and Enemy Results',
      disambiguation: 'This chunk describes the Damage Reduction Calculator Summary Cards and Enemy Results mechanic itself, not its interactions. It is not the customize-columns workflow or saved-state contract by itself.',
      mechanics: ['Damage Reduction Calculator Summary Cards and Enemy Results'],
      tags: ['trackerai', 'damage reduction', 'calculator', 'results', 'enemy types', 'summary'],
      paragraphs: [...DAMAGE_REDUCTION_CALCULATOR_RESULTS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_damage_reduction_breakdown_01',
      source: 'Damage Reduction Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Enemy Breakdown Table',
      title: 'Damage Reduction Calculator Enemy Breakdown Table',
      disambiguation: 'This chunk describes the Damage Reduction Calculator Enemy Breakdown Table mechanic itself, not its interactions. It is not a flat one-row results card.',
      mechanics: ['Damage Reduction Calculator Enemy Breakdown Table'],
      tags: ['trackerai', 'damage reduction', 'calculator', 'breakdown', 'columns', 'enemy table'],
      paragraphs: [...DAMAGE_REDUCTION_CALCULATOR_BREAKDOWN_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_damage_reduction_persistence_01',
      source: 'Damage Reduction Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Saved Calculator State',
      title: 'Damage Reduction Calculator Saved Calculator State',
      disambiguation: 'This chunk describes the Damage Reduction Calculator Saved Calculator State mechanic itself, not its interactions. It is not a cloud-sync contract or a site-wide settings record.',
      mechanics: ['Damage Reduction Calculator Saved Calculator State'],
      tags: ['trackerai', 'damage reduction', 'calculator', 'saved state', 'dexie', 'local'],
      paragraphs: [...DAMAGE_REDUCTION_CALCULATOR_PERSISTENCE_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_damage_reduction_ai_01',
      source: 'Damage Reduction Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on Damage Reduction Calculator',
      title: 'Damage Reduction Calculator AI Help Coverage',
      disambiguation: 'This chunk describes the Damage Reduction Calculator AI Help Coverage mechanic itself, not its interactions. It is not unrestricted silent editing of the saved calculator state.',
      mechanics: ['Damage Reduction Calculator AI Help Coverage'],
      tags: ['trackerai', 'damage reduction', 'calculator', 'ai help'],
      paragraphs: [...DAMAGE_REDUCTION_CALCULATOR_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_damage_reduction_faq_use_01',
      source: 'Damage Reduction Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I use the Damage Reduction calculator?',
      title: 'How do I use the Damage Reduction calculator?',
      disambiguation: 'This chunk is about the interaction between the main damage-reduction calculator surfaces, not a general strategy guide outside the page.',
      mechanics: ['Damage Reduction Calculator Workspace Overview', 'Damage Reduction Calculator Reduction Inputs', 'Damage Reduction Calculator Summary Cards and Enemy Results', 'Damage Reduction Calculator Enemy Breakdown Table'],
      tags: ['trackerai', 'damage reduction', 'faq', 'calculator', 'workflow'],
      interaction_type: 'cross_system',
      interaction_summary: 'Damage Reduction Calculator Workspace Overview, Damage Reduction Calculator Reduction Inputs, Damage Reduction Calculator Summary Cards and Enemy Results, and Damage Reduction Calculator Enemy Breakdown Table explain how the page moves from modeled reduction setup into top-line and per-enemy outputs.',
      paragraphs: [
        'Damage Reduction Calculator Workspace Overview explains the page as a whole, Damage Reduction Calculator Reduction Inputs explains how the reduction stack is modeled, Damage Reduction Calculator Summary Cards and Enemy Results explains the top-line outputs, and Damage Reduction Calculator Enemy Breakdown Table explains the deeper drill-down table.',
        'That matters because users often know they want a final reduction number without yet knowing whether the better evidence is the summary cards or the enemy-type breakdown.',
        'The clearest answer is to name those mechanics directly: set up the wave and enabled reductions first, read the summary cards for the top-line result, and expand enemy rows when you need to audit how the reduction order played out for a specific enemy type.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_damage_reduction_faq_ct_01',
      source: 'Damage Reduction Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why do some HP and reduction columns only appear when Chain Thunder is enabled?',
      title: 'Why do some HP and reduction columns only appear when Chain Thunder is enabled?',
      disambiguation: 'This chunk is about the interaction between the CT branch and the visible results surfaces, not a claim that the page has broken columns when CT is off.',
      mechanics: ['Damage Reduction Calculator Chain Thunder Branch', 'Damage Reduction Calculator Summary Cards and Enemy Results', 'Damage Reduction Calculator Enemy Breakdown Table'],
      tags: ['trackerai', 'damage reduction', 'faq', 'chain thunder', 'columns', 'hp'],
      interaction_type: 'conditional',
      interaction_summary: 'Damage Reduction Calculator Chain Thunder Branch, Damage Reduction Calculator Summary Cards and Enemy Results, and Damage Reduction Calculator Enemy Breakdown Table explain why HP-side outputs and some reduction columns are conditional on CT being active.',
      paragraphs: [
        'Damage Reduction Calculator Chain Thunder Branch explains that CT adds its own HP-side modeling path, and Damage Reduction Calculator Summary Cards and Enemy Results explains the conditional HP summary row that appears with it.',
        'Damage Reduction Calculator Enemy Breakdown Table is the other half of the explanation because the displayed column set also changes when CT is off or on.',
        'The clearest answer is to name those mechanics directly: CT unlocks the HP-after-CL+ modeling branch, so the page only surfaces HP-specific rows and CT-dependent reduction columns when that branch is active.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_damage_reduction_faq_columns_01',
      source: 'Damage Reduction Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What does Customize Columns do on the Damage Reduction calculator?',
      title: 'What does Customize Columns do on the Damage Reduction calculator?',
      disambiguation: 'This chunk is about the interaction between column toggling, drag reordering, and the enemy breakdown surface, not a claim that the page edits the underlying formulas.',
      mechanics: ['Damage Reduction Calculator Enemy Breakdown Table', 'Damage Reduction Calculator Summary Cards and Enemy Results'],
      tags: ['trackerai', 'damage reduction', 'faq', 'columns', 'reorder', 'table'],
      interaction_type: 'cross_system',
      interaction_summary: 'Damage Reduction Calculator Enemy Breakdown Table and Damage Reduction Calculator Summary Cards and Enemy Results explain how the Customize Columns menu changes the visible evidence in the enemy table while leaving the calculator\'s top-line modeled results unchanged.',
      paragraphs: [
        'Damage Reduction Calculator Enemy Breakdown Table explains that the menu can toggle columns, reset them to defaults, and optionally switch the table into drag-reorder mode, while Damage Reduction Calculator Summary Cards and Enemy Results explains the stable top-line outputs that remain available above the table.',
        'That means the workflow is about curating which evidence is visible, not recalculating the reduction stack itself.',
        'The clearest answer is to name that mechanic directly: Customize Columns changes which enemy-table columns are shown and in what order they appear, while the calculator model underneath stays the same.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_damage_reduction_faq_reset_01',
      source: 'Damage Reduction Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What does Reset do on the Damage Reduction calculator?',
      title: 'What does Reset do on the Damage Reduction calculator?',
      disambiguation: 'This chunk is about the interaction between the saved calculator workspace and the page reset action, not a destructive reset of tracker progress elsewhere on the site.',
      mechanics: ['Damage Reduction Calculator Workspace Overview', 'Damage Reduction Calculator Saved Calculator State'],
      tags: ['trackerai', 'damage reduction', 'faq', 'reset', 'saved state'],
      interaction_type: 'conditional',
      interaction_summary: 'Damage Reduction Calculator Workspace Overview and Damage Reduction Calculator Saved Calculator State explain why Reset clears the current modeled reduction workspace instead of unrelated site progress.',
      paragraphs: [
        'Damage Reduction Calculator Workspace Overview explains that the route is a saved calculator workspace, and Damage Reduction Calculator Saved Calculator State explains which page-specific fields persist there.',
        'That is why Reset should be understood as clearing this route\'s modeled state rather than deleting progress in trackers or other calculators.',
        'The clearest answer is to name those mechanics directly: Reset clears the current damage-reduction calculator setup toward its baseline values and replaces the saved local workspace for this page.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_damage_reduction_faq_saved_01',
      source: 'Damage Reduction Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What does the Damage Reduction calculator remember between visits?',
      title: 'What does the Damage Reduction calculator remember between visits?',
      disambiguation: 'This chunk is about the interaction between the persisted calculator store, panel state, and table configuration, not a cloud-sync guarantee.',
      mechanics: ['Damage Reduction Calculator Saved Calculator State', 'Damage Reduction Calculator Enemy Breakdown Table', 'Damage Reduction Calculator Active Perks Panel'],
      tags: ['trackerai', 'damage reduction', 'faq', 'saved state', 'columns', 'perks'],
      interaction_type: 'cross_system',
      interaction_summary: 'Damage Reduction Calculator Saved Calculator State, Damage Reduction Calculator Enemy Breakdown Table, and Damage Reduction Calculator Active Perks Panel explain why both the modeling inputs and the table workspace can return with the page.',
      paragraphs: [
        'Damage Reduction Calculator Saved Calculator State explains the persisted inputs, toggles, CT settings, panel-open state, and column configuration, while Damage Reduction Calculator Enemy Breakdown Table explains the saved table customizations the user sees on return.',
        'Damage Reduction Calculator Active Perks Panel matters because perk assumptions are also part of the same saved workspace rather than a temporary overlay.',
        'The clearest answer is to name those mechanics directly: the calculator remembers its wave inputs, enabled reductions, perk toggles, CT settings, table columns and order, reorder mode, and the open state of its expansion panels.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_damage_reduction_faq_ai_01',
      source: 'Damage Reduction Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do with the Damage Reduction calculator?',
      title: 'What can TrackerAI help me do with the Damage Reduction calculator?',
      disambiguation: 'This chunk is about the interaction between damage-reduction page knowledge and TrackerAI help boundaries, not unrestricted silent mutation of the stored calculator workspace.',
      mechanics: ['Damage Reduction Calculator Workspace Overview', 'Damage Reduction Calculator AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'damage reduction', 'faq', 'ai help', 'calculator'],
      interaction_type: 'conditional',
      interaction_summary: 'Damage Reduction Calculator Workspace Overview, Damage Reduction Calculator AI Help Coverage, and TrackerAI Safety Guardrails define the kinds of page-specific explanation and workflow guidance the assistant can provide without pretending it should silently rewrite stored values.',
      paragraphs: [
        'Damage Reduction Calculator Workspace Overview provides the page context, and Damage Reduction Calculator AI Help Coverage explains why this calculator is a strong fit for interpretation help when multiple reductions interact.',
        'This is where TrackerAI is most useful for normal users: clarifying which reductions are active, explaining why CT changes the visible surfaces, and helping interpret enemy-specific breakdown rows.',
        'TrackerAI Safety Guardrails is the boundary that keeps that help honest, because guidance and explanation are different from silently resetting or rewriting a user\'s saved calculator workspace without clear intent.',
      ],
    }),
  ]
}
