import {
  TRACKER_AI_SITE_KNOWLEDGE_COMMUNICATION_FACTS,
  TRACKER_AI_SITE_KNOWLEDGE_EXAMPLE_REQUEST_FACTS,
  TRACKER_AI_SITE_KNOWLEDGE_EXECUTION_FACTS,
  TRACKER_AI_SITE_KNOWLEDGE_FEATURE_COVERAGE_FACTS,
  TRACKER_AI_SITE_KNOWLEDGE_GUARDRAILS_FACTS,
  TRACKER_AI_SITE_KNOWLEDGE_KB_FACTS,
  TRACKER_AI_SITE_KNOWLEDGE_OVERVIEW_FACTS,
  TRACKER_AI_SITE_KNOWLEDGE_USER_CONTEXT_FACTS,
} from './trackerAiSiteKnowledgeSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiAccessCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_global_access_01',
      source: 'TrackerAI Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Global Access',
      title: 'TrackerAI Global Access Contract',
      disambiguation: 'This chunk is about the TrackerAI Global Access Contract mechanic itself, not its interactions. It is not about admin-only access, unrestricted backend access, or destructive actions without confirmation.',
      mechanics: ['TrackerAI Global Access Contract'],
      tags: ['trackerai', 'global access', 'capabilities', 'routes', 'calculators', 'trackers'],
      paragraphs: [
        ...TRACKER_AI_SITE_KNOWLEDGE_OVERVIEW_FACTS,
        ...TRACKER_AI_SITE_KNOWLEDGE_FEATURE_COVERAGE_FACTS,
      ],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_safety_rules_01',
      source: 'TrackerAI Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Safety Guardrails',
      title: 'TrackerAI Safety and Confirmation Rules',
      disambiguation: 'This chunk is about the TrackerAI Safety Guardrails mechanic itself, not its interactions. It is not about gameplay safety, anti-cheat systems, or admin moderation tools.',
      mechanics: ['TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'safety', 'confirmation', 'destructive actions', 'guardrails'],
      paragraphs: [...TRACKER_AI_SITE_KNOWLEDGE_GUARDRAILS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_execution_workflows_01',
      source: 'TrackerAI Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Execution Workflows',
      title: 'TrackerAI Execution and Workflow Coverage',
      disambiguation: 'This chunk is about the TrackerAI Execution Workflows mechanic itself, not its interactions. It is not a gameplay guide, a backend API contract, or a raw prompt dump.',
      mechanics: ['TrackerAI Execution Workflows'],
      tags: ['trackerai', 'execution', 'workflow', 'multi-step', 'follow-up'],
      paragraphs: [...TRACKER_AI_SITE_KNOWLEDGE_EXECUTION_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_kb_role_01',
      source: 'TrackerAI Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Knowledge Base Role',
      title: 'TrackerAI Knowledge Base Role',
      disambiguation: 'This chunk is about the TrackerAI Knowledge Base Role mechanic itself, not its interactions. It is not about one specific game mechanic, tool output, or hidden internal prompt.',
      mechanics: ['TrackerAI Knowledge Base Role'],
      tags: ['trackerai', 'knowledge base', 'tool scope', 'workflows', 'constraints'],
      paragraphs: [...TRACKER_AI_SITE_KNOWLEDGE_KB_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_user_context_01',
      source: 'TrackerAI Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'User Context and Memory',
      title: 'TrackerAI User Context and Memory Rules',
      disambiguation: 'This chunk is about the TrackerAI User Context and Memory Rules mechanic itself, not its interactions. It is not about browser storage internals, hidden memory systems, or private user profiling.',
      mechanics: ['TrackerAI User Context and Memory Rules'],
      tags: ['trackerai', 'context', 'memory', 'follow-up', 'privacy'],
      paragraphs: [...TRACKER_AI_SITE_KNOWLEDGE_USER_CONTEXT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_communication_01',
      source: 'TrackerAI Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Communication Style',
      title: 'TrackerAI Communication and User-Facing Boundaries',
      disambiguation: 'This chunk is about the TrackerAI Communication and User-Facing Boundaries mechanic itself, not its interactions. It is not about internal implementation details or model training behavior.',
      mechanics: ['TrackerAI Communication and User-Facing Boundaries'],
      tags: ['trackerai', 'communication', 'plain language', 'accessibility', 'boundaries'],
      paragraphs: [...TRACKER_AI_SITE_KNOWLEDGE_COMMUNICATION_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_examples_01',
      source: 'TrackerAI Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Supported Request Patterns',
      title: 'TrackerAI Supported Site Request Patterns',
      disambiguation: 'This chunk is about the TrackerAI Supported Site Request Patterns mechanic itself, not its interactions. It is not about guaranteed outcomes for any one page or a fixed command grammar.',
      mechanics: ['TrackerAI Supported Site Request Patterns'],
      tags: ['trackerai', 'examples', 'tools', 'trackers', 'navigation', 'support'],
      paragraphs: [...TRACKER_AI_SITE_KNOWLEDGE_EXAMPLE_REQUEST_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_access_guardrails_01',
      source: 'TrackerAI Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'TrackerAI Global Access Contract with TrackerAI Safety Guardrails',
      title: 'TrackerAI Global Access Contract with TrackerAI Safety Guardrails',
      disambiguation: 'This chunk is about the interaction between TrackerAI global access and TrackerAI safety guardrails, not about unrelated admin systems or game safety mechanics.',
      mechanics: ['TrackerAI Global Access Contract', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'global access', 'guardrails', 'confirmation', 'permissions'],
      interaction_type: 'conditional',
      interaction_summary: 'TrackerAI Global Access Contract only applies inside TrackerAI Safety Guardrails, so broad site coverage does not permit admin-only actions, backend bypasses, or destructive changes without confirmation.',
      paragraphs: [
        'The site-wide access contract is intentionally broad, but the guardrails define how that breadth is allowed to operate. TrackerAI should act across user-visible pages and tools without turning into an unrestricted automation channel.',
        'That means the assistant can move quickly on normal reads, writes, and navigation while still pausing for confirmation on destructive steps and refusing anything outside ordinary user permissions.',
        'In practice, the capability story and the safety story are not separate systems. The useful version of full access is permission-bound, confirmation-aware, and routed through normal frontend behavior.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_execution_context_01',
      source: 'TrackerAI Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'TrackerAI Execution Workflows with TrackerAI User Context and Memory Rules',
      title: 'TrackerAI Execution Workflows with TrackerAI User Context and Memory Rules',
      disambiguation: 'This chunk is about the interaction between multi-step execution and remembered user context, not a general memory-system implementation note or a single workflow script.',
      mechanics: ['TrackerAI Execution Workflows', 'TrackerAI User Context and Memory Rules'],
      tags: ['trackerai', 'workflow', 'context', 'follow-up', 'multi-step'],
      interaction_type: 'cross_system',
      interaction_summary: 'TrackerAI Execution Workflows depend on TrackerAI User Context and Memory Rules so follow-up prompts can reuse resolved entities, current targets, and user goals without forcing the user to restate the full task every turn.',
      paragraphs: [
        'Multi-step site assistance becomes much more reliable when the assistant remembers what page is in view, what tracker item was just edited, and what goal the user is working toward.',
        'That remembered context should streamline follow-ups, but it should not replace the live site state or user confirmation when a new risky action appears.',
        'The intended model is assistive continuity: TrackerAI should carry forward useful context, then combine it with current UI state and the current request before acting.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_kb_execution_01',
      source: 'TrackerAI Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'TrackerAI Knowledge Base Role with TrackerAI Execution Workflows and TrackerAI Global Access Contract',
      title: 'TrackerAI Knowledge Base Role with TrackerAI Execution Workflows and TrackerAI Global Access Contract',
      disambiguation: 'This chunk is about the interaction between curated site knowledge, execution workflows, and global access, not about hidden prompt injection defenses or backend data models.',
      mechanics: ['TrackerAI Knowledge Base Role', 'TrackerAI Execution Workflows', 'TrackerAI Global Access Contract'],
      tags: ['trackerai', 'knowledge base', 'execution', 'global access', 'tool guidance'],
      interaction_type: 'conditional',
      interaction_summary: 'TrackerAI should consult curated site knowledge first for fast guidance, but its execution workflows still rely on live site state and the global access contract rather than treating the KB as the only authority.',
      paragraphs: [
        'The curated KB is the fast path for answering what a tool does, how a page works, or which fields and workflows are relevant to a request.',
        'But the assistant should not freeze when the KB is incomplete. If the live page state and allowed UI actions provide enough clarity, TrackerAI should continue helping inside normal user scope.',
        'That balance keeps the system practical: knowledge improves guidance, global access enables action, and live state prevents the KB from becoming a stale gatekeeper.',
      ],
    }),
  ]
}
