import {
  GIVEAWAY_PAGE_AI_FACTS,
  GIVEAWAY_PAGE_CURRENT_FACTS,
  GIVEAWAY_PAGE_LEADERBOARD_FACTS,
  GIVEAWAY_PAGE_OVERVIEW_FACTS,
  GIVEAWAY_PAGE_PLAYER_ID_FACTS,
  GIVEAWAY_PAGE_PROCESSING_FACTS,
  GIVEAWAY_PAGE_PROGRESS_FACTS,
  GIVEAWAY_PAGE_REFERRAL_FACTS,
  GIVEAWAY_PAGE_RULES_FACTS,
} from './trackerAiGiveawaySource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiGiveawayCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_giveaway_overview_01',
      source: 'Giveaway Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Giveaway Page Overview',
      title: 'Giveaway Page Overview',
      disambiguation: 'This chunk describes the Giveaway Page Overview mechanic itself, not its interactions. It is not a generic legal sweepstakes template or a backend implementation spec by itself.',
      mechanics: ['Giveaway Page Overview'],
      tags: ['trackerai', 'giveaway', 'page', 'overview', 'monthly giveaways'],
      paragraphs: [...GIVEAWAY_PAGE_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_giveaway_progress_01',
      source: 'Giveaway Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Monthly Giveaway Progress',
      title: 'Giveaway Page Monthly Giveaway Progress',
      disambiguation: 'This chunk describes the Giveaway Page Monthly Giveaway Progress mechanic itself, not its interactions. It is not the referral form or legal rules section by itself.',
      mechanics: ['Giveaway Page Monthly Giveaway Progress'],
      tags: ['trackerai', 'giveaway', 'progress', 'tickets', 'verified runs', 'referrals'],
      paragraphs: [...GIVEAWAY_PAGE_PROGRESS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_giveaway_player_id_01',
      source: 'Giveaway Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Player ID Participation Gate',
      title: 'Giveaway Page Player ID Participation Gate',
      disambiguation: 'This chunk describes the Giveaway Page Player ID Participation Gate mechanic itself, not its interactions. It is not a general account-settings page.',
      mechanics: ['Giveaway Page Player ID Participation Gate'],
      tags: ['trackerai', 'giveaway', 'player id', 'eligibility', 'participation'],
      paragraphs: [...GIVEAWAY_PAGE_PLAYER_ID_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_giveaway_referrals_01',
      source: 'Giveaway Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Referral Workflow',
      title: 'Giveaway Page Referral Workflow',
      disambiguation: 'This chunk describes the Giveaway Page Referral Workflow mechanic itself, not its interactions. It is not a promise that every signed-in user can always submit or generate a referral code immediately.',
      mechanics: ['Giveaway Page Referral Workflow'],
      tags: ['trackerai', 'giveaway', 'referral', 'code', 'eligibility'],
      paragraphs: [...GIVEAWAY_PAGE_REFERRAL_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_giveaway_current_01',
      source: 'Giveaway Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Current Giveaway Pool',
      title: 'Giveaway Page Current Giveaway Pool',
      disambiguation: 'This chunk describes the Giveaway Page Current Giveaway Pool mechanic itself, not its interactions. It is not the personal progress dashboard or referral workflow by itself.',
      mechanics: ['Giveaway Page Current Giveaway Pool'],
      tags: ['trackerai', 'giveaway', 'countdown', 'prizes', 'odds'],
      paragraphs: [...GIVEAWAY_PAGE_CURRENT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_giveaway_rules_01',
      source: 'Giveaway Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Rules and Terms Section',
      title: 'Giveaway Page Rules and Terms Section',
      disambiguation: 'This chunk describes the Giveaway Page Rules and Terms Section mechanic itself, not its interactions. It is not a full external legal handbook.',
      mechanics: ['Giveaway Page Rules and Terms Section'],
      tags: ['trackerai', 'giveaway', 'rules', 'terms', 'legal'],
      paragraphs: [...GIVEAWAY_PAGE_RULES_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_giveaway_processing_01',
      source: 'Giveaway Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Ticket Qualification Processing',
      title: 'Giveaway Page Ticket Qualification Processing',
      disambiguation: 'This chunk describes the Giveaway Page Ticket Qualification Processing mechanic itself, not its interactions. It is not a claim that the UI exposes every internal moderation or database detail.',
      mechanics: ['Giveaway Page Ticket Qualification Processing'],
      tags: ['trackerai', 'giveaway', 'ticket processing', 'verified runs', 'streaks', 'monthly draw'],
      paragraphs: [...GIVEAWAY_PAGE_PROCESSING_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_giveaway_leaderboards_01',
      source: 'Giveaway Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Staff Leaderboards',
      title: 'Giveaway Page Staff Leaderboards',
      disambiguation: 'This chunk describes the Giveaway Page Staff Leaderboards mechanic itself, not its interactions. It is not a public feature available to every participant.',
      mechanics: ['Giveaway Page Staff Leaderboards'],
      tags: ['trackerai', 'giveaway', 'leaderboards', 'admin', 'moderator'],
      paragraphs: [...GIVEAWAY_PAGE_LEADERBOARD_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_giveaway_ai_01',
      source: 'Giveaway Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on Giveaway Page',
      title: 'Giveaway Page AI Help Coverage',
      disambiguation: 'This chunk describes the Giveaway Page AI Help Coverage mechanic itself, not its interactions. It is not unrestricted silent mutation of giveaway participation state.',
      mechanics: ['Giveaway Page AI Help Coverage'],
      tags: ['trackerai', 'giveaway', 'ai help', 'rules', 'referrals'],
      paragraphs: [...GIVEAWAY_PAGE_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_giveaway_faq_use_01',
      source: 'Giveaway Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I use the giveaway page?',
      title: 'How do I use the giveaway page?',
      disambiguation: 'This chunk is about the interaction between the main giveaway page surfaces, not a generic explanation of raffles outside the page.',
      mechanics: ['Giveaway Page Overview', 'Giveaway Page Monthly Giveaway Progress', 'Giveaway Page Current Giveaway Pool', 'Giveaway Page Rules and Terms Section'],
      tags: ['trackerai', 'giveaway', 'faq', 'workflow', 'page'],
      interaction_type: 'cross_system',
      interaction_summary: 'Giveaway Page Overview, Giveaway Page Monthly Giveaway Progress, Giveaway Page Current Giveaway Pool, and Giveaway Page Rules and Terms Section explain how the route combines public giveaway information with the signed-in participation dashboard.',
      paragraphs: [
        'Giveaway Page Overview explains the route as a whole, Giveaway Page Monthly Giveaway Progress explains the signed-in dashboard, Giveaway Page Current Giveaway Pool explains the live prize section, and Giveaway Page Rules and Terms Section explains where the official participation rules live.',
        'That matters because the page is not only a prize advertisement and not only a personal dashboard. It is both at once.',
        'The clearest answer is to name those mechanics directly: review the public rules and current prize pool first, then use the progress section when signed in to check your Player ID status, run tickets, referral tickets, and total monthly entries.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_giveaway_faq_referral_code_01',
      source: 'Giveaway Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why can\'t I generate or submit a referral code on the giveaway page?',
      title: 'Why can\'t I generate or submit a referral code on the giveaway page?',
      disambiguation: 'This chunk is about the interaction between referral gating, Player ID participation, and the signed-in giveaway dashboard, not a bug claim by itself.',
      mechanics: ['Giveaway Page Referral Workflow', 'Giveaway Page Player ID Participation Gate', 'Giveaway Page Monthly Giveaway Progress'],
      tags: ['trackerai', 'giveaway', 'faq', 'referral code', 'eligibility', 'player id'],
      interaction_type: 'conditional',
      interaction_summary: 'Giveaway Page Referral Workflow, Giveaway Page Player ID Participation Gate, and Giveaway Page Monthly Giveaway Progress explain why referral actions can be blocked by first-month timing, missing Player ID, or missing qualifying progress.',
      paragraphs: [
        'Giveaway Page Referral Workflow explains the first-eligible-month window and the one-time referral constraints, while Giveaway Page Player ID Participation Gate explains why missing Player ID blocks giveaway participation features.',
        'Giveaway Page Monthly Giveaway Progress matters because referral-code generation is also tied to qualifying run progress and eligibility timing shown on the dashboard.',
        'The clearest answer is to name those mechanics directly: referral actions can be blocked because you are outside the referral-entry window, do not yet have a Player ID on file, have not uploaded enough qualifying runs to generate your own code, or already have a referral applied.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_giveaway_faq_player_id_01',
      source: 'Giveaway Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What does Player ID do on the giveaway page, and what happens if I remove it?',
      title: 'What does Player ID do on the giveaway page, and what happens if I remove it?',
      disambiguation: 'This chunk is about the interaction between Player ID participation gating and the signed-in giveaway dashboard, not a general profile-editing guide.',
      mechanics: ['Giveaway Page Player ID Participation Gate', 'Giveaway Page Monthly Giveaway Progress'],
      tags: ['trackerai', 'giveaway', 'faq', 'player id', 'eligibility', 'remove'],
      interaction_type: 'conditional',
      interaction_summary: 'Giveaway Page Player ID Participation Gate and Giveaway Page Monthly Giveaway Progress explain why Player ID is needed for participation and why removing it affects eligibility without necessarily erasing monthly progress.',
      paragraphs: [
        'Giveaway Page Player ID Participation Gate explains the entry form, the confirmed-entry state, and the removal warning dialog, while Giveaway Page Monthly Giveaway Progress explains the ticket and progress context users are looking at when they make that decision.',
        'That is why removing the Player ID is treated as a participation change, not just cosmetic profile cleanup.',
        'The clearest answer is to name those mechanics directly: the Player ID confirms your giveaway participation target for prize fulfillment, and removing it disqualifies you until it is added again even though the page warns that same-month progress can still be preserved if you re-enter in time.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_giveaway_faq_tickets_01',
      source: 'Giveaway Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How are giveaway tickets and odds calculated on the page?',
      title: 'How are giveaway tickets and odds calculated on the page?',
      disambiguation: 'This chunk is about the interaction between monthly progress, ticket processing, and the current giveaway pool, not a promise that every raw run creates a ticket instantly.',
      mechanics: ['Giveaway Page Monthly Giveaway Progress', 'Giveaway Page Ticket Qualification Processing', 'Giveaway Page Current Giveaway Pool'],
      tags: ['trackerai', 'giveaway', 'faq', 'tickets', 'odds', 'streaks'],
      interaction_type: 'cross_system',
      interaction_summary: 'Giveaway Page Monthly Giveaway Progress, Giveaway Page Ticket Qualification Processing, and Giveaway Page Current Giveaway Pool explain how qualifying activity turns into displayed tickets and then into the odds estimates shown on the page.',
      paragraphs: [
        'Giveaway Page Monthly Giveaway Progress explains where your run tickets, referral tickets, and total tickets are shown, and Giveaway Page Ticket Qualification Processing explains that those counts depend on milestone rules, streak rules, referral qualification, and run-quality checks.',
        'Giveaway Page Current Giveaway Pool is the output side of that interaction because it shows the active pool size and the per-prize chance chips derived from your current tickets against that pool.',
        'The clearest answer is to name those mechanics directly: tickets come from qualifying milestone-based run and referral processing, then the page compares your current total against the active pool to estimate the displayed odds.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_giveaway_faq_leaderboards_01',
      source: 'Giveaway Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Who can see the giveaway leaderboards?',
      title: 'Who can see the giveaway leaderboards?',
      disambiguation: 'This chunk is about the interaction between giveaway permissions and the route layout, not the public site leaderboard page.',
      mechanics: ['Giveaway Page Staff Leaderboards', 'Giveaway Page Overview'],
      tags: ['trackerai', 'giveaway', 'faq', 'leaderboards', 'permissions', 'staff'],
      interaction_type: 'conditional',
      interaction_summary: 'Giveaway Page Staff Leaderboards and Giveaway Page Overview explain why the page has a leaderboard section that only appears for staff-capable accounts.',
      paragraphs: [
        'Giveaway Page Staff Leaderboards explains the admin-and-moderator-only visibility rule, and Giveaway Page Overview explains that the route mixes public sections with signed-in and staff-only surfaces.',
        'That is why a normal participant can still use the giveaway page fully for their own progress without ever seeing the staff board area.',
        'The clearest answer is to name those mechanics directly: giveaway leaderboards are a staff-only section that appears only after admin or moderator permissions resolve successfully.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_giveaway_faq_ai_01',
      source: 'Giveaway Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do on the giveaway page?',
      title: 'What can TrackerAI help me do on the giveaway page?',
      disambiguation: 'This chunk is about the interaction between giveaway page knowledge and TrackerAI help boundaries, not unrestricted silent mutation of giveaway participation or referral state.',
      mechanics: ['Giveaway Page Overview', 'Giveaway Page AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'giveaway', 'faq', 'ai help', 'rules', 'eligibility'],
      interaction_type: 'conditional',
      interaction_summary: 'Giveaway Page Overview, Giveaway Page AI Help Coverage, and TrackerAI Safety Guardrails define the kinds of giveaway-page explanation and guidance the assistant can provide without pretending it should silently apply participation changes.',
      paragraphs: [
        'Giveaway Page Overview provides the route context, and Giveaway Page AI Help Coverage explains why the page is a good fit for requirement and eligibility explanations.',
        'This is where TrackerAI is most useful for normal users: clarifying giveaway requirements, explaining why a referral step is blocked, identifying whether Player ID or run qualification is the missing piece, and pointing to the right rules section on the page.',
        'TrackerAI Safety Guardrails is the boundary that keeps that help honest, because explanation and guided action are different from silently removing a Player ID or applying referral participation changes without clear intent.',
      ],
    }),
  ]
}
