import {
  WORKSHOP_CALCULATOR_INPUT_FACTS,
  WORKSHOP_CALCULATOR_OUTPUT_FACTS,
  WORKSHOP_CALCULATOR_OVERVIEW_FACTS,
  WORKSHOP_TRACKER_AI_FACTS,
  WORKSHOP_TRACKER_CALCULATOR_LINK_FACTS,
  WORKSHOP_TRACKER_OVERVIEW_FACTS,
  WORKSHOP_TRACKER_OVERVIEW_TAB_FACTS,
  WORKSHOP_TRACKER_PROGRESS_FACTS,
  WORKSHOP_TRACKER_SYNC_FACTS,
} from './trackerAiWorkshopSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiWorkshopCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_workshop_overview_01',
      source: 'Workshop Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Workshop Tracker',
      title: 'Workshop Tracker Overview',
      disambiguation: 'This chunk describes the Workshop Tracker Overview mechanic itself, not its interactions. It is not the general workshop mechanics encyclopedia or raw workshop stat formulas.',
      mechanics: ['Workshop Tracker Overview'],
      tags: ['trackerai', 'workshop', 'tracker', 'site page', 'overview'],
      paragraphs: [...WORKSHOP_TRACKER_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_workshop_progress_01',
      source: 'Workshop Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Progress Planning Views',
      title: 'Workshop Tracker Progress Planning Views',
      disambiguation: 'This chunk describes the Workshop Tracker Progress Planning Views mechanic itself, not its interactions. It is not the full calculator output table or a generic workshop strategy guide.',
      mechanics: ['Workshop Tracker Progress Planning Views'],
      tags: ['trackerai', 'workshop', 'tracker', 'progress', 'enhancements', 'discounts'],
      paragraphs: [...WORKSHOP_TRACKER_PROGRESS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_workshop_overview_tab_01',
      source: 'Workshop Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'All Workshop Tab',
      title: 'Workshop Tracker All Workshop Tab',
      disambiguation: 'This chunk describes the Workshop Tracker All Workshop Tab mechanic itself, not its interactions. It is not the progress table or a standalone preset system outside the tracker page.',
      mechanics: ['Workshop Tracker All Workshop Tab'],
      tags: ['trackerai', 'workshop', 'tracker', 'overview', 'presets', 'disable'],
      paragraphs: [...WORKSHOP_TRACKER_OVERVIEW_TAB_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_workshop_sync_01',
      source: 'Workshop Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Local Save and Sync',
      title: 'Workshop Tracker Local Save and Sync',
      disambiguation: 'This chunk describes the Workshop Tracker Local Save and Sync mechanic itself, not its interactions. It is not a low-level sync protocol dump.',
      mechanics: ['Workshop Tracker Local Save and Sync'],
      tags: ['trackerai', 'workshop', 'tracker', 'sync', 'local save', 'cloud'],
      paragraphs: [...WORKSHOP_TRACKER_SYNC_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_workshop_calculator_overview_01',
      source: 'Workshop Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Workshop Calculator',
      title: 'Workshop Calculator Overview',
      disambiguation: 'This chunk describes the Workshop Calculator Overview mechanic itself, not its interactions. It is not the full tracker page or the general workshop encyclopedia.',
      mechanics: ['Workshop Calculator Overview'],
      tags: ['trackerai', 'workshop', 'calculator', 'site page', 'overview'],
      paragraphs: [...WORKSHOP_CALCULATOR_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_workshop_calculator_inputs_01',
      source: 'Workshop Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Calculator Inputs and State',
      title: 'Workshop Calculator Inputs and State',
      disambiguation: 'This chunk describes the Workshop Calculator Inputs and State mechanic itself, not its interactions. It is not the tracker progress table or a hidden export system.',
      mechanics: ['Workshop Calculator Inputs and State'],
      tags: ['trackerai', 'workshop', 'calculator', 'inputs', 'discounts', 'targets'],
      paragraphs: [...WORKSHOP_CALCULATOR_INPUT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_workshop_calculator_outputs_01',
      source: 'Workshop Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Calculator Outputs',
      title: 'Workshop Calculator Outputs',
      disambiguation: 'This chunk describes the Workshop Calculator Outputs mechanic itself, not its interactions. It is not a sync explanation or a guarantee that every stat uses the same cost path.',
      mechanics: ['Workshop Calculator Outputs'],
      tags: ['trackerai', 'workshop', 'calculator', 'outputs', 'coin', 'cash', 'enhancements'],
      paragraphs: [...WORKSHOP_CALCULATOR_OUTPUT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_workshop_link_01',
      source: 'Workshop Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Tracker and Calculator Link',
      title: 'Workshop Tracker and Calculator Link',
      disambiguation: 'This chunk describes the Workshop Tracker and Calculator Link mechanic itself, not its interactions. It is not a claim that both pages are identical views.',
      mechanics: ['Workshop Tracker and Calculator Link'],
      tags: ['trackerai', 'workshop', 'tracker', 'calculator', 'shared state'],
      paragraphs: [...WORKSHOP_TRACKER_CALCULATOR_LINK_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_workshop_ai_01',
      source: 'Workshop Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on Workshop Pages',
      title: 'Workshop Tracker and Calculator AI Help Coverage',
      disambiguation: 'This chunk describes the Workshop Tracker and Calculator AI Help Coverage mechanic itself, not its interactions. It is not unrestricted bulk editing or silent tracker resets.',
      mechanics: ['Workshop Tracker and Calculator AI Help Coverage'],
      tags: ['trackerai', 'workshop', 'ai help', 'tracker', 'calculator'],
      paragraphs: [...WORKSHOP_TRACKER_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_workshop_faq_use_01',
      source: 'Workshop Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I use the Workshop tracker page?',
      title: 'How do I use the Workshop tracker page?',
      disambiguation: 'This chunk is about the interaction between the main Workshop tracker tabs, not the deeper game meaning of workshop stats.',
      mechanics: ['Workshop Tracker Overview', 'Workshop Tracker Progress Planning Views', 'Workshop Tracker All Workshop Tab', 'Workshop Tracker and Calculator Link'],
      tags: ['trackerai', 'workshop', 'faq', 'tracker', 'tabs', 'workflow'],
      interaction_type: 'cross_system',
      interaction_summary: 'Workshop Tracker Overview, Workshop Tracker Progress Planning Views, Workshop Tracker All Workshop Tab, and Workshop Tracker and Calculator Link explain how the tracker splits saved planning, broad stat editing, and calculator handoff into separate surfaces.',
      paragraphs: [
        'Workshop Tracker Overview explains the page as a whole, Workshop Tracker Progress Planning Views explains the day-to-day planning tables, Workshop Tracker All Workshop Tab explains broad saved-state editing, and Workshop Tracker and Calculator Link explains how calculator handoff fits into the page.',
        'That matters because users often ask where a specific workshop task belongs before they ask about the numbers themselves.',
        'The clearest answer is to name those mechanics directly: use Progress for target planning, use All Workshop for broad stat maintenance and presets, and use the calculator link when the question becomes detailed cost math for one stat.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_workshop_faq_tracker_vs_calc_01',
      source: 'Workshop Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What is the difference between the Workshop tracker and calculator?',
      title: 'What is the difference between the Workshop tracker and calculator?',
      disambiguation: 'This chunk is about the interaction between the Workshop tracker and calculator, not a claim that one replaces the other.',
      mechanics: ['Workshop Tracker Overview', 'Workshop Calculator Overview', 'Workshop Tracker and Calculator Link'],
      tags: ['trackerai', 'workshop', 'faq', 'tracker', 'calculator', 'difference'],
      interaction_type: 'cross_system',
      interaction_summary: 'Workshop Tracker Overview, Workshop Calculator Overview, and Workshop Tracker and Calculator Link explain why one page manages saved progress and presets while the other focuses on stat-specific upgrade math.',
      paragraphs: [
        'Workshop Tracker Overview explains the broader management page, Workshop Calculator Overview explains the focused planning page, and Workshop Tracker and Calculator Link explains why they share context instead of acting like unrelated tools.',
        'That relationship is the practical answer for users who want to know where to start.',
        'The clearest answer is to name those mechanics directly: use the tracker for long-term saved workshop state, use the calculator for one-stat cost planning, and use the shared-link mechanic for how the two surfaces stay aligned.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_workshop_faq_modes_01',
      source: 'Workshop Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why are Workshop and Enhancements separated on both pages?',
      title: 'Why are Workshop and Enhancements separated on both pages?',
      disambiguation: 'This chunk is about the interaction between the Workshop tracker planning views and Workshop calculator overview, not a generic answer about upgrades in the abstract.',
      mechanics: ['Workshop Tracker Progress Planning Views', 'Workshop Calculator Overview', 'Workshop Calculator Inputs and State'],
      tags: ['trackerai', 'workshop', 'faq', 'enhancements', 'tabs', 'modes'],
      interaction_type: 'conditional',
      interaction_summary: 'Workshop Tracker Progress Planning Views, Workshop Calculator Overview, and Workshop Calculator Inputs and State explain why Workshop and Enhancements stay split into different modes instead of being merged into one confusing table.',
      paragraphs: [
        'Workshop Tracker Progress Planning Views explains that the tracker already treats Workshop and Enhancements as different planning tables, while Workshop Calculator Overview and Workshop Calculator Inputs and State show that the calculator makes the same split in its own inputs and breakdowns.',
        'That split exists because base workshop stats and enhancement stats do not use the same levels, discount controls, or cost presentation.',
        'The clearest answer is to name those mechanics directly: Workshop and Enhancements are separated because both the tracker and the calculator treat them as related but distinct planning systems.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_workshop_faq_discounts_01',
      source: 'Workshop Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What do the discount fields and average coins per hour affect on Workshop?',
      title: 'What do the discount fields and average coins per hour affect on Workshop?',
      disambiguation: 'This chunk is about the interaction between Workshop tracker planning inputs and Workshop calculator planning inputs, not a universal claim about game economy formulas outside the site tools.',
      mechanics: ['Workshop Tracker Progress Planning Views', 'Workshop Calculator Inputs and State', 'Workshop Calculator Outputs'],
      tags: ['trackerai', 'workshop', 'faq', 'discounts', 'coins per hour', 'time'],
      interaction_type: 'conditional',
      interaction_summary: 'Workshop Tracker Progress Planning Views, Workshop Calculator Inputs and State, and Workshop Calculator Outputs explain how discount controls change displayed costs and how coins-per-hour turns remaining coin costs into time estimates.',
      paragraphs: [
        'Workshop Tracker Progress Planning Views explains the tracker-side discount and coins-per-hour inputs, Workshop Calculator Inputs and State explains the matching calculator-side discount controls, and Workshop Calculator Outputs explains where those inputs appear as discounted totals and breakdown rows.',
        'That is why the tracker can show time estimates for remaining coin costs while the calculator can show discounted cost paths for the same stat selection.',
        'The clearest answer is to name those mechanics directly: discount fields change displayed upgrade costs, and average coins per hour is what turns remaining coin costs into time estimates on the tracker.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_workshop_faq_disable_01',
      source: 'Workshop Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do disabled Workshop stats affect planning views?',
      title: 'How do disabled Workshop stats affect planning views?',
      disambiguation: 'This chunk is about the interaction between the All Workshop tab and the Progress planning views, not a claim that disabling a stat deletes its saved data.',
      mechanics: ['Workshop Tracker All Workshop Tab', 'Workshop Tracker Progress Planning Views'],
      tags: ['trackerai', 'workshop', 'faq', 'disabled', 'presets', 'tracker'],
      interaction_type: 'cross_system',
      interaction_summary: 'Workshop Tracker All Workshop Tab and Workshop Tracker Progress Planning Views explain how stats can be marked inactive for planning without erasing their saved levels from the tracker preset.',
      paragraphs: [
        'Workshop Tracker All Workshop Tab explains where users disable or re-enable stats while maintaining saved preset state, and Workshop Tracker Progress Planning Views explains how those inactive stats show up differently in the active planning workflow.',
        'That matters because users often want to narrow the planning surface without treating inactive stats as lost data.',
        'The clearest answer is to name those mechanics directly: disable a stat in All Workshop when you want it out of the active planning workflow, then re-enable it later without rebuilding the saved levels from scratch.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_workshop_faq_sync_01',
      source: 'Workshop Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Does the Workshop tracker save and sync with the calculator?',
      title: 'Does the Workshop tracker save and sync with the calculator?',
      disambiguation: 'This chunk is about the interaction between Workshop tracker sync behavior and shared tracker-calculator workflow, not a low-level store contract.',
      mechanics: ['Workshop Tracker Local Save and Sync', 'Workshop Tracker and Calculator Link', 'Workshop Calculator Inputs and State'],
      tags: ['trackerai', 'workshop', 'faq', 'sync', 'shared state', 'calculator'],
      interaction_type: 'conditional',
      interaction_summary: 'Workshop Tracker Local Save and Sync, Workshop Tracker and Calculator Link, and Workshop Calculator Inputs and State explain how Workshop state persists and why calculator context often follows the tracker workflow.',
      paragraphs: [
        'Workshop Tracker Local Save and Sync explains the persistence layer, Workshop Tracker and Calculator Link explains the shared page workflow, and Workshop Calculator Inputs and State explains the calculator context that stays available across visits.',
        'That is why the calculator can feel like it already knows the workshop mode and stat context the tracker was using.',
        'The cleanest answer is to name those mechanics directly: use the sync chunk for persistence, then use the tracker-calculator link and calculator-state chunk for how that saved context carries into the calculator.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_workshop_faq_ai_01',
      source: 'Workshop Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do with the Workshop tracker and calculator?',
      title: 'What can TrackerAI help me do with the Workshop tracker and calculator?',
      disambiguation: 'This chunk is about the interaction between Workshop page knowledge and TrackerAI help boundaries, not unrestricted bulk edits or sync control.',
      mechanics: ['Workshop Tracker Overview', 'Workshop Calculator Overview', 'Workshop Tracker and Calculator Link', 'Workshop Tracker and Calculator AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'workshop', 'faq', 'ai help', 'tracker', 'calculator'],
      interaction_type: 'conditional',
      interaction_summary: 'Workshop Tracker Overview, Workshop Calculator Overview, Workshop Tracker and Calculator Link, Workshop Tracker and Calculator AI Help Coverage, and TrackerAI Safety Guardrails define the kinds of Workshop help the assistant can give without pretending it should silently rewrite saved tracker state.',
      paragraphs: [
        'Workshop Tracker Overview and Workshop Calculator Overview provide the two page contexts, Workshop Tracker and Calculator Link explains why users move between them, and Workshop Tracker and Calculator AI Help Coverage explains why this is a strong explanation-and-guidance area for the assistant.',
        'This is where TrackerAI is most useful for normal users: deciding which Workshop surface to use, understanding discount and time columns, and clarifying why a tracker row and a calculator breakdown are related.',
        'TrackerAI Safety Guardrails is the boundary that keeps that help honest, because explanation and interpretation are different from silently changing saved levels, running sync, or clearing progress on the user’s behalf.',
      ],
    }),
  ]
}
