import {
  SHARD_SPLITTER_AI_FACTS,
  SHARD_SPLITTER_DAMAGE_PATH_CONFIG_FACTS,
  SHARD_SPLITTER_DAMAGE_PATH_FACTS,
  SHARD_SPLITTER_INPUT_FACTS,
  SHARD_SPLITTER_OUTPUT_FACTS,
  SHARD_SPLITTER_OVERVIEW_FACTS,
  SHARD_SPLITTER_STATE_FACTS,
} from './trackerAiShardSplitterSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiShardSplitterCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_shardsplitter_overview_01',
      source: 'Shard Splitter Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Shard Splitter',
      title: 'Shard Splitter Overview',
      disambiguation: 'This chunk describes the Shard Splitter Overview mechanic itself, not its interactions. It is not the module tracker page or the broader module reference layer.',
      mechanics: ['Shard Splitter Overview'],
      tags: ['trackerai', 'shard splitter', 'modules', 'calculator', 'overview'],
      paragraphs: [...SHARD_SPLITTER_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_shardsplitter_inputs_01',
      source: 'Shard Splitter Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Splitter Inputs',
      title: 'Shard Splitter Inputs',
      disambiguation: 'This chunk describes the Shard Splitter Inputs mechanic itself, not its interactions. It is not the best-result output card or the damage-path ROI table.',
      mechanics: ['Shard Splitter Inputs'],
      tags: ['trackerai', 'shard splitter', 'calculator', 'inputs', 'module type', 'shards'],
      paragraphs: [...SHARD_SPLITTER_INPUT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_shardsplitter_outputs_01',
      source: 'Shard Splitter Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Splitter Outputs',
      title: 'Shard Splitter Outputs',
      disambiguation: 'This chunk describes the Shard Splitter Outputs mechanic itself, not its interactions. It is not a guarantee that one candidate always fits every user goal.',
      mechanics: ['Shard Splitter Outputs'],
      tags: ['trackerai', 'shard splitter', 'calculator', 'outputs', 'best result', 'alternatives'],
      paragraphs: [...SHARD_SPLITTER_OUTPUT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_shardsplitter_damagepath_01',
      source: 'Shard Splitter Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Effective Module Damage Path',
      title: 'Shard Splitter Effective Module Damage Path',
      disambiguation: 'This chunk describes the Shard Splitter Effective Module Damage Path mechanic itself, not its interactions. It is not the normal split-candidate table.',
      mechanics: ['Shard Splitter Effective Module Damage Path'],
      tags: ['trackerai', 'shard splitter', 'calculator', 'damage path', 'roi'],
      paragraphs: [...SHARD_SPLITTER_DAMAGE_PATH_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_shardsplitter_damageconfig_01',
      source: 'Shard Splitter Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Damage Path Configuration',
      title: 'Shard Splitter Damage Path Configuration',
      disambiguation: 'This chunk describes the Shard Splitter Damage Path Configuration mechanic itself, not its interactions. It is not the split-candidate results table or a generic module setup guide.',
      mechanics: ['Shard Splitter Damage Path Configuration'],
      tags: ['trackerai', 'shard splitter', 'calculator', 'damage path', 'configuration'],
      paragraphs: [...SHARD_SPLITTER_DAMAGE_PATH_CONFIG_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_shardsplitter_state_01',
      source: 'Shard Splitter Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Persistent State and Workspace Link',
      title: 'Shard Splitter Persistent State and Workspace Link',
      disambiguation: 'This chunk describes the Shard Splitter Persistent State and Workspace Link mechanic itself, not its interactions. It is not a cloud-sync contract or a claim that the tool writes directly to the module tracker.',
      mechanics: ['Shard Splitter Persistent State and Workspace Link'],
      tags: ['trackerai', 'shard splitter', 'calculator', 'shared state', 'workspace'],
      paragraphs: [...SHARD_SPLITTER_STATE_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_shardsplitter_ai_01',
      source: 'Shard Splitter Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on Shard Splitter',
      title: 'Shard Splitter AI Help Coverage',
      disambiguation: 'This chunk describes the Shard Splitter AI Help Coverage mechanic itself, not its interactions. It is not unrestricted bulk editing or silent optimizer execution.',
      mechanics: ['Shard Splitter AI Help Coverage'],
      tags: ['trackerai', 'shard splitter', 'ai help', 'modules', 'calculator'],
      paragraphs: [...SHARD_SPLITTER_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_shardsplitter_faq_use_01',
      source: 'Shard Splitter Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I use the Shard Splitter page?',
      title: 'How do I use the Shard Splitter page?',
      disambiguation: 'This chunk is about the interaction between the main Shard Splitter page modes, not the deeper module game mechanics behind the numbers.',
      mechanics: ['Shard Splitter Overview', 'Shard Splitter Inputs', 'Shard Splitter Outputs', 'Shard Splitter Effective Module Damage Path'],
      tags: ['trackerai', 'shard splitter', 'faq', 'workflow', 'calculator', 'modules'],
      interaction_type: 'cross_system',
      interaction_summary: 'Shard Splitter Overview, Shard Splitter Inputs, Shard Splitter Outputs, and Shard Splitter Effective Module Damage Path explain how the page splits setup, split recommendations, and ROI-based damage-path planning into related but different modes.',
      paragraphs: [
        'Shard Splitter Overview explains the page as a two-mode optimizer, Shard Splitter Inputs explains the setup controls, Shard Splitter Outputs explains the split recommendations, and Shard Splitter Effective Module Damage Path explains the upgrade-order mode.',
        'That matters because users often know they want module shard help but are not sure whether they need a target split or an upgrade-order path.',
        'The clearest answer is to name those mechanics directly: use the splitter mode for target allocations, and use the damage-path mode when the question is about best ROI order over time.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_shardsplitter_faq_best_01',
      source: 'Shard Splitter Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What is the difference between Best Result and Alternative Candidates?',
      title: 'What is the difference between Best Result and Alternative Candidates?',
      disambiguation: 'This chunk is about the interaction between the splitter output cards and tables, not a claim that alternatives are mistakes or useless results.',
      mechanics: ['Shard Splitter Inputs', 'Shard Splitter Outputs'],
      tags: ['trackerai', 'shard splitter', 'faq', 'best result', 'alternatives'],
      interaction_type: 'conditional',
      interaction_summary: 'Shard Splitter Inputs and Shard Splitter Outputs explain why one specific setup can yield a highlighted best-result summary while still keeping alternative split candidates available for comparison.',
      paragraphs: [
        'Shard Splitter Inputs explains that the recommendation depends on the current module-type and shard-planning setup, and Shard Splitter Outputs explains that the page offers a highlighted best result, a next split projection, and deeper alternative candidate tables instead of only one recommendation.',
        'That matters because users sometimes want the strongest current recommendation, while other times they want to compare nearby tradeoffs before committing their shards.',
        'The clearest answer is to name that mechanic directly: Best Result is the highlighted recommendation, while Alternative Candidates are the nearby comparison options that help you judge tradeoffs.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_shardsplitter_faq_damagepath_01',
      source: 'Shard Splitter Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'When should I use Effective Module Damage Path instead of Shard Splitter?',
      title: 'When should I use Effective Module Damage Path instead of Shard Splitter?',
      disambiguation: 'This chunk is about the interaction between the two shard-splitter page modes, not a claim that one of them is obsolete.',
      mechanics: ['Shard Splitter Overview', 'Shard Splitter Outputs', 'Shard Splitter Effective Module Damage Path'],
      tags: ['trackerai', 'shard splitter', 'faq', 'damage path', 'roi', 'which mode'],
      interaction_type: 'cross_system',
      interaction_summary: 'Shard Splitter Overview, Shard Splitter Outputs, and Shard Splitter Effective Module Damage Path explain why the page offers both split recommendations and an ROI-ordered damage-path mode.',
      paragraphs: [
        'Shard Splitter Overview explains the paired modes, Shard Splitter Outputs explains the split-target side, and Shard Splitter Effective Module Damage Path explains the upgrade-order ROI side.',
        'That means the right mode depends on the kind of answer the user wants, not just the fact that both modes involve module shards.',
        'The clearest answer is to name those mechanics directly: use Shard Splitter when you want target split recommendations, and use Effective Module Damage Path when you want the best upgrade order by ROI.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_shardsplitter_faq_config_01',
      source: 'Shard Splitter Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why does Effective Module Damage Path ask for separate Cannon and Core settings?',
      title: 'Why does Effective Module Damage Path ask for separate Cannon and Core settings?',
      disambiguation: 'This chunk is about the interaction between the damage-path configuration and damage-path results, not a claim that the splitter and damage path should share identical input models.',
      mechanics: ['Shard Splitter Damage Path Configuration', 'Shard Splitter Effective Module Damage Path'],
      tags: ['trackerai', 'shard splitter', 'faq', 'damage path', 'cannon', 'core'],
      interaction_type: 'conditional',
      interaction_summary: 'Shard Splitter Damage Path Configuration and Shard Splitter Effective Module Damage Path explain why the ROI path needs separate Cannon and Core assumptions before it can order upgrades correctly.',
      paragraphs: [
        'Shard Splitter Damage Path Configuration explains that the mode stores separate Cannon and Core rarity, level, shard, and efficiency inputs, and Shard Splitter Effective Module Damage Path explains that the final table ranks upgrades from those assumptions.',
        'That is why the page asks for more setup here than in the simpler split-target mode: the damage-path answer depends on how both module pairs are currently configured.',
        'The clearest answer is to name those mechanics directly: separate Cannon and Core settings exist because the ROI path compares upgrade order across both module pairs, not just one shared shard bucket.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_shardsplitter_faq_state_01',
      source: 'Shard Splitter Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why does Shard Splitter remember my last setup?',
      title: 'Why does Shard Splitter remember my last setup?',
      disambiguation: 'This chunk is about the interaction between shard splitter persistence and the broader module calculator workspace, not a cloud-sync explanation.',
      mechanics: ['Shard Splitter Persistent State and Workspace Link', 'Module Calculator Cross-Tab State'],
      tags: ['trackerai', 'shard splitter', 'faq', 'shared state', 'persistence', 'modules'],
      interaction_type: 'cross_system',
      interaction_summary: 'Shard Splitter Persistent State and Workspace Link and Module Calculator Cross-Tab State explain why shard-splitter inputs and UI state can survive across visits and related module planning tabs.',
      paragraphs: [
        'Shard Splitter Persistent State and Workspace Link explains the tool-side persistence and workspace connection, and Module Calculator Cross-Tab State explains how that shared module planning context can also matter inside the broader module calculator workspace.',
        'That is why the tool can feel like it resumes where the last module-planning session left off instead of starting empty every time.',
        'The clearest answer is to name those mechanics directly: Shard Splitter remembers your setup because it persists both planning inputs and UI state as part of the module-planning workflow.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_shardsplitter_faq_ai_01',
      source: 'Shard Splitter Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do with Shard Splitter?',
      title: 'What can TrackerAI help me do with Shard Splitter?',
      disambiguation: 'This chunk is about the interaction between shard-splitter page knowledge and TrackerAI help boundaries, not unrestricted optimizer execution or silent input rewrites.',
      mechanics: ['Shard Splitter Overview', 'Shard Splitter Outputs', 'Shard Splitter Effective Module Damage Path', 'Shard Splitter AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'shard splitter', 'faq', 'ai help', 'modules', 'calculator'],
      interaction_type: 'conditional',
      interaction_summary: 'Shard Splitter Overview, Shard Splitter Outputs, Shard Splitter Effective Module Damage Path, Shard Splitter AI Help Coverage, and TrackerAI Safety Guardrails define the kinds of shard-splitter help the assistant can give without pretending it should silently rewrite optimization inputs.',
      paragraphs: [
        'Shard Splitter Overview, Shard Splitter Outputs, and Shard Splitter Effective Module Damage Path provide the tool context, and Shard Splitter AI Help Coverage explains why this is a strong explanation-and-guidance area for the assistant.',
        'This is where TrackerAI is most useful for normal users: deciding which shard-splitter mode to use, interpreting best-result versus alternative candidates, and understanding how ROI tables differ from split recommendations.',
        'TrackerAI Safety Guardrails is the boundary that keeps that help honest, because explanation and interpretation are different from silently changing optimization inputs or applying a result on the user\'s behalf.',
      ],
    }),
  ]
}
