import {
  CARDS_TRACKER_AI_FACTS,
  CARDS_TRACKER_EQUIPPED_FACTS,
  CARDS_TRACKER_OVERVIEW_FACTS,
  CARDS_TRACKER_OVERVIEW_TAB_FACTS,
  CARDS_TRACKER_PROGRESS_FACTS,
  CARDS_TRACKER_RULE_FACTS,
  CARDS_TRACKER_SYNC_FACTS,
  CARDS_TRACKER_VISUAL_FACTS,
} from './trackerAiCardsSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiCardsCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_cards_overview_01',
      source: 'Cards Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Cards Tracker',
      title: 'Cards Tracker Overview',
      disambiguation: 'This chunk describes the Cards Tracker Overview mechanic itself, not its interactions. It is not the general cards encyclopedia or a separate calculator page.',
      mechanics: ['Cards Tracker Overview'],
      tags: ['trackerai', 'cards', 'tracker', 'site page', 'overview'],
      paragraphs: [...CARDS_TRACKER_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_cards_progress_01',
      source: 'Cards Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Progress Planning Table',
      title: 'Cards Tracker Progress Planning Table',
      disambiguation: 'This chunk describes the Cards Tracker Progress Planning Table mechanic itself, not its interactions. It is not the equipped-preset planner or the all-cards gallery.',
      mechanics: ['Cards Tracker Progress Planning Table'],
      tags: ['trackerai', 'cards', 'tracker', 'progress', 'gems', 'columns'],
      paragraphs: [...CARDS_TRACKER_PROGRESS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_cards_overview_tab_01',
      source: 'Cards Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'All Cards Tab',
      title: 'Cards Tracker All Cards Tab',
      disambiguation: 'This chunk describes the Cards Tracker All Cards Tab mechanic itself, not its interactions. It is not the progress planning table or the equipped loadout planner.',
      mechanics: ['Cards Tracker All Cards Tab'],
      tags: ['trackerai', 'cards', 'tracker', 'overview', 'reference', 'effects'],
      paragraphs: [...CARDS_TRACKER_OVERVIEW_TAB_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_cards_equipped_01',
      source: 'Cards Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Equipped Tab and Presets',
      title: 'Cards Tracker Equipped Tab and Presets',
      disambiguation: 'This chunk describes the Cards Tracker Equipped Tab and Presets mechanic itself, not its interactions. It is not the progress row table or a separate combat simulator.',
      mechanics: ['Cards Tracker Equipped Tab and Presets'],
      tags: ['trackerai', 'cards', 'tracker', 'equipped', 'presets', 'slots'],
      paragraphs: [...CARDS_TRACKER_EQUIPPED_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_cards_sync_01',
      source: 'Cards Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Local Save and Sync',
      title: 'Cards Tracker Local Save and Sync',
      disambiguation: 'This chunk describes the Cards Tracker Local Save and Sync mechanic itself, not its interactions. It is not a low-level sync protocol dump.',
      mechanics: ['Cards Tracker Local Save and Sync'],
      tags: ['trackerai', 'cards', 'tracker', 'sync', 'local save', 'cloud'],
      paragraphs: [...CARDS_TRACKER_SYNC_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_cards_rules_01',
      source: 'Cards Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Progress Rules and Derived Fields',
      title: 'Cards Tracker Progress Rules and Derived Fields',
      disambiguation: 'This chunk describes the Cards Tracker Progress Rules and Derived Fields mechanic itself, not its interactions. It is not a generic card-strategy guide.',
      mechanics: ['Cards Tracker Progress Rules and Derived Fields'],
      tags: ['trackerai', 'cards', 'tracker', 'rules', 'mastery', 'completed'],
      paragraphs: [...CARDS_TRACKER_RULE_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_cards_visuals_01',
      source: 'Cards Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Dynamic Card Visuals and Descriptions',
      title: 'Cards Tracker Dynamic Card Visuals and Descriptions',
      disambiguation: 'This chunk describes the Cards Tracker Dynamic Card Visuals and Descriptions mechanic itself, not its interactions. It is not a generic art gallery or a separate rendering system outside the tracker page.',
      mechanics: ['Cards Tracker Dynamic Card Visuals and Descriptions'],
      tags: ['trackerai', 'cards', 'tracker', 'descriptions', 'visuals', 'mastery'],
      paragraphs: [...CARDS_TRACKER_VISUAL_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_cards_ai_01',
      source: 'Cards Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on Cards Tracker',
      title: 'Cards Tracker AI Help Coverage',
      disambiguation: 'This chunk describes the Cards Tracker AI Help Coverage mechanic itself, not its interactions. It is not unrestricted bulk editing or silent resets.',
      mechanics: ['Cards Tracker AI Help Coverage'],
      tags: ['trackerai', 'cards', 'ai help', 'tracker'],
      paragraphs: [...CARDS_TRACKER_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_cards_faq_use_01',
      source: 'Cards Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I use the Cards tracker page?',
      title: 'How do I use the Cards tracker page?',
      disambiguation: 'This chunk is about the interaction between the main Cards tracker tabs, not the deeper game meaning of individual cards.',
      mechanics: ['Cards Tracker Overview', 'Cards Tracker Progress Planning Table', 'Cards Tracker Equipped Tab and Presets', 'Cards Tracker All Cards Tab'],
      tags: ['trackerai', 'cards', 'faq', 'tracker', 'tabs', 'workflow'],
      interaction_type: 'cross_system',
      interaction_summary: 'Cards Tracker Overview, Cards Tracker Progress Planning Table, Cards Tracker Equipped Tab and Presets, and Cards Tracker All Cards Tab explain how the page splits saved progress, loadout presets, and browseable card details into separate surfaces.',
      paragraphs: [
        'Cards Tracker Overview explains the page as a whole, Cards Tracker Progress Planning Table explains the saved progress table, Cards Tracker Equipped Tab and Presets explains the loadout planner, and Cards Tracker All Cards Tab explains the browseable card reference view.',
        'That matters because users often know the card they want to work on before they know which tab owns the right action.',
        'The clearest answer is to name those mechanics directly: use Progress for owned-card tracking and timing estimates, use Equipped for preset loadouts, and use All Cards when the goal is to browse effects and progression details.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_cards_faq_weekly_gems_01',
      source: 'Cards Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why does the Cards tracker ask for estimated weekly gems?',
      title: 'Why does the Cards tracker ask for estimated weekly gems?',
      disambiguation: 'This chunk is about the interaction between the progress planning table and its timing outputs, not a universal gem-income formula outside the tracker.',
      mechanics: ['Cards Tracker Progress Planning Table', 'Cards Tracker Progress Rules and Derived Fields'],
      tags: ['trackerai', 'cards', 'faq', 'gems', 'time to next', 'time to max'],
      interaction_type: 'conditional',
      interaction_summary: 'Cards Tracker Progress Planning Table and Cards Tracker Progress Rules and Derived Fields explain why timing columns need a saved gem pace instead of one fixed site-wide assumption.',
      paragraphs: [
        'Cards Tracker Progress Planning Table explains that the tracker can show gems remaining, time to next, and time to max, while Cards Tracker Progress Rules and Derived Fields explains that those outputs depend on saved row state rather than static card labels alone.',
        'That is why the tracker asks for weekly gems: timing estimates only make sense when they are tied to the pace the user actually expects.',
        'The clearest answer is to name those mechanics directly: estimated weekly gems personalizes the card timing columns so the tracker can project progress from the user\'s own pace.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_cards_faq_mastery_01',
      source: 'Cards Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why is mastery disabled for some cards in the tracker?',
      title: 'Why is mastery disabled for some cards in the tracker?',
      disambiguation: 'This chunk is about the interaction between progress editing and the tracker\'s derived-field rules, not a site bug report or a general mastery guide.',
      mechanics: ['Cards Tracker Progress Planning Table', 'Cards Tracker Progress Rules and Derived Fields'],
      tags: ['trackerai', 'cards', 'faq', 'mastery', 'level 7', 'completed'],
      interaction_type: 'conditional',
      interaction_summary: 'Cards Tracker Progress Planning Table and Cards Tracker Progress Rules and Derived Fields explain why mastery availability depends on the saved level state of the row being edited.',
      paragraphs: [
        'Cards Tracker Progress Planning Table explains where level, mastery, quantity, and completed fields are edited, and Cards Tracker Progress Rules and Derived Fields explains that those values stay linked instead of acting like unrelated toggles.',
        'That is why mastery can be unavailable on lower-level entries and then become editable once the saved row reaches the tracker\'s max-level condition.',
        'The clearest answer is to name those mechanics directly: mastery is disabled until the card reaches the required max-level state because the tracker keeps level, copies, mastery, and completed status internally consistent.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_cards_faq_equipped_01',
      source: 'Cards Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How are equipped presets different from the main card progress list?',
      title: 'How are equipped presets different from the main card progress list?',
      disambiguation: 'This chunk is about the interaction between the equipped planner and the progress tracker, not a claim that equipping a card changes its owned copies automatically.',
      mechanics: ['Cards Tracker Progress Planning Table', 'Cards Tracker Equipped Tab and Presets'],
      tags: ['trackerai', 'cards', 'faq', 'equipped', 'presets', 'progress'],
      interaction_type: 'cross_system',
      interaction_summary: 'Cards Tracker Progress Planning Table and Cards Tracker Equipped Tab and Presets explain why the page keeps owned-card progress and slotted-card presets as related but separate saved workflows.',
      paragraphs: [
        'Cards Tracker Progress Planning Table explains the owned-card rows and timing outputs, while Cards Tracker Equipped Tab and Presets explains the preset-based loadout planner with slots and toggled equipped cards.',
        'That separation matters because users often want to save what they own without implying that every owned card is currently equipped in a preset.',
        'The clearest answer is to name those mechanics directly: Progress stores ownership and upgrade progress, while Equipped stores preset loadouts and slot usage.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_cards_faq_sync_01',
      source: 'Cards Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Does the Cards tracker save and sync everything on the page?',
      title: 'Does the Cards tracker save and sync everything on the page?',
      disambiguation: 'This chunk is about the interaction between cards tracker sync behavior and the broader saved workspace, not a low-level storage contract.',
      mechanics: ['Cards Tracker Overview', 'Cards Tracker Local Save and Sync', 'Cards Tracker Equipped Tab and Presets'],
      tags: ['trackerai', 'cards', 'faq', 'sync', 'presets', 'tabs'],
      interaction_type: 'conditional',
      interaction_summary: 'Cards Tracker Overview, Cards Tracker Local Save and Sync, and Cards Tracker Equipped Tab and Presets explain why the page behaves like a persistent workspace rather than a disposable table.',
      paragraphs: [
        'Cards Tracker Overview explains the multi-tab workspace, Cards Tracker Local Save and Sync explains the local-first and cloud-sync behavior, and Cards Tracker Equipped Tab and Presets shows that saved state includes more than the main progress rows alone.',
        'That is why the page can usually restore tracked entries, presets, and related view context together instead of only reloading a partial card list.',
        'The clearest answer is to name those mechanics directly: the cards tracker saves and syncs the broader workspace, including tracked rows and equipped presets, not just one table snapshot.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_cards_faq_visuals_01',
      source: 'Cards Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why do card descriptions and colors change as I edit tracked progress?',
      title: 'Why do card descriptions and colors change as I edit tracked progress?',
      disambiguation: 'This chunk is about the interaction between cards-tracker progress state and the tracker visuals, not a graphics bug report or a claim that card balance data is being rewritten globally.',
      mechanics: ['Cards Tracker Progress Planning Table', 'Cards Tracker All Cards Tab', 'Cards Tracker Dynamic Card Visuals and Descriptions'],
      tags: ['trackerai', 'cards', 'faq', 'descriptions', 'visuals', 'mastery'],
      interaction_type: 'conditional',
      interaction_summary: 'Cards Tracker Progress Planning Table, Cards Tracker All Cards Tab, and Cards Tracker Dynamic Card Visuals and Descriptions explain why tracked level and mastery updates change the way cards are described and styled throughout the page.',
      paragraphs: [
        'Cards Tracker Progress Planning Table is where level, quantity, mastery, and completed state are edited, Cards Tracker All Cards Tab is where those saved values are displayed as card details, and Cards Tracker Dynamic Card Visuals and Descriptions explains that the tracker reuses saved progress to update placeholders, highlighted effects, and frame styling.',
        'That is why the page can look different after a progress edit even when the user has not changed tabs or manually refreshed anything.',
        'The clearest answer is to name those mechanics directly: cards tracker visuals and descriptions are derived from the saved tracked progress, so changing level or mastery can update both the numbers and the presentation across the workspace.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_cards_faq_ai_01',
      source: 'Cards Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do with the Cards tracker?',
      title: 'What can TrackerAI help me do with the Cards tracker?',
      disambiguation: 'This chunk is about the interaction between cards-tracker page knowledge and TrackerAI help boundaries, not unrestricted bulk edits or silent resets.',
      mechanics: ['Cards Tracker Overview', 'Cards Tracker Progress Planning Table', 'Cards Tracker AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'cards', 'faq', 'ai help', 'tracker'],
      interaction_type: 'conditional',
      interaction_summary: 'Cards Tracker Overview, Cards Tracker Progress Planning Table, Cards Tracker AI Help Coverage, and TrackerAI Safety Guardrails define the kinds of cards-tracker help the assistant can give without pretending it should silently rewrite saved progress.',
      paragraphs: [
        'Cards Tracker Overview and Cards Tracker Progress Planning Table provide the page context, and Cards Tracker AI Help Coverage explains why this is a strong explanation-and-guidance area for the assistant.',
        'This is where TrackerAI is most useful for normal users: clarifying which tab to use, explaining timing and mastery behavior, and helping interpret the tracker\'s saved progress outputs.',
        'TrackerAI Safety Guardrails is the boundary that keeps that help honest, because explanation and interpretation are different from silently removing entries, resetting presets, or forcing a sync decision on the user\'s behalf.',
      ],
    }),
  ]
}
