import {
  LIFETIME_TRACKER_AI_FACTS,
  LIFETIME_TRACKER_ANALYSIS_FACTS,
  LIFETIME_TRACKER_ENTRY_FACTS,
  LIFETIME_TRACKER_INTERPRETATION_FACTS,
  LIFETIME_TRACKER_LEADERBOARD_FACTS,
  LIFETIME_TRACKER_OVERVIEW_FACTS,
  LIFETIME_TRACKER_SCREENSHOT_FACTS,
  LIFETIME_TRACKER_SYNC_FACTS,
  LIFETIME_TRACKER_TABLE_FACTS,
} from './trackerAiLifetimeSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiLifetimeCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_lifetime_overview_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Lifetime Tracker',
      title: 'Lifetime Tracker Overview',
      disambiguation: 'This chunk is about the Lifetime Tracker Overview mechanic itself, not its interactions. It is not a raw save export, a one-off screenshot inbox, or the leaderboard page itself.',
      mechanics: ['Lifetime Tracker Overview'],
      tags: ['trackerai', 'lifetime', 'tracker', 'site page', 'overview'],
      paragraphs: [...LIFETIME_TRACKER_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_lifetime_entry_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Entry Capture',
      title: 'Lifetime Tracker Entry Capture',
      disambiguation: 'This chunk is about the Lifetime Tracker Entry Capture mechanic itself, not its interactions. It is not a promise that OCR is always perfect or that manual entry is forbidden.',
      mechanics: ['Lifetime Tracker Entry Capture'],
      tags: ['trackerai', 'lifetime', 'ocr', 'manual entry', 'screenshots', 'stats'],
      paragraphs: [...LIFETIME_TRACKER_ENTRY_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_lifetime_table_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Table and History Management',
      title: 'Lifetime Tracker Table and History Management',
      disambiguation: 'This chunk is about the Lifetime Tracker Table and History Management mechanic itself, not its interactions. It is not a spreadsheet export format or a moderation queue.',
      mechanics: ['Lifetime Tracker Table and History Management'],
      tags: ['trackerai', 'lifetime', 'table', 'history', 'columns', 'edit', 'delete'],
      paragraphs: [...LIFETIME_TRACKER_TABLE_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_lifetime_analysis_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Averages and Charts',
      title: 'Lifetime Tracker Averages and Charts',
      disambiguation: 'This chunk is about the Lifetime Tracker Averages and Charts mechanic itself, not its interactions. It is not a guarantee that every metric must stay visible at once.',
      mechanics: ['Lifetime Tracker Averages and Charts'],
      tags: ['trackerai', 'lifetime', 'averages', 'charts', 'timeline', 'analysis'],
      paragraphs: [...LIFETIME_TRACKER_ANALYSIS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_lifetime_interpretation_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Reading Lifetime Progress',
      title: 'Lifetime Tracker Reading Lifetime Progress',
      disambiguation: 'This chunk is about the Lifetime Tracker Reading Lifetime Progress mechanic itself, not its interactions. It is not a strict posting schedule or a guarantee that every average is equally meaningful.',
      mechanics: ['Lifetime Tracker Reading Lifetime Progress'],
      tags: ['trackerai', 'lifetime', 'interpretation', 'averages', 'chart', 'snapshots'],
      paragraphs: [...LIFETIME_TRACKER_INTERPRETATION_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_lifetime_sync_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Local Save and Cloud Sync',
      title: 'Lifetime Tracker Local Save and Cloud Sync',
      disambiguation: 'This chunk is about the Lifetime Tracker Local Save and Cloud Sync mechanic itself, not its interactions. It is not a low-level storage schema or a promise that cloud sync always wins silently.',
      mechanics: ['Lifetime Tracker Local Save and Cloud Sync'],
      tags: ['trackerai', 'lifetime', 'sync', 'local save', 'cloud', 'conflicts'],
      paragraphs: [...LIFETIME_TRACKER_SYNC_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_lifetime_screenshots_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Screenshots and Verification Context',
      title: 'Lifetime Tracker Screenshots and Verification Context',
      disambiguation: 'This chunk is about the Lifetime Tracker Screenshots and Verification Context mechanic itself, not its interactions. It is not a blanket rule that every historical row should keep identical screenshot evidence forever.',
      mechanics: ['Lifetime Tracker Screenshots and Verification Context'],
      tags: ['trackerai', 'lifetime', 'screenshots', 'verification', 'ocr', 'history'],
      paragraphs: [...LIFETIME_TRACKER_SCREENSHOT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_lifetime_leaderboard_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Lifetime Tracker and Leaderboard',
      title: 'Lifetime Tracker and Lifetime Leaderboard',
      disambiguation: 'This chunk is about the Lifetime Tracker and Lifetime Leaderboard mechanic itself, not its interactions. It is not the same thing as tower-run leaderboard publication or guild ranking rules.',
      mechanics: ['Lifetime Tracker and Lifetime Leaderboard'],
      tags: ['trackerai', 'lifetime', 'leaderboard', 'comparison', 'history'],
      paragraphs: [...LIFETIME_TRACKER_LEADERBOARD_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_lifetime_ai_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on Lifetime Tracker',
      title: 'Lifetime Tracker AI Help Coverage',
      disambiguation: 'This chunk is about the Lifetime Tracker AI Help Coverage mechanic itself, not its interactions. It is not a promise that the assistant should bypass edit or sync confirmations.',
      mechanics: ['Lifetime Tracker AI Help Coverage'],
      tags: ['trackerai', 'lifetime', 'ai help', 'ocr', 'charts', 'sync'],
      paragraphs: [...LIFETIME_TRACKER_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_lifetime_faq_overview_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What is the lifetime tracker for?',
      title: 'What is the lifetime tracker for?',
      disambiguation: 'This chunk is about the interaction between the lifetime tracker page and its long-term analysis role, not a single screenshot upload action.',
      mechanics: ['Lifetime Tracker Overview', 'Lifetime Tracker Averages and Charts'],
      tags: ['trackerai', 'lifetime', 'faq', 'overview', 'purpose', 'analysis'],
      interaction_type: 'cross_system',
      interaction_summary: 'Lifetime Tracker Overview and Lifetime Tracker Averages and Charts explain why the page exists as a long-term tracking surface instead of only a place to store one number.',
      paragraphs: [
        'Lifetime Tracker Overview explains that the page is meant for long-term lifetime logging, and Lifetime Tracker Averages and Charts explains how that history turns into readable averages and trend views.',
        'That pairing matters because users often ask whether the page is just a data-entry form, when in practice it is also a review and analysis surface.',
        'The clearest answer is to name those mechanics directly: use Lifetime Tracker Overview for what the page is, then use Lifetime Tracker Averages and Charts for what the saved history becomes once it is on the page.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_lifetime_faq_add_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I add lifetime entries?',
      title: 'How do I add lifetime entries?',
      disambiguation: 'This chunk is about the interaction between screenshot OCR and manual entry on the lifetime tracker page, not a hidden import automation path.',
      mechanics: ['Lifetime Tracker Entry Capture', 'Lifetime Tracker Table and History Management'],
      tags: ['trackerai', 'lifetime', 'faq', 'add entry', 'ocr', 'manual'],
      interaction_type: 'cross_system',
      interaction_summary: 'Lifetime Tracker Entry Capture and Lifetime Tracker Table and History Management explain how users add data first and then manage it as part of their saved lifetime history.',
      paragraphs: [
        'Lifetime Tracker Entry Capture explains the two main inputs, screenshot OCR review and manual entry, while Lifetime Tracker Table and History Management explains what happens after saving: the entry becomes part of the editable history table.',
        'That matters because users usually do not just want to know how to start. They also want to know whether they can fix things later if OCR or typing needs cleanup.',
        'The best answer is to name those mechanics directly: use Lifetime Tracker Entry Capture for adding data, then use Lifetime Tracker Table and History Management for editing, viewing screenshots, or deleting entries later.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_lifetime_faq_ocr_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Do I need to trust OCR blindly?',
      title: 'Do I need to trust OCR blindly?',
      disambiguation: 'This chunk is about the interaction between OCR review and manual correction, not a claim that OCR output should always be accepted as final.',
      mechanics: ['Lifetime Tracker Entry Capture', 'Lifetime Tracker Screenshots and Verification Context'],
      tags: ['trackerai', 'lifetime', 'faq', 'ocr', 'screenshots', 'review'],
      interaction_type: 'conditional',
      interaction_summary: 'Lifetime Tracker Entry Capture and Lifetime Tracker Screenshots and Verification Context explain why screenshot import is review-first and why the screenshot context still matters after saving.',
      paragraphs: [
        'Lifetime Tracker Entry Capture explains that OCR imports are shown in an editable review step instead of being committed without user confirmation, and Lifetime Tracker Screenshots and Verification Context explains why the screenshot itself can still matter later.',
        'That means users can treat OCR as a helper, not as an unquestionable source of truth.',
        'A clean answer should name those mechanics directly: use Lifetime Tracker Entry Capture for the review-and-correct workflow, and use Lifetime Tracker Screenshots and Verification Context when the question shifts to why screenshot-backed context matters after the entry is saved.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_lifetime_faq_chart_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can I compare over time in the lifetime tracker?',
      title: 'What can I compare over time in the lifetime tracker?',
      disambiguation: 'This chunk is about the interaction between lifetime history and the page analysis tools, not a fixed one-chart-only layout.',
      mechanics: ['Lifetime Tracker Table and History Management', 'Lifetime Tracker Averages and Charts'],
      tags: ['trackerai', 'lifetime', 'faq', 'charts', 'averages', 'timeline'],
      interaction_type: 'cross_system',
      interaction_summary: 'Lifetime Tracker Table and History Management and Lifetime Tracker Averages and Charts explain how saved lifetime rows become trend views and period-based summaries.',
      paragraphs: [
        'Lifetime Tracker Table and History Management explains the stored history that feeds the page, and Lifetime Tracker Averages and Charts explains the averages, chart axes, timeline columns, and style controls built on top of that history.',
        'This is the part that turns the page from a log into an analysis tool.',
        'The clearest explanation is to name those mechanics directly: the table provides the history, and Lifetime Tracker Averages and Charts provides the customizable way to read that history over time.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_lifetime_faq_cadence_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How often should I update the lifetime tracker?',
      title: 'How often should I update the lifetime tracker?',
      disambiguation: 'This chunk is about the interaction between lifetime snapshots, averages, and chart interpretation, not a mandatory posting rule.',
      mechanics: ['Lifetime Tracker Table and History Management', 'Lifetime Tracker Averages and Charts', 'Lifetime Tracker Reading Lifetime Progress'],
      tags: ['trackerai', 'lifetime', 'faq', 'cadence', 'snapshots', 'averages'],
      interaction_type: 'conditional',
      interaction_summary: 'Lifetime Tracker Table and History Management, Lifetime Tracker Averages and Charts, and Lifetime Tracker Reading Lifetime Progress explain why steady checkpoints are usually more useful than constant noisy updates.',
      paragraphs: [
        'Lifetime Tracker Table and History Management explains the saved snapshot history, Lifetime Tracker Averages and Charts explains what the page builds from that history, and Lifetime Tracker Reading Lifetime Progress explains why clearer checkpoints usually make that analysis easier to trust.',
        'That means the page does not need constant spam to stay useful. It needs updates that make the direction of progress readable.',
        'The most helpful answer is to name those mechanics directly: use Lifetime Tracker Reading Lifetime Progress for the quality-of-history guidance, and use Lifetime Tracker Averages and Charts for why that guidance matters on the page.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_lifetime_faq_average_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why do my lifetime averages look strange?',
      title: 'Why do my lifetime averages look strange?',
      disambiguation: 'This chunk is about the interaction between the latest lifetime entry, the recorded game-start date, and the page interpretation layer, not a hidden formula bug.',
      mechanics: ['Lifetime Tracker Entry Capture', 'Lifetime Tracker Averages and Charts', 'Lifetime Tracker Reading Lifetime Progress'],
      tags: ['trackerai', 'lifetime', 'faq', 'averages', 'game started', 'interpretation'],
      interaction_type: 'conditional',
      interaction_summary: 'Lifetime Tracker Entry Capture, Lifetime Tracker Averages and Charts, and Lifetime Tracker Reading Lifetime Progress explain why odd averages usually come from the saved inputs and snapshot history rather than from mystery math.',
      paragraphs: [
        'Lifetime Tracker Entry Capture covers the saved values the page is relying on, Lifetime Tracker Averages and Charts explains that the latest entry and recorded game-start date drive the average cards, and Lifetime Tracker Reading Lifetime Progress explains how uneven snapshots can skew how those numbers feel.',
        'That is why strange averages are often an input-history question before they are a page bug question.',
        'The clearest answer is to name those mechanics directly: check Lifetime Tracker Entry Capture first, then use Lifetime Tracker Averages and Charts and Lifetime Tracker Reading Lifetime Progress to explain how the page is interpreting those saved totals.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_lifetime_faq_sync_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Does the lifetime tracker save and sync?',
      title: 'Does the lifetime tracker save and sync?',
      disambiguation: 'This chunk is about the interaction between lifetime local storage and lifetime cloud sync, not a promise that sync never needs conflict resolution.',
      mechanics: ['Lifetime Tracker Overview', 'Lifetime Tracker Local Save and Cloud Sync'],
      tags: ['trackerai', 'lifetime', 'faq', 'save', 'sync', 'cloud'],
      interaction_type: 'conditional',
      interaction_summary: 'Lifetime Tracker Overview and Lifetime Tracker Local Save and Cloud Sync explain how the page can remain usable locally while still supporting signed-in cloud continuity.',
      paragraphs: [
        'Lifetime Tracker Overview gives the page context, and Lifetime Tracker Local Save and Cloud Sync explains the practical behavior: local-first storage, optional cloud load and save, and conflict-aware sync prompts when needed.',
        'That answer matters because many users really mean two separate questions when they ask whether the page saves: will my data stay here locally, and can it follow my account too?',
        'The best response is to name those mechanics directly: Lifetime Tracker Local Save and Cloud Sync covers both the local and cloud side of the page behavior.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_lifetime_faq_leaderboard_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How does the lifetime tracker connect to leaderboard?',
      title: 'How does the lifetime tracker connect to leaderboard?',
      disambiguation: 'This chunk is about the interaction between the lifetime tracker page and the lifetime leaderboard mode, not the tower-run leaderboard path.',
      mechanics: ['Lifetime Tracker and Lifetime Leaderboard', 'Leaderboard Modes and Tiers', 'Leaderboard Lifetime Stats View'],
      tags: ['trackerai', 'lifetime', 'faq', 'leaderboard', 'comparison', 'metrics'],
      interaction_type: 'cross_system',
      interaction_summary: 'Lifetime Tracker and Lifetime Leaderboard, Leaderboard Modes and Tiers, and Leaderboard Lifetime Stats View explain how the lifetime tracker feeds into a separate shared comparison view on the leaderboard page.',
      paragraphs: [
        'Lifetime Tracker and Lifetime Leaderboard explains the division of roles, Leaderboard Modes and Tiers explains where users switch into the lifetime leaderboard mode, and Leaderboard Lifetime Stats View explains the lifetime metrics visible once they get there.',
        'This bridge matters because the tracker page and leaderboard page are closely related without being the same feature surface.',
        'A useful answer should name those mechanics directly: maintain the data through Lifetime Tracker and Lifetime Leaderboard, switch views through Leaderboard Modes and Tiers, and read the comparison table through Leaderboard Lifetime Stats View.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_lifetime_faq_verified_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why does one lifetime entry have screenshot context but older ones do not?',
      title: 'Why does one lifetime entry have screenshot context but older ones do not?',
      disambiguation: 'This chunk is about the interaction between lifetime screenshot handling, sync behavior, and lifetime leaderboard comparison, not a bug placeholder.',
      mechanics: ['Lifetime Tracker Screenshots and Verification Context', 'Lifetime Tracker Local Save and Cloud Sync', 'Leaderboard Lifetime Stats View'],
      tags: ['trackerai', 'lifetime', 'faq', 'screenshots', 'verification', 'leaderboard'],
      interaction_type: 'conditional',
      interaction_summary: 'Lifetime Tracker Screenshots and Verification Context, Lifetime Tracker Local Save and Cloud Sync, and Leaderboard Lifetime Stats View explain why screenshot-backed context is strongest around the current synced lifetime evidence rather than every historical row equally.',
      paragraphs: [
        'Lifetime Tracker Screenshots and Verification Context explains the rule, Lifetime Tracker Local Save and Cloud Sync explains when that handling happens, and Leaderboard Lifetime Stats View explains why users usually notice the difference when they are thinking about comparison or proof.',
        'That means the difference is usually by design, not random row damage.',
        'The clearest answer is to name those mechanics directly: use Lifetime Tracker Screenshots and Verification Context for the screenshot rule, then use Lifetime Tracker Local Save and Cloud Sync for when it applies.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_lifetime_faq_ai_01',
      source: 'Lifetime Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do on the lifetime tracker?',
      title: 'What can TrackerAI help me do on the lifetime tracker?',
      disambiguation: 'This chunk is about the interaction between lifetime page knowledge and TrackerAI help boundaries, not unrestricted edit or sync automation.',
      mechanics: ['Lifetime Tracker Overview', 'Lifetime Tracker Entry Capture', 'Lifetime Tracker Averages and Charts', 'Lifetime Tracker Local Save and Cloud Sync', 'Lifetime Tracker AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'lifetime', 'faq', 'ai help', 'ocr', 'charts', 'sync'],
      interaction_type: 'conditional',
      interaction_summary: 'Lifetime Tracker Overview, Lifetime Tracker Entry Capture, Lifetime Tracker Averages and Charts, Lifetime Tracker Local Save and Cloud Sync, Lifetime Tracker AI Help Coverage, and TrackerAI Safety Guardrails define where the assistant is useful on the lifetime page and where it should still stay inside the normal page flows.',
      paragraphs: [
        'Lifetime Tracker Overview gives the page context, Lifetime Tracker Entry Capture covers OCR and manual-entry questions, Lifetime Tracker Averages and Charts covers analysis questions, and Lifetime Tracker Local Save and Cloud Sync covers the save-and-sync side of the tracker.',
        'Lifetime Tracker AI Help Coverage explains why those are strong assistant tasks for normal users, especially when they are trying to understand what to add, what to trust, or what a chart or leaderboard connection means.',
        'TrackerAI Safety Guardrails is the boundary that keeps the answer honest: the assistant can explain, guide, and interpret clearly without pretending it should bypass edit confirmations or sync decisions automatically.',
      ],
    }),
  ]
}
