import {
  GUARDIANS_CALCULATOR_CHIPS_FACTS,
  GUARDIANS_CALCULATOR_OVERVIEW_FACTS,
  GUARDIANS_CALCULATOR_PATH_FACTS,
  GUARDIANS_CALCULATOR_STATE_FACTS,
  GUARDIANS_TRACKER_AI_FACTS,
  GUARDIANS_TRACKER_CALCULATOR_LINK_FACTS,
  GUARDIANS_TRACKER_OVERVIEW_FACTS,
  GUARDIANS_TRACKER_OVERVIEW_TAB_FACTS,
  GUARDIANS_TRACKER_PROGRESS_FACTS,
  GUARDIANS_TRACKER_SYNC_FACTS,
} from './trackerAiGuardiansSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiGuardiansCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_guardians_overview_01',
      source: 'Guardians Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Guardians Tracker',
      title: 'Guardians Tracker Overview',
      disambiguation: 'This chunk describes the Guardians Tracker Overview mechanic itself, not its interactions. It is not the general guardian encyclopedia or the standalone calculator tables by themselves.',
      mechanics: ['Guardians Tracker Overview'],
      tags: ['trackerai', 'guardians', 'tracker', 'site page', 'overview'],
      paragraphs: [...GUARDIANS_TRACKER_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_guardians_progress_01',
      source: 'Guardians Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Progress Planning Table',
      title: 'Guardians Tracker Progress Planning Table',
      disambiguation: 'This chunk describes the Guardians Tracker Progress Planning Table mechanic itself, not its interactions. It is not the preset overview tab or the deeper calculator workspace.',
      mechanics: ['Guardians Tracker Progress Planning Table'],
      tags: ['trackerai', 'guardians', 'tracker', 'progress', 'bits', 'columns'],
      paragraphs: [...GUARDIANS_TRACKER_PROGRESS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_guardians_overview_tab_01',
      source: 'Guardians Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'All Guardians Tab',
      title: 'Guardians Tracker All Guardians Tab',
      disambiguation: 'This chunk describes the Guardians Tracker All Guardians Tab mechanic itself, not its interactions. It is not the progress table or the calculator output tables.',
      mechanics: ['Guardians Tracker All Guardians Tab'],
      tags: ['trackerai', 'guardians', 'tracker', 'overview', 'presets', 'disabled'],
      paragraphs: [...GUARDIANS_TRACKER_OVERVIEW_TAB_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_guardians_sync_01',
      source: 'Guardians Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Local Save and Sync',
      title: 'Guardians Tracker Local Save and Sync',
      disambiguation: 'This chunk describes the Guardians Tracker Local Save and Sync mechanic itself, not its interactions. It is not a low-level sync protocol dump.',
      mechanics: ['Guardians Tracker Local Save and Sync'],
      tags: ['trackerai', 'guardians', 'tracker', 'sync', 'local save', 'cloud'],
      paragraphs: [...GUARDIANS_TRACKER_SYNC_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_guardians_calculator_overview_01',
      source: 'Guardians Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Guardians Calculator Workspace',
      title: 'Guardians Calculator Workspace Overview',
      disambiguation: 'This chunk describes the Guardians Calculator Workspace Overview mechanic itself, not its interactions. It is not the tracker page or a generic guardian wiki summary.',
      mechanics: ['Guardians Calculator Workspace Overview'],
      tags: ['trackerai', 'guardians', 'calculator', 'site page', 'overview'],
      paragraphs: [...GUARDIANS_CALCULATOR_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_guardians_calculator_chips_01',
      source: 'Guardians Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Chips Mode',
      title: 'Guardians Calculator Chips Mode',
      disambiguation: 'This chunk describes the Guardians Calculator Chips Mode mechanic itself, not its interactions. It is not the effective-path planner or the tracker progress table.',
      mechanics: ['Guardians Calculator Chips Mode'],
      tags: ['trackerai', 'guardians', 'calculator', 'chips', 'bits', 'levels'],
      paragraphs: [...GUARDIANS_CALCULATOR_CHIPS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_guardians_calculator_paths_01',
      source: 'Guardians Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Effective Paths Mode',
      title: 'Guardians Calculator Effective Paths Mode',
      disambiguation: 'This chunk describes the Guardians Calculator Effective Paths Mode mechanic itself, not its interactions. It is not the chips table or a generic optimizer outside this page.',
      mechanics: ['Guardians Calculator Effective Paths Mode'],
      tags: ['trackerai', 'guardians', 'calculator', 'effective paths', 'roi', 'steps'],
      paragraphs: [...GUARDIANS_CALCULATOR_PATH_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_guardians_calculator_state_01',
      source: 'Guardians Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Shared Calculator State',
      title: 'Guardians Calculator Shared State',
      disambiguation: 'This chunk describes the Guardians Calculator Shared State mechanic itself, not its interactions. It is not a cloud-sync explanation or a claim that every guardian stat is globally shared across unrelated tools.',
      mechanics: ['Guardians Calculator Shared State'],
      tags: ['trackerai', 'guardians', 'calculator', 'shared state', 'tracker defaults', 'tabs'],
      paragraphs: [...GUARDIANS_CALCULATOR_STATE_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_guardians_link_01',
      source: 'Guardians Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Tracker and Calculator Link',
      title: 'Guardians Tracker and Calculator Link',
      disambiguation: 'This chunk describes the Guardians Tracker and Calculator Link mechanic itself, not its interactions. It is not a claim that the tracker and calculator are identical views.',
      mechanics: ['Guardians Tracker and Calculator Link'],
      tags: ['trackerai', 'guardians', 'tracker', 'calculator', 'shared context'],
      paragraphs: [...GUARDIANS_TRACKER_CALCULATOR_LINK_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_guardians_ai_01',
      source: 'Guardians Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on Guardian Pages',
      title: 'Guardians Tracker and Calculator AI Help Coverage',
      disambiguation: 'This chunk describes the Guardians Tracker and Calculator AI Help Coverage mechanic itself, not its interactions. It is not unrestricted bulk editing or silent resets.',
      mechanics: ['Guardians Tracker and Calculator AI Help Coverage'],
      tags: ['trackerai', 'guardians', 'ai help', 'tracker', 'calculator'],
      paragraphs: [...GUARDIANS_TRACKER_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_guardians_faq_use_01',
      source: 'Guardians Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I use the Guardians tracker page?',
      title: 'How do I use the Guardians tracker page?',
      disambiguation: 'This chunk is about the interaction between the main Guardians tracker tabs, not the deeper game meaning of individual guardian mechanics.',
      mechanics: ['Guardians Tracker Overview', 'Guardians Tracker Progress Planning Table', 'Guardians Tracker All Guardians Tab', 'Guardians Tracker and Calculator Link'],
      tags: ['trackerai', 'guardians', 'faq', 'tracker', 'tabs', 'workflow'],
      interaction_type: 'cross_system',
      interaction_summary: 'Guardians Tracker Overview, Guardians Tracker Progress Planning Table, Guardians Tracker All Guardians Tab, and Guardians Tracker and Calculator Link explain how the page splits saved progress planning, preset-level guardian control, and calculator handoff into separate surfaces.',
      paragraphs: [
        'Guardians Tracker Overview explains the page as a whole, Guardians Tracker Progress Planning Table explains the main planning table, Guardians Tracker All Guardians Tab explains the preset-level guardian board, and Guardians Tracker and Calculator Link explains how the calculator fits into that workflow.',
        'That matters because users often know the guardian they want to change before they know which tab owns the right action.',
        'The clearest answer is to name those mechanics directly: use Progress for current and target planning, use All Guardians for preset-wide guardian enablement and quick level editing, and use the calculator link when the question becomes deeper guardian math.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_guardians_faq_disabled_01',
      source: 'Guardians Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What happens when a guardian is disabled in the tracker?',
      title: 'What happens when a guardian is disabled in the tracker?',
      disambiguation: 'This chunk is about the interaction between tracker presets and progress visibility, not a claim that the guardian is deleted from the account.',
      mechanics: ['Guardians Tracker Progress Planning Table', 'Guardians Tracker All Guardians Tab'],
      tags: ['trackerai', 'guardians', 'faq', 'disabled', 'presets', 'progress'],
      interaction_type: 'conditional',
      interaction_summary: 'Guardians Tracker Progress Planning Table and Guardians Tracker All Guardians Tab explain why disabling a guardian marks it inactive for that preset instead of deleting its definition from the tool.',
      paragraphs: [
        'Guardians Tracker All Guardians Tab is where guardians are enabled or disabled per preset, and Guardians Tracker Progress Planning Table is where disabled guardians are treated as inactive rows with their calculator shortcut blocked.',
        'That is why disabling a guardian changes how it appears in the workspace without acting like a destructive removal of guardian data from the site.',
        'The clearest answer is to name those mechanics directly: disabling a guardian marks it inactive for the current preset and removes it from the main progress workflow until it is re-enabled.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_guardians_faq_bits_01',
      source: 'Guardians Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What does average bits per week affect on the Guardians tracker?',
      title: 'What does average bits per week affect on the Guardians tracker?',
      disambiguation: 'This chunk is about the interaction between the guardian progress table and its time-oriented outputs, not a universal bit-income formula outside the tracker.',
      mechanics: ['Guardians Tracker Overview', 'Guardians Tracker Progress Planning Table'],
      tags: ['trackerai', 'guardians', 'faq', 'bits per week', 'finish date', 'time'],
      interaction_type: 'conditional',
      interaction_summary: 'Guardians Tracker Overview and Guardians Tracker Progress Planning Table explain why the tracker asks for a saved bits-per-week pace when showing weeks, time, and finish-date outputs.',
      paragraphs: [
        'Guardians Tracker Overview explains the page context, and Guardians Tracker Progress Planning Table explains that the guardian table can show remaining bits, weeks to target or max, time to target, and estimated finish dates.',
        'Those outputs only make sense when they are tied to the pace the user actually expects, not one fixed site-wide assumption.',
        'The clearest answer is to name that mechanic directly: average bits per week personalizes the guardian progress table\'s time-based planning columns.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_guardians_faq_tracker_vs_calc_01',
      source: 'Guardians Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What is the difference between the Guardians tracker and calculator?',
      title: 'What is the difference between the Guardians tracker and calculator?',
      disambiguation: 'This chunk is about the interaction between the Guardians tracker and calculator, not a claim that one replaces the other.',
      mechanics: ['Guardians Tracker Overview', 'Guardians Calculator Workspace Overview', 'Guardians Tracker and Calculator Link'],
      tags: ['trackerai', 'guardians', 'faq', 'tracker', 'calculator', 'difference'],
      interaction_type: 'cross_system',
      interaction_summary: 'Guardians Tracker Overview, Guardians Calculator Workspace Overview, and Guardians Tracker and Calculator Link explain why one surface manages saved guardian progress and presets while the other focuses on bit tables and effective upgrade paths.',
      paragraphs: [
        'Guardians Tracker Overview explains the broader saved workspace, Guardians Calculator Workspace Overview explains the two-mode calculator workspace, and Guardians Tracker and Calculator Link explains how the two surfaces stay connected.',
        'That relationship is the practical answer for users who want to know where to start.',
        'The clearest answer is to name those mechanics directly: use the tracker for saved guardian progress and preset state, use the calculator for chip tables and effective-path math, and use the shared-link mechanic for how they hand context to each other.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_guardians_faq_calc_modes_01',
      source: 'Guardians Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Which Guardians calculator mode should I use?',
      title: 'Which Guardians calculator mode should I use?',
      disambiguation: 'This chunk is about the interaction between the guardians calculator modes, not a claim that Chips and Effective Paths answer the same question.',
      mechanics: ['Guardians Calculator Workspace Overview', 'Guardians Calculator Chips Mode', 'Guardians Calculator Effective Paths Mode'],
      tags: ['trackerai', 'guardians', 'faq', 'calculator', 'chips', 'effective paths'],
      interaction_type: 'cross_system',
      interaction_summary: 'Guardians Calculator Workspace Overview, Guardians Calculator Chips Mode, and Guardians Calculator Effective Paths Mode explain how the guardians calculator splits direct bit-table planning from ordered upgrade-path analysis.',
      paragraphs: [
        'Guardians Calculator Workspace Overview explains the two-mode workspace, Guardians Calculator Chips Mode covers the direct stat-and-cost tables, and Guardians Calculator Effective Paths Mode covers the ordered ROI path output.',
        'That matters because users often know they need guardian math but are not sure whether they want a static cost ladder or a recommended step sequence.',
        'The clearest answer is to name those mechanics directly: use Chips for level tables and raw bit costs, and use Effective Paths when the goal is a recommended upgrade order.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_guardians_faq_handoff_01',
      source: 'Guardians Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What does Open in Calculator do on the Guardians tracker?',
      title: 'What does Open in Calculator do on the Guardians tracker?',
      disambiguation: 'This chunk is about the interaction between guardian progress rows and calculator state, not a claim that it performs a destructive sync or overwrites unrelated guardian setups.',
      mechanics: ['Guardians Tracker Progress Planning Table', 'Guardians Calculator Shared State', 'Guardians Tracker and Calculator Link'],
      tags: ['trackerai', 'guardians', 'faq', 'open in calculator', 'handoff', 'shared state'],
      interaction_type: 'conditional',
      interaction_summary: 'Guardians Tracker Progress Planning Table, Guardians Calculator Shared State, and Guardians Tracker and Calculator Link explain why the tracker can hand a selected guardian directly into calculator context.',
      paragraphs: [
        'Guardians Tracker Progress Planning Table explains where the Open in Calculator action lives, Guardians Calculator Shared State explains that calculator inputs are tied to saved guardian context, and Guardians Tracker and Calculator Link explains that the tracker embeds the same calculator workspace.',
        'That is why the action can switch the user into calculator mode with the chosen guardian already selected and its saved start and target levels already prepared.',
        'The clearest answer is to name those mechanics directly: Open in Calculator hands the selected guardian\'s saved tracker context into the guardians calculator so the user can continue the same planning session there.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_guardians_faq_ai_01',
      source: 'Guardians Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do with the Guardians tracker and calculator?',
      title: 'What can TrackerAI help me do with the Guardians tracker and calculator?',
      disambiguation: 'This chunk is about the interaction between guardians page knowledge and TrackerAI help boundaries, not unrestricted bulk edits or silent resets.',
      mechanics: ['Guardians Tracker Overview', 'Guardians Calculator Workspace Overview', 'Guardians Tracker and Calculator AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'guardians', 'faq', 'ai help', 'tracker', 'calculator'],
      interaction_type: 'conditional',
      interaction_summary: 'Guardians Tracker Overview, Guardians Calculator Workspace Overview, Guardians Tracker and Calculator AI Help Coverage, and TrackerAI Safety Guardrails define the kinds of guardian-tool help the assistant can give without pretending it should silently rewrite saved progress.',
      paragraphs: [
        'Guardians Tracker Overview and Guardians Calculator Workspace Overview provide the page context, and Guardians Tracker and Calculator AI Help Coverage explains why this is a strong explanation-and-guidance area for the assistant.',
        'This is where TrackerAI is most useful for normal users: clarifying which tab or mode to use, explaining progress columns and effective-path outputs, and helping interpret the saved guardian planning state.',
        'TrackerAI Safety Guardrails is the boundary that keeps that help honest, because explanation and interpretation are different from silently resetting guardian progress, toggling disabled state, or forcing a sync decision on the user\'s behalf.',
      ],
    }),
  ]
}
