import {
  THORNS_CALCULATOR_AI_FACTS,
  THORNS_CALCULATOR_COMPARISON_FACTS,
  THORNS_CALCULATOR_INPUT_FACTS,
  THORNS_CALCULATOR_OVERVIEW_FACTS,
  THORNS_CALCULATOR_PERSISTENCE_FACTS,
  THORNS_CALCULATOR_RESULTS_FACTS,
  THORNS_CALCULATOR_RULES_FACTS,
  THORNS_CALCULATOR_SUMMARY_FACTS,
} from './trackerAiThornsSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiThornsCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_thorns_overview_01',
      source: 'Thorns Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Thorns Calculator Workspace',
      title: 'Thorns Calculator Workspace Overview',
      disambiguation: 'This chunk describes the Thorns Calculator Workspace Overview mechanic itself, not its interactions. It is not the general thorns mechanic encyclopedia or a combat guide outside the page.',
      mechanics: ['Thorns Calculator Workspace Overview'],
      tags: ['trackerai', 'thorns', 'calculator', 'site page', 'overview'],
      paragraphs: [...THORNS_CALCULATOR_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_thorns_inputs_01',
      source: 'Thorns Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Main Inputs',
      title: 'Thorns Calculator Main Inputs',
      disambiguation: 'This chunk describes the Thorns Calculator Main Inputs mechanic itself, not its interactions. It is not the comparison panel or the output tables.',
      mechanics: ['Thorns Calculator Main Inputs'],
      tags: ['trackerai', 'thorns', 'calculator', 'inputs', 'plasma cannon', 'heat'],
      paragraphs: [...THORNS_CALCULATOR_INPUT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_thorns_rules_01',
      source: 'Thorns Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Input Guardrails',
      title: 'Thorns Calculator Input Guardrails',
      disambiguation: 'This chunk describes the Thorns Calculator Input Guardrails mechanic itself, not its interactions. It is not a hidden formula dump.',
      mechanics: ['Thorns Calculator Input Guardrails'],
      tags: ['trackerai', 'thorns', 'calculator', 'guardrails', 'plasma cannon'],
      paragraphs: [...THORNS_CALCULATOR_RULES_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_thorns_comparison_01',
      source: 'Thorns Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Comparison Scenario',
      title: 'Thorns Calculator Comparison Scenario',
      disambiguation: 'This chunk describes the Thorns Calculator Comparison Scenario mechanic itself, not its interactions. It is not a duplicate of the main input card.',
      mechanics: ['Thorns Calculator Comparison Scenario'],
      tags: ['trackerai', 'thorns', 'calculator', 'comparison', 'scenario'],
      paragraphs: [...THORNS_CALCULATOR_COMPARISON_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_thorns_results_01',
      source: 'Thorns Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Dual Results Tables',
      title: 'Thorns Calculator Dual Results Tables',
      disambiguation: 'This chunk describes the Thorns Calculator Dual Results Tables mechanic itself, not its interactions. It is not the input form or comparison panel by itself.',
      mechanics: ['Thorns Calculator Dual Results Tables'],
      tags: ['trackerai', 'thorns', 'calculator', 'results', 'tables', 'wall thorns'],
      paragraphs: [...THORNS_CALCULATOR_RESULTS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_thorns_summary_01',
      source: 'Thorns Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Scenario Summary Chips',
      title: 'Thorns Calculator Scenario Summary Chips',
      disambiguation: 'This chunk describes the Thorns Calculator Scenario Summary Chips mechanic itself, not its interactions. It is not a separate results table.',
      mechanics: ['Thorns Calculator Scenario Summary Chips'],
      tags: ['trackerai', 'thorns', 'calculator', 'summary', 'comparison'],
      paragraphs: [...THORNS_CALCULATOR_SUMMARY_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_thorns_persistence_01',
      source: 'Thorns Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Saved Thorns State',
      title: 'Thorns Calculator Saved State',
      disambiguation: 'This chunk describes the Thorns Calculator Saved State mechanic itself, not its interactions. It is not a cloud-sync contract.',
      mechanics: ['Thorns Calculator Saved State'],
      tags: ['trackerai', 'thorns', 'calculator', 'saved state', 'dexie', 'local'],
      paragraphs: [...THORNS_CALCULATOR_PERSISTENCE_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_thorns_ai_01',
      source: 'Thorns Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on Thorns Calculator',
      title: 'Thorns Calculator AI Help Coverage',
      disambiguation: 'This chunk describes the Thorns Calculator AI Help Coverage mechanic itself, not its interactions. It is not unrestricted silent editing of saved scenarios.',
      mechanics: ['Thorns Calculator AI Help Coverage'],
      tags: ['trackerai', 'thorns', 'calculator', 'ai help'],
      paragraphs: [...THORNS_CALCULATOR_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_thorns_faq_use_01',
      source: 'Thorns Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I use the Thorns calculator?',
      title: 'How do I use the Thorns calculator?',
      disambiguation: 'This chunk is about the interaction between the main thorns calculator surfaces, not the deeper combat theory outside the page.',
      mechanics: ['Thorns Calculator Workspace Overview', 'Thorns Calculator Main Inputs', 'Thorns Calculator Dual Results Tables'],
      tags: ['trackerai', 'thorns', 'faq', 'calculator', 'workflow'],
      interaction_type: 'cross_system',
      interaction_summary: 'Thorns Calculator Workspace Overview, Thorns Calculator Main Inputs, and Thorns Calculator Dual Results Tables explain how the page moves from one modeled setup into lookup-style hit-to-kill tables.',
      paragraphs: [
        'Thorns Calculator Workspace Overview explains the page as a whole, Thorns Calculator Main Inputs explains how the scenario is built, and Thorns Calculator Dual Results Tables explains the two output tables.',
        'That matters because users often know they want a kill-hit answer without yet knowing why the page shows two related but different tables.',
        'The clearest answer is to name those mechanics directly: set up the thorn and plasma cannon scenario in the main inputs, then read the base-thorns and wall-thorns tables together to see the relevant hit counts.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_thorns_faq_compare_01',
      source: 'Thorns Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How does the comparison panel work on the Thorns calculator?',
      title: 'How does the comparison panel work on the Thorns calculator?',
      disambiguation: 'This chunk is about the interaction between the main and comparison scenarios, not a claim that the page stores only one thorns model.',
      mechanics: ['Thorns Calculator Comparison Scenario', 'Thorns Calculator Dual Results Tables', 'Thorns Calculator Scenario Summary Chips'],
      tags: ['trackerai', 'thorns', 'faq', 'comparison', 'scenario'],
      interaction_type: 'cross_system',
      interaction_summary: 'Thorns Calculator Comparison Scenario, Thorns Calculator Dual Results Tables, and Thorns Calculator Scenario Summary Chips explain how the calculator keeps two setups visible at once without leaving the page.',
      paragraphs: [
        'Thorns Calculator Comparison Scenario explains the second modeled setup, Thorns Calculator Dual Results Tables explains how comparison values appear in the result cells, and Thorns Calculator Scenario Summary Chips explains how both assumptions stay readable.',
        'That is why the comparison workflow feels like branching the current model rather than replacing it.',
        'The clearest answer is to name those mechanics directly: the comparison panel holds a second thorns setup, can reset itself back to the main scenario, and then overlays the alternative hit-to-kill results beside the main values.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_thorns_faq_pc_mastery_01',
      source: 'Thorns Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why does Plasma Cannon Mastery change my Plasma Cannon level?',
      title: 'Why does Plasma Cannon Mastery change my Plasma Cannon level?',
      disambiguation: 'This chunk is about the interaction between Plasma Cannon and Plasma Cannon Mastery in the calculator state, not a game-design argument about whether that dependency should exist.',
      mechanics: ['Thorns Calculator Main Inputs', 'Thorns Calculator Input Guardrails'],
      tags: ['trackerai', 'thorns', 'faq', 'plasma cannon', 'mastery', 'guardrails'],
      interaction_type: 'conditional',
      interaction_summary: 'Thorns Calculator Main Inputs and Thorns Calculator Input Guardrails explain why mastery and base Plasma Cannon levels are normalized together inside the page.',
      paragraphs: [
        'Thorns Calculator Main Inputs explains where Plasma Cannon and mastery are configured, and Thorns Calculator Input Guardrails explains that the page keeps those fields in a valid relationship.',
        'That is why increasing mastery can force Plasma Cannon to max, and lowering Plasma Cannon can remove an incompatible mastery state.',
        'The clearest answer is to name those mechanics directly: the calculator treats Plasma Cannon Mastery as dependent on a maxed Plasma Cannon setup and normalizes the stored values accordingly.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_thorns_faq_saved_01',
      source: 'Thorns Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What does the Thorns calculator remember between visits?',
      title: 'What does the Thorns calculator remember between visits?',
      disambiguation: 'This chunk is about the interaction between saved main scenario state, saved comparison state, and the comparison panel open state, not a cloud-sync guarantee.',
      mechanics: ['Thorns Calculator Saved State', 'Thorns Calculator Comparison Scenario'],
      tags: ['trackerai', 'thorns', 'faq', 'saved state', 'comparison'],
      interaction_type: 'cross_system',
      interaction_summary: 'Thorns Calculator Saved State and Thorns Calculator Comparison Scenario explain why the page can restore both scenarios and the comparison workflow itself after a revisit.',
      paragraphs: [
        'Thorns Calculator Saved State explains the persisted local storage for the tool, and Thorns Calculator Comparison Scenario explains that the page keeps a second setup alongside the primary one.',
        'That means coming back to the route can restore more than a single thorns percentage field.',
        'The clearest answer is to name those mechanics directly: the thorns calculator remembers both the main and comparison scenarios and whether the comparison panel was open.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_thorns_faq_ai_01',
      source: 'Thorns Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do with the Thorns calculator?',
      title: 'What can TrackerAI help me do with the Thorns calculator?',
      disambiguation: 'This chunk is about the interaction between thorns-calculator page knowledge and TrackerAI help boundaries, not unrestricted silent editing of saved calculator scenarios.',
      mechanics: ['Thorns Calculator Workspace Overview', 'Thorns Calculator AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'thorns', 'faq', 'ai help', 'calculator'],
      interaction_type: 'conditional',
      interaction_summary: 'Thorns Calculator Workspace Overview, Thorns Calculator AI Help Coverage, and TrackerAI Safety Guardrails define the kinds of thorns-calculator help the assistant can give without pretending it should silently rewrite stored comparison scenarios.',
      paragraphs: [
        'Thorns Calculator Workspace Overview provides the page context, and Thorns Calculator AI Help Coverage explains why this calculator is a strong fit for explanation and scenario-guidance help.',
        'This is where TrackerAI is most useful for normal users: clarifying which fields change the modeled setup, explaining the difference between base-thorns and wall-thorns results, and helping interpret a comparison scenario.',
        'TrackerAI Safety Guardrails is the boundary that keeps that help honest, because guidance and explanation are different from silently resetting or rewriting the user\'s saved thorns scenarios.',
      ],
    }),
  ]
}
