import {
  DOWNLOADS_PAGE_AI_FACTS,
  DOWNLOADS_PAGE_BOTS_FACTS,
  DOWNLOADS_PAGE_DAEMON_FACTS,
  DOWNLOADS_PAGE_DESKTOP_FACTS,
  DOWNLOADS_PAGE_EDITION_FACTS,
  DOWNLOADS_PAGE_MOBILE_FACTS,
  DOWNLOADS_PAGE_OVERVIEW_FACTS,
  DOWNLOADS_PAGE_UI_FACTS,
} from './trackerAiDownloadsSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiDownloadsCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_downloads_overview_01',
      source: 'Downloads Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Downloads Page Overview',
      title: 'Downloads Page Overview',
      disambiguation: 'This chunk describes the Downloads Page Overview mechanic itself, not its interactions. It is not a backend release-engineering document or a full device-support matrix outside the page.',
      mechanics: ['Downloads Page Overview'],
      tags: ['trackerai', 'downloads', 'page', 'overview'],
      paragraphs: [...DOWNLOADS_PAGE_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_downloads_desktop_01',
      source: 'Downloads Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Desktop App Downloads',
      title: 'Downloads Page Desktop App Downloads',
      disambiguation: 'This chunk describes the Downloads Page Desktop App Downloads mechanic itself, not its interactions. It is not the standalone daemon package section.',
      mechanics: ['Downloads Page Desktop App Downloads'],
      tags: ['trackerai', 'downloads', 'desktop', 'windows', 'macos', 'linux'],
      paragraphs: [...DOWNLOADS_PAGE_DESKTOP_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_downloads_daemon_01',
      source: 'Downloads Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Daemon Downloads',
      title: 'Downloads Page Daemon Downloads',
      disambiguation: 'This chunk describes the Downloads Page Daemon Downloads mechanic itself, not its interactions. It is not the full desktop app shell or a generic daemon architecture article.',
      mechanics: ['Downloads Page Daemon Downloads'],
      tags: ['trackerai', 'downloads', 'daemon', 'catt daemon', 'mcp bridge', 'tray'],
      paragraphs: [...DOWNLOADS_PAGE_DAEMON_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_downloads_mobile_01',
      source: 'Downloads Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Mobile Downloads',
      title: 'Downloads Page Mobile Downloads',
      disambiguation: 'This chunk describes the Downloads Page Mobile Downloads mechanic itself, not its interactions. It is not the desktop installer path or a mobile feature-comparison article.',
      mechanics: ['Downloads Page Mobile Downloads'],
      tags: ['trackerai', 'downloads', 'mobile', 'android', 'ios'],
      paragraphs: [...DOWNLOADS_PAGE_MOBILE_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_downloads_bots_01',
      source: 'Downloads Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Discord Bot Access',
      title: 'Downloads Page Discord Bot Access',
      disambiguation: 'This chunk describes the Downloads Page Discord Bot Access mechanic itself, not its interactions. It is not a download of executable binaries.',
      mechanics: ['Downloads Page Discord Bot Access'],
      tags: ['trackerai', 'downloads', 'discord bots', 'tracker bot', 'tools bot'],
      paragraphs: [...DOWNLOADS_PAGE_BOTS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_downloads_editions_01',
      source: 'Downloads Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Edition Selection',
      title: 'Downloads Page Edition Selection',
      disambiguation: 'This chunk describes the Downloads Page Edition Selection mechanic itself, not its interactions. It is not a promise that all editions behave identically after install.',
      mechanics: ['Downloads Page Edition Selection'],
      tags: ['trackerai', 'downloads', 'editions', 'lite', 'standard', 'pro'],
      paragraphs: [...DOWNLOADS_PAGE_EDITION_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_downloads_ui_01',
      source: 'Downloads Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Copy Helper UI',
      title: 'Downloads Page Copy Helper UI',
      disambiguation: 'This chunk describes the Downloads Page Copy Helper UI mechanic itself, not its interactions. It is not a full installer workflow by itself.',
      mechanics: ['Downloads Page Copy Helper UI'],
      tags: ['trackerai', 'downloads', 'copy', 'ui', 'snackbar'],
      paragraphs: [...DOWNLOADS_PAGE_UI_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_downloads_ai_01',
      source: 'Downloads Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on Downloads Page',
      title: 'Downloads Page AI Help Coverage',
      disambiguation: 'This chunk describes the Downloads Page AI Help Coverage mechanic itself, not its interactions. It is not silent installation automation.',
      mechanics: ['Downloads Page AI Help Coverage'],
      tags: ['trackerai', 'downloads', 'ai help'],
      paragraphs: [...DOWNLOADS_PAGE_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_downloads_faq_use_01',
      source: 'Downloads Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I use the downloads page?',
      title: 'How do I use the downloads page?',
      disambiguation: 'This chunk is about the interaction between the main downloads page sections, not a generic app-install guide outside the route.',
      mechanics: ['Downloads Page Overview', 'Downloads Page Desktop App Downloads', 'Downloads Page Daemon Downloads', 'Downloads Page Mobile Downloads', 'Downloads Page Discord Bot Access'],
      tags: ['trackerai', 'downloads', 'faq', 'workflow'],
      interaction_type: 'cross_system',
      interaction_summary: 'Downloads Page Overview, Downloads Page Desktop App Downloads, Downloads Page Daemon Downloads, Downloads Page Mobile Downloads, and Downloads Page Discord Bot Access explain how the route splits ecosystem access into distinct installation and invite surfaces.',
      paragraphs: [
        'Downloads Page Overview explains the route as a hub, while Downloads Page Desktop App Downloads, Downloads Page Daemon Downloads, Downloads Page Mobile Downloads, and Downloads Page Discord Bot Access explain the four concrete access paths shown there.',
        'That matters because the page is not offering one universal installer. It is helping users choose the right entry point for their environment and goal.',
        'The clearest answer is to name those mechanics directly: use Downloads Page Desktop App Downloads for the full packaged shell, Downloads Page Daemon Downloads for the standalone tray and MCP runtime, Downloads Page Mobile Downloads for store-link installs, and Downloads Page Discord Bot Access for invite-based access instead of file downloads.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_downloads_faq_desktop_vs_daemon_01',
      source: 'Downloads Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What is the difference between the desktop app download and the standalone daemon download?',
      title: 'What is the difference between the desktop app download and the standalone daemon download?',
      disambiguation: 'This chunk is about the interaction between the desktop and daemon download sections, not a claim that they are unrelated products.',
      mechanics: ['Downloads Page Desktop App Downloads', 'Downloads Page Daemon Downloads', 'Downloads Page Edition Selection'],
      tags: ['trackerai', 'downloads', 'faq', 'desktop', 'daemon', 'editions'],
      interaction_type: 'cross_system',
      interaction_summary: 'Downloads Page Desktop App Downloads, Downloads Page Daemon Downloads, and Downloads Page Edition Selection explain why the page offers both a full desktop shell and a standalone daemon path that still shares the same edition vocabulary.',
      paragraphs: [
        'Downloads Page Desktop App Downloads explains that the desktop installers already include the daemon, while Downloads Page Daemon Downloads explains the standalone daemon package path for users who want just that runtime layer.',
        'Downloads Page Edition Selection matters because both sections reuse Lite, Standard, and Pro labels, but those labels are applied to different installer families.',
        'The clearest answer is to name those mechanics directly: the desktop download gives you the packaged app shell with a bundled daemon inside, while the daemon download gives you only the standalone Catt Daemon installer for that platform and edition.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_downloads_faq_mobile_01',
      source: 'Downloads Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What mobile download options are available right now?',
      title: 'What mobile download options are available right now?',
      disambiguation: 'This chunk is about the interaction between the mobile section and the overall downloads page, not a generic mobile roadmap.',
      mechanics: ['Downloads Page Mobile Downloads', 'Downloads Page Overview'],
      tags: ['trackerai', 'downloads', 'faq', 'mobile', 'android', 'ios'],
      interaction_type: 'conditional',
      interaction_summary: 'Downloads Page Mobile Downloads and Downloads Page Overview explain why the route currently presents Android as a live store path and iOS as a coming-soon placeholder.',
      paragraphs: [
        'Downloads Page Mobile Downloads explains the current Android store button and the disabled iOS Coming Soon state, while Downloads Page Overview explains mobile as one branch of the broader downloads hub.',
        'That is why a user can get a real mobile install path for Android right now without seeing a matching iOS installer yet.',
        'The clearest answer is to name those mechanics directly: Android is currently available through the Play Store link on the page, while iOS is shown as planned but not yet downloadable.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_downloads_faq_bots_01',
      source: 'Downloads Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why are Tracker Bot and Tools Bot listed on the downloads page if they are not file downloads?',
      title: 'Why are Tracker Bot and Tools Bot listed on the downloads page if they are not file downloads?',
      disambiguation: 'This chunk is about the interaction between the bot access section and the overall downloads page purpose, not a claim that the bots are packaged like desktop binaries.',
      mechanics: ['Downloads Page Discord Bot Access', 'Downloads Page Overview'],
      tags: ['trackerai', 'downloads', 'faq', 'discord bots', 'tracker bot', 'tools bot'],
      interaction_type: 'cross_system',
      interaction_summary: 'Downloads Page Discord Bot Access and Downloads Page Overview explain why the route groups Discord invite links with installer downloads as part of one broader ecosystem-access hub.',
      paragraphs: [
        'Downloads Page Discord Bot Access explains that the bot section is invite-based, and Downloads Page Overview explains that the route is acting as a central access hub for the ecosystem rather than a pure binary-only download list.',
        'That is why bot invite buttons sit beside desktop, daemon, and mobile options even though their underlying action is OAuth authorization rather than downloading a file.',
        'The clearest answer is to name those mechanics directly: the page groups every major install or access path together, and for bots the relevant path is an invite link instead of an installer package.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_downloads_faq_build_01',
      source: 'Downloads Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Can I build the desktop app or daemon myself instead of downloading the prebuilt packages?',
      title: 'Can I build the desktop app or daemon myself instead of downloading the prebuilt packages?',
      disambiguation: 'This chunk is about the interaction between the download cards and the build-it-yourself sections, not a claim that source builds are required for normal use.',
      mechanics: ['Downloads Page Desktop App Downloads', 'Downloads Page Daemon Downloads'],
      tags: ['trackerai', 'downloads', 'faq', 'build from source', 'desktop', 'daemon'],
      interaction_type: 'cross_system',
      interaction_summary: 'Downloads Page Desktop App Downloads and Downloads Page Daemon Downloads explain how both installer families also expose build-it-yourself instructions directly on the route.',
      paragraphs: [
        'Downloads Page Desktop App Downloads explains the desktop clone and pnpm make workflow, while Downloads Page Daemon Downloads explains the daemon-specific build matrix and start commands.',
        'That means the page supports both normal prebuilt downloads and transparency-oriented source-build workflows without sending the user elsewhere first.',
        'The clearest answer is to name those mechanics directly: yes, both the desktop app and the daemon have build-it-yourself expansion panels with copyable commands on the downloads page.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_downloads_faq_ai_01',
      source: 'Downloads Page Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do on the downloads page?',
      title: 'What can TrackerAI help me do on the downloads page?',
      disambiguation: 'This chunk is about the interaction between downloads-page knowledge and TrackerAI help boundaries, not silent installation or background package management.',
      mechanics: ['Downloads Page Overview', 'Downloads Page AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'downloads', 'faq', 'ai help'],
      interaction_type: 'conditional',
      interaction_summary: 'Downloads Page Overview, Downloads Page AI Help Coverage, and TrackerAI Safety Guardrails define the kinds of guidance the assistant can provide on the downloads route without pretending it already performed an install.',
      paragraphs: [
        'Downloads Page Overview provides the route context, and Downloads Page AI Help Coverage explains why this page is a good fit for explaining which access path a user should choose.',
        'This is where TrackerAI is most useful for normal users: clarifying desktop versus daemon packaging, checking whether mobile support is live yet, and identifying which Discord bot invite matches the user\'s goal.',
        'TrackerAI Safety Guardrails is the boundary that keeps that help honest, because explanation and link selection are different from claiming that the assistant silently downloaded or installed software in the background.',
      ],
    }),
  ]
}
