import {
  MODULES_CALCULATOR_ASSIST_FACTS,
  MODULES_CALCULATOR_COST_FACTS,
  MODULES_CALCULATOR_OVERVIEW_FACTS,
  MODULES_CALCULATOR_PATH_FACTS,
  MODULES_CALCULATOR_SYNC_FACTS,
  MODULES_TRACKER_AI_FACTS,
  MODULES_TRACKER_CALCULATOR_LINK_FACTS,
  MODULES_TRACKER_EQUIPPED_FACTS,
  MODULES_TRACKER_OVERVIEW_FACTS,
  MODULES_TRACKER_OVERVIEW_TAB_FACTS,
  MODULES_TRACKER_PROGRESS_FACTS,
  MODULES_TRACKER_SYNC_FACTS,
} from './trackerAiModulesSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiModulesCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_modules_overview_01',
      source: 'Module Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Module Tracker',
      title: 'Module Tracker Overview',
      disambiguation: 'This chunk describes the Module Tracker Overview mechanic itself, not its interactions. It is not the general module encyclopedia or raw module stat tables.',
      mechanics: ['Module Tracker Overview'],
      tags: ['trackerai', 'modules', 'tracker', 'site page', 'overview'],
      paragraphs: [...MODULES_TRACKER_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_modules_progress_01',
      source: 'Module Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Progress Planning Table',
      title: 'Module Tracker Progress Planning Table',
      disambiguation: 'This chunk describes the Module Tracker Progress Planning Table mechanic itself, not its interactions. It is not the equipped loadout editor or the module calculator workspace.',
      mechanics: ['Module Tracker Progress Planning Table'],
      tags: ['trackerai', 'modules', 'tracker', 'progress', 'copies', 'weekly gems'],
      paragraphs: [...MODULES_TRACKER_PROGRESS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_modules_equipped_01',
      source: 'Module Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Equipped Tab',
      title: 'Module Tracker Equipped Tab',
      disambiguation: 'This chunk describes the Module Tracker Equipped Tab mechanic itself, not its interactions. It is not the progress table or the general catalog overview.',
      mechanics: ['Module Tracker Equipped Tab'],
      tags: ['trackerai', 'modules', 'tracker', 'equipped', 'presets', 'substats'],
      paragraphs: [...MODULES_TRACKER_EQUIPPED_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_modules_overview_tab_01',
      source: 'Module Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'All Modules Tab',
      title: 'Module Tracker All Modules Tab',
      disambiguation: 'This chunk describes the Module Tracker All Modules Tab mechanic itself, not its interactions. It is not the progress table or an external wiki view.',
      mechanics: ['Module Tracker All Modules Tab'],
      tags: ['trackerai', 'modules', 'tracker', 'overview', 'catalog', 'artwork'],
      paragraphs: [...MODULES_TRACKER_OVERVIEW_TAB_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_modules_sync_01',
      source: 'Module Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Local Save and Sync',
      title: 'Module Tracker Local Save and Sync',
      disambiguation: 'This chunk describes the Module Tracker Local Save and Sync mechanic itself, not its interactions. It is not a low-level sync protocol dump.',
      mechanics: ['Module Tracker Local Save and Sync'],
      tags: ['trackerai', 'modules', 'tracker', 'sync', 'local save', 'cloud'],
      paragraphs: [...MODULES_TRACKER_SYNC_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_modules_calculator_overview_01',
      source: 'Module Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Module Calculator Workspace',
      title: 'Module Calculator Workspace Overview',
      disambiguation: 'This chunk describes the Module Calculator Workspace Overview mechanic itself, not its interactions. It is not the tracker page or a single standalone module-cost table.',
      mechanics: ['Module Calculator Workspace Overview'],
      tags: ['trackerai', 'modules', 'calculator', 'site page', 'overview'],
      paragraphs: [...MODULES_CALCULATOR_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_modules_calculator_costs_01',
      source: 'Module Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Module Cost Tab',
      title: 'Module Calculator Module Cost Tab',
      disambiguation: 'This chunk describes the Module Calculator Module Cost Tab mechanic itself, not its interactions. It is not the assist-stone planner or shard-splitter path tool.',
      mechanics: ['Module Calculator Module Cost Tab'],
      tags: ['trackerai', 'modules', 'calculator', 'costs', 'shards', 'coins'],
      paragraphs: [...MODULES_CALCULATOR_COST_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_modules_calculator_assist_01',
      source: 'Module Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Assist Module Cost Tab',
      title: 'Module Calculator Assist Module Cost Tab',
      disambiguation: 'This chunk describes the Module Calculator Assist Module Cost Tab mechanic itself, not its interactions. It is not the normal rarity-and-level cost tab.',
      mechanics: ['Module Calculator Assist Module Cost Tab'],
      tags: ['trackerai', 'modules', 'calculator', 'assist', 'stones', 'substats'],
      paragraphs: [...MODULES_CALCULATOR_ASSIST_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_modules_calculator_paths_01',
      source: 'Module Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Shard Splitter and Effective Paths Tabs',
      title: 'Module Calculator Shard Splitter and Effective Paths Tabs',
      disambiguation: 'This chunk describes the Module Calculator Shard Splitter and Effective Paths Tabs mechanic itself, not its interactions. It is not a claim that these tabs replace the main shard-splitter tool everywhere else on the site.',
      mechanics: ['Module Calculator Shard Splitter and Effective Paths Tabs'],
      tags: ['trackerai', 'modules', 'calculator', 'shard splitter', 'effective paths'],
      paragraphs: [...MODULES_CALCULATOR_PATH_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_modules_calculator_sync_01',
      source: 'Module Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Cross-Tab Calculator State',
      title: 'Module Calculator Cross-Tab State',
      disambiguation: 'This chunk describes the Module Calculator Cross-Tab State mechanic itself, not its interactions. It is not a cloud-sync explanation or a promise that every module subtool uses identical outputs.',
      mechanics: ['Module Calculator Cross-Tab State'],
      tags: ['trackerai', 'modules', 'calculator', 'shared state', 'tabs', 'shard splitter'],
      paragraphs: [...MODULES_CALCULATOR_SYNC_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_modules_link_01',
      source: 'Module Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Tracker and Calculator Link',
      title: 'Module Tracker and Calculator Link',
      disambiguation: 'This chunk describes the Module Tracker and Calculator Link mechanic itself, not its interactions. It is not a claim that the tracker and calculator are identical views.',
      mechanics: ['Module Tracker and Calculator Link'],
      tags: ['trackerai', 'modules', 'tracker', 'calculator', 'shared context'],
      paragraphs: [...MODULES_TRACKER_CALCULATOR_LINK_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_modules_ai_01',
      source: 'Module Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on Module Pages',
      title: 'Module Tracker and Calculator AI Help Coverage',
      disambiguation: 'This chunk describes the Module Tracker and Calculator AI Help Coverage mechanic itself, not its interactions. It is not unrestricted bulk editing or silent resets.',
      mechanics: ['Module Tracker and Calculator AI Help Coverage'],
      tags: ['trackerai', 'modules', 'ai help', 'tracker', 'calculator'],
      paragraphs: [...MODULES_TRACKER_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_modules_faq_use_01',
      source: 'Module Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I use the Module tracker page?',
      title: 'How do I use the Module tracker page?',
      disambiguation: 'This chunk is about the interaction between the main Module tracker tabs, not the deeper game meaning of module bonuses.',
      mechanics: ['Module Tracker Overview', 'Module Tracker Progress Planning Table', 'Module Tracker Equipped Tab', 'Module Tracker All Modules Tab', 'Module Tracker and Calculator Link'],
      tags: ['trackerai', 'modules', 'faq', 'tracker', 'tabs', 'workflow'],
      interaction_type: 'cross_system',
      interaction_summary: 'Module Tracker Overview, Module Tracker Progress Planning Table, Module Tracker Equipped Tab, Module Tracker All Modules Tab, and Module Tracker and Calculator Link explain how the tracker splits collection progress, equipped loadouts, catalog review, and calculator handoff into separate surfaces.',
      paragraphs: [
        'Module Tracker Overview explains the page as a whole, Module Tracker Progress Planning Table covers copy planning, Module Tracker Equipped Tab covers live loadout and preset editing, Module Tracker All Modules Tab covers broad catalog review, and Module Tracker and Calculator Link explains how the calculator workspace fits into that workflow.',
        'That matters because users often ask where a module task belongs before they ask about the underlying numbers.',
        'The clearest answer is to name those mechanics directly: use Progress for owned-copy planning, use Equipped for loadout presets and slot editing, use All Modules for broad review, and use the calculator link when the question becomes deeper module math.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_modules_faq_tracker_vs_calc_01',
      source: 'Module Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What is the difference between the Module tracker and calculator?',
      title: 'What is the difference between the Module tracker and calculator?',
      disambiguation: 'This chunk is about the interaction between the Module tracker and calculator, not a claim that one replaces the other.',
      mechanics: ['Module Tracker Overview', 'Module Calculator Workspace Overview', 'Module Tracker and Calculator Link'],
      tags: ['trackerai', 'modules', 'faq', 'tracker', 'calculator', 'difference'],
      interaction_type: 'cross_system',
      interaction_summary: 'Module Tracker Overview, Module Calculator Workspace Overview, and Module Tracker and Calculator Link explain why one page manages owned modules and equipped presets while the other focuses on module-optimization math.',
      paragraphs: [
        'Module Tracker Overview explains the broader management page, Module Calculator Workspace Overview explains the multi-tool calculator page, and Module Tracker and Calculator Link explains why they share context instead of acting like unrelated tools.',
        'That relationship is the practical answer for users who want to know where to start.',
        'The clearest answer is to name those mechanics directly: use the tracker for long-term ownership and loadout state, use the calculator workspace for optimization math, and use the shared-link mechanic for how the two surfaces stay aligned.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_modules_faq_weekly_gems_01',
      source: 'Module Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What does estimated weekly gems affect on the Module tracker?',
      title: 'What does estimated weekly gems affect on the Module tracker?',
      disambiguation: 'This chunk is about the interaction between Module Tracker Progress Planning Table and Module Tracker Overview, not a universal gem-income formula outside the site tools.',
      mechanics: ['Module Tracker Overview', 'Module Tracker Progress Planning Table'],
      tags: ['trackerai', 'modules', 'faq', 'weekly gems', 'time to max', 'progress'],
      interaction_type: 'conditional',
      interaction_summary: 'Module Tracker Overview and Module Tracker Progress Planning Table explain why the tracker asks for weekly-gem pace when showing time-oriented copy projections.',
      paragraphs: [
        'Module Tracker Overview explains the page context, and Module Tracker Progress Planning Table explains that the progress table can show time-to-next and time-to-max style projections based on the user\'s own weekly gem pace.',
        'That is why the field exists: those time estimates are only useful if they match the account pace the user actually expects.',
        'The clearest answer is to name that mechanic directly: estimated weekly gems personalizes the progress table\'s time-based module copy projections.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_modules_faq_equipped_01',
      source: 'Module Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do equipped presets and slot editing work on the Module tracker?',
      title: 'How do equipped presets and slot editing work on the Module tracker?',
      disambiguation: 'This chunk is about the interaction between Module Tracker Equipped Tab and Module Tracker Overview, not a claim that resetting slots deletes the whole tracker.',
      mechanics: ['Module Tracker Overview', 'Module Tracker Equipped Tab'],
      tags: ['trackerai', 'modules', 'faq', 'equipped', 'presets', 'slots'],
      interaction_type: 'cross_system',
      interaction_summary: 'Module Tracker Overview and Module Tracker Equipped Tab explain how the tracker separates collection progress from active loadout presets, slot editing, and assist-efficiency controls.',
      paragraphs: [
        'Module Tracker Overview explains where the Equipped tab sits in the broader tracker, and Module Tracker Equipped Tab explains how presets, slot editing, substats, descriptions, and reset behavior work inside that tab.',
        'That matters because users often want to change their active loadout without confusing that task with owned-copy tracking.',
        'The clearest answer is to name those mechanics directly: the Equipped tab is the preset-based loadout editor, while the broader tracker still holds the rest of the module workflow around it.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_modules_faq_progress_cleanup_01',
      source: 'Module Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do adding, removing, and grouped progress views work on the Module tracker?',
      title: 'How do adding, removing, and grouped progress views work on the Module tracker?',
      disambiguation: 'This chunk is about the interaction between the Module progress entry flow and the grouped progress table, not a claim that removal only hides entries.',
      mechanics: ['Module Tracker Overview', 'Module Tracker Progress Planning Table'],
      tags: ['trackerai', 'modules', 'faq', 'add module', 'remove module', 'grouping'],
      interaction_type: 'cross_system',
      interaction_summary: 'Module Tracker Overview and Module Tracker Progress Planning Table explain how modules are added into the tracker and then managed through filtered, grouped, and removable progress rows.',
      paragraphs: [
        'Module Tracker Overview explains the overall workflow, and Module Tracker Progress Planning Table explains that the tracker combines add-module entry, grouped progress views, copy planning columns, and direct row removal in the same progress surface.',
        'That matters because users often want to know whether they should treat the progress tab as a passive list or as the place where ownership data is actively maintained.',
        'The clearest answer is to name those mechanics directly: add entries from the progress form, use filters and grouping to review them, and use the row actions when the tracked module list itself needs cleanup.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_modules_faq_calc_modes_01',
      source: 'Module Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Which module calculator tab should I use?',
      title: 'Which module calculator tab should I use?',
      disambiguation: 'This chunk is about the interaction between the module calculator workspace tabs, not a claim that they all answer the same question.',
      mechanics: ['Module Calculator Workspace Overview', 'Module Calculator Module Cost Tab', 'Module Calculator Assist Module Cost Tab', 'Module Calculator Shard Splitter and Effective Paths Tabs'],
      tags: ['trackerai', 'modules', 'faq', 'calculator', 'tabs', 'which tool'],
      interaction_type: 'cross_system',
      interaction_summary: 'Module Calculator Workspace Overview, Module Calculator Module Cost Tab, Module Calculator Assist Module Cost Tab, and Module Calculator Shard Splitter and Effective Paths Tabs explain how the module calculator page splits normal costs, assist stones, shard splitting, and effective-path work into different modes.',
      paragraphs: [
        'Module Calculator Workspace Overview explains the four-tab calculator workspace, Module Calculator Module Cost Tab covers normal rarity-and-level cost planning, Module Calculator Assist Module Cost Tab covers stone-planning for multiplier and substats, and Module Calculator Shard Splitter and Effective Paths Tabs covers the shard-optimization modes.',
        'That matters because users often know they need a module calculator but are not sure which tab matches the question they actually have.',
        'The clearest answer is to name those mechanics directly: use Module Cost for standard upgrade paths, Assist Module Cost for stone planning, and Shard Splitter or Effective Paths when the question is broader shard optimization.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_modules_faq_calc_state_01',
      source: 'Module Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why do module calculator tabs seem to remember each other\'s settings?',
      title: 'Why do module calculator tabs seem to remember each other\'s settings?',
      disambiguation: 'This chunk is about the interaction between the module calculator workspace tabs, not a cloud-sync explanation or a bug report about stale UI.',
      mechanics: ['Module Calculator Workspace Overview', 'Module Calculator Shard Splitter and Effective Paths Tabs', 'Module Calculator Cross-Tab State'],
      tags: ['trackerai', 'modules', 'faq', 'shared state', 'calculator', 'tabs'],
      interaction_type: 'cross_system',
      interaction_summary: 'Module Calculator Workspace Overview, Module Calculator Shard Splitter and Effective Paths Tabs, and Module Calculator Cross-Tab State explain why module-cost and shard-path tabs can reuse shared planning assumptions during one module session.',
      paragraphs: [
        'Module Calculator Workspace Overview explains the connected four-tab calculator workspace, Module Calculator Shard Splitter and Effective Paths Tabs explains the optimization side of that workspace, and Module Calculator Cross-Tab State explains why key inputs can stay aligned between them.',
        'That means remembered values between tabs usually reflect intentional shared module-planning context rather than random carryover.',
        'The clearest answer is to name those mechanics directly: the module calculator is designed to reuse important module assumptions across its tabs so users can move between cost and optimization views without re-entering everything.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_modules_faq_sync_01',
      source: 'Module Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Does the Module tracker save and sync with the calculator?',
      title: 'Does the Module tracker save and sync with the calculator?',
      disambiguation: 'This chunk is about the interaction between Module tracker sync behavior and the shared tracker-calculator workflow, not a low-level store contract.',
      mechanics: ['Module Tracker Local Save and Sync', 'Module Tracker and Calculator Link', 'Module Calculator Workspace Overview', 'Module Calculator Shard Splitter and Effective Paths Tabs', 'Module Calculator Cross-Tab State'],
      tags: ['trackerai', 'modules', 'faq', 'sync', 'shared state', 'calculator'],
      interaction_type: 'conditional',
      interaction_summary: 'Module Tracker Local Save and Sync, Module Tracker and Calculator Link, Module Calculator Workspace Overview, Module Calculator Shard Splitter and Effective Paths Tabs, and Module Calculator Cross-Tab State explain how module state persists and why calculator context can follow the broader module workflow.',
      paragraphs: [
        'Module Tracker Local Save and Sync explains the persistence layer, Module Tracker and Calculator Link explains the embedded and standalone calculator relationship, and Module Calculator Workspace Overview, Module Calculator Shard Splitter and Effective Paths Tabs, and Module Calculator Cross-Tab State explain the calculator-side context that can stay aligned across module planning modes.',
        'That is why the module calculator workspace can feel like it already knows the assumptions the tracker or other module tabs were using.',
        'The cleanest answer is to name those mechanics directly: use the sync chunk for persistence, then use the tracker-calculator link and calculator workspace chunks for how saved module context carries into the calculator views.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_modules_faq_ai_01',
      source: 'Module Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do with the Module tracker and calculator?',
      title: 'What can TrackerAI help me do with the Module tracker and calculator?',
      disambiguation: 'This chunk is about the interaction between module page knowledge and TrackerAI help boundaries, not unrestricted bulk edits or sync control.',
      mechanics: ['Module Tracker Overview', 'Module Calculator Workspace Overview', 'Module Tracker and Calculator Link', 'Module Tracker and Calculator AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'modules', 'faq', 'ai help', 'tracker', 'calculator'],
      interaction_type: 'conditional',
      interaction_summary: 'Module Tracker Overview, Module Calculator Workspace Overview, Module Tracker and Calculator Link, Module Tracker and Calculator AI Help Coverage, and TrackerAI Safety Guardrails define the kinds of module-page help the assistant can give without pretending it should silently rewrite saved tracker state.',
      paragraphs: [
        'Module Tracker Overview and Module Calculator Workspace Overview provide the two page contexts, Module Tracker and Calculator Link explains why users move between them, and Module Tracker and Calculator AI Help Coverage explains why this is a strong explanation-and-guidance area for the assistant.',
        'This is where TrackerAI is most useful for normal users: deciding which module surface to use, understanding copy-progress and loadout controls, and clarifying which calculator tab matches a module-cost or shard-path question.',
        'TrackerAI Safety Guardrails is the boundary that keeps that help honest, because explanation and interpretation are different from silently deleting entries, resetting slots, or running sync on the user\'s behalf.',
      ],
    }),
  ]
}
