import {
  BEMERGED_AI_FACTS,
  BEMERGED_BOSS_PREP_FACTS,
  BEMERGED_ELIGIBILITY_FACTS,
  BEMERGED_FAMILY_STRATEGY_FACTS,
  BEMERGED_GOALS_FACTS,
  BEMERGED_HAZARDS_FACTS,
  BEMERGED_INVENTORY_FACTS,
  BEMERGED_LEADERBOARD_FACTS,
  BEMERGED_MERGE_FACTS,
  BEMERGED_OVERVIEW_FACTS,
  BEMERGED_PHASE_STRATEGY_FACTS,
  BEMERGED_PERSONAL_BESTS_FACTS,
  BEMERGED_SETTINGS_FACTS,
  BEMERGED_SHARDS_FACTS,
  BEMERGED_SHATTER_FACTS,
  BEMERGED_TURN_FLOW_FACTS,
  BEMERGED_UNIQUES_FACTS,
} from './trackerAiBemergedSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiBemergedCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bemerged_overview_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'BeMerged',
      title: 'BeMerged Overview',
      disambiguation: 'This chunk is about the BeMerged Overview mechanic itself, not its interactions. It is not a private dev sandbox, a raw game-engine spec, or a Tower gameplay guide.',
      mechanics: ['BeMerged Overview'],
      tags: ['trackerai', 'bemerged', 'site page', 'game', 'overview'],
      paragraphs: [...BEMERGED_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bemerged_goals_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Goals and Run Stats',
      title: 'BeMerged Goals and Run Stats',
      disambiguation: 'This chunk is about the BeMerged Goals and Run Stats mechanic itself, not its interactions. It is not a hidden solver trace or a full rarity-balance spreadsheet.',
      mechanics: ['BeMerged Goals and Run Stats'],
      tags: ['trackerai', 'bemerged', 'goal', 'stats', 'shards', 'moves'],
      paragraphs: [...BEMERGED_GOALS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bemerged_turn_flow_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Turn Flow',
      title: 'BeMerged Turn Flow',
      disambiguation: 'This chunk is about the BeMerged Turn Flow mechanic itself, not its interactions. It is not a hidden solver route or a complete rarity math breakdown.',
      mechanics: ['BeMerged Turn Flow'],
      tags: ['trackerai', 'bemerged', 'turn flow', 'how to play', 'loop'],
      paragraphs: [...BEMERGED_TURN_FLOW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bemerged_shatter_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Shattering and Cascades',
      title: 'BeMerged Shattering and Cascades',
      disambiguation: 'This chunk is about the BeMerged Shattering and Cascades mechanic itself, not its interactions. It is not the merge system or a guarantee that every cascade is equally valuable.',
      mechanics: ['BeMerged Shattering and Cascades'],
      tags: ['trackerai', 'bemerged', 'shatter', 'combos', 'cascade', 'space'],
      paragraphs: [...BEMERGED_SHATTER_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bemerged_merge_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Merge Mode and Upgrade Rules',
      title: 'BeMerged Merge Mode and Upgrade Rules',
      disambiguation: 'This chunk is about the BeMerged Merge Mode and Upgrade Rules mechanic itself, not its interactions. It is not a board-match rule description or a full upgrade table dump.',
      mechanics: ['BeMerged Merge Mode and Upgrade Rules'],
      tags: ['trackerai', 'bemerged', 'merge mode', 'upgrade', 'uniques', 'rarity'],
      paragraphs: [...BEMERGED_MERGE_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bemerged_hazards_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Hazards and Boss Pressure',
      title: 'BeMerged Hazards and Boss Pressure',
      disambiguation: 'This chunk is about the BeMerged Hazards and Boss Pressure mechanic itself, not its interactions. It is not a secret spawn table or an internal AI combat model.',
      mechanics: ['BeMerged Hazards and Boss Pressure'],
      tags: ['trackerai', 'bemerged', 'hazards', 'bosses', 'mines', 'pressure'],
      paragraphs: [...BEMERGED_HAZARDS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bemerged_inventory_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Inventory and Loadouts',
      title: 'BeMerged Inventory and Loadouts',
      disambiguation: 'This chunk is about the BeMerged Inventory and Loadouts mechanic itself, not its interactions. It is not a generic stash system or a permanent account inventory.',
      mechanics: ['BeMerged Inventory and Loadouts'],
      tags: ['trackerai', 'bemerged', 'inventory', 'loadout', 'equipping', 'uniques'],
      paragraphs: [...BEMERGED_INVENTORY_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bemerged_shards_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Shards and Spawn Tuning',
      title: 'BeMerged Shards and Spawn Tuning',
      disambiguation: 'This chunk is about the BeMerged Shards and Spawn Tuning mechanic itself, not its interactions. It is not a hidden economy table or a promise that one spend pattern is always correct.',
      mechanics: ['BeMerged Shards and Spawn Tuning'],
      tags: ['trackerai', 'bemerged', 'shards', 'spending', 'spawn tuning', 'pf'],
      paragraphs: [...BEMERGED_SHARDS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bemerged_uniques_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Unique Types and Effects',
      title: 'BeMerged Unique Types and Effects',
      disambiguation: 'This chunk is about the BeMerged Unique Types and Effects mechanic itself, not its interactions. It is not a full per-unique balance list or a hidden best-build ranking.',
      mechanics: ['BeMerged Unique Types and Effects'],
      tags: ['trackerai', 'bemerged', 'uniques', 'cannon', 'armor', 'generator', 'core'],
      paragraphs: [...BEMERGED_UNIQUES_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bemerged_phase_strategy_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Run Phases and Priorities',
      title: 'BeMerged Run Phases and Priorities',
      disambiguation: 'This chunk is about the BeMerged Run Phases and Priorities mechanic itself, not its interactions. It is not a solver script or a promise that every run has one fixed correct timeline.',
      mechanics: ['BeMerged Run Phases and Priorities'],
      tags: ['trackerai', 'bemerged', 'strategy', 'early game', 'late game', 'priorities'],
      paragraphs: [...BEMERGED_PHASE_STRATEGY_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bemerged_boss_prep_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Boss Preparation',
      title: 'BeMerged Boss Preparation',
      disambiguation: 'This chunk is about the BeMerged Boss Preparation mechanic itself, not its interactions. It is not a hidden boss seed reader or a full damage simulator.',
      mechanics: ['BeMerged Boss Preparation'],
      tags: ['trackerai', 'bemerged', 'boss', 'prep', 'loadout', 'kiting'],
      paragraphs: [...BEMERGED_BOSS_PREP_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bemerged_family_strategy_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Family Planning',
      title: 'BeMerged Family Planning',
      disambiguation: 'This chunk is about the BeMerged Family Planning mechanic itself, not its interactions. It is not a hidden best-build ranking or a full unique-by-unique tier list.',
      mechanics: ['BeMerged Family Planning'],
      tags: ['trackerai', 'bemerged', 'family', 'cannon', 'armor', 'generator', 'core', 'strategy'],
      paragraphs: [...BEMERGED_FAMILY_STRATEGY_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bemerged_settings_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Page Settings',
      title: 'BeMerged Page Settings',
      disambiguation: 'This chunk is about the BeMerged Page Settings mechanic itself, not its interactions. It is not an exhaustive dev-controls catalog or a backend configuration file.',
      mechanics: ['BeMerged Page Settings'],
      tags: ['trackerai', 'bemerged', 'settings', 'orientation', 'autoplay', 'hints'],
      paragraphs: [...BEMERGED_SETTINGS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bemerged_personal_bests_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Personal Bests and Publishing',
      title: 'BeMerged Personal Bests and Publishing',
      disambiguation: 'This chunk is about the BeMerged Personal Bests and Publishing mechanic itself, not its interactions. It is not a raw cloud schema dump or a guarantee that every session publishes online automatically.',
      mechanics: ['BeMerged Personal Bests and Publishing'],
      tags: ['trackerai', 'bemerged', 'personal best', 'publishing', 'leaderboard', 'signed-in'],
      paragraphs: [...BEMERGED_PERSONAL_BESTS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bemerged_leaderboard_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Leaderboard Connection',
      title: 'BeMerged Leaderboard Connection',
      disambiguation: 'This chunk is about the BeMerged Leaderboard Connection mechanic itself, not its interactions. It is not the full leaderboard page spec or a Tower ranking formula.',
      mechanics: ['BeMerged Leaderboard Connection'],
      tags: ['trackerai', 'bemerged', 'leaderboard', 'metrics', 'results'],
      paragraphs: [...BEMERGED_LEADERBOARD_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bemerged_eligibility_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Leaderboard Eligibility',
      title: 'BeMerged Leaderboard Eligibility',
      disambiguation: 'This chunk is about the BeMerged Leaderboard Eligibility mechanic itself, not its interactions. It is not a moderation workflow or a backend anti-cheat implementation note.',
      mechanics: ['BeMerged Leaderboard Eligibility'],
      tags: ['trackerai', 'bemerged', 'leaderboard', 'eligibility', 'ai', 'dev tools'],
      paragraphs: [...BEMERGED_ELIGIBILITY_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_bemerged_ai_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on BeMerged',
      title: 'BeMerged AI Help Coverage',
      disambiguation: 'This chunk is about the BeMerged AI Help Coverage mechanic itself, not its interactions. It is not a promise that the assistant should bypass page controls or safety limits.',
      mechanics: ['BeMerged AI Help Coverage'],
      tags: ['trackerai', 'bemerged', 'ai help', 'autoplay', 'guidance'],
      paragraphs: [...BEMERGED_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bemerged_faq_goal_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What am I trying to do in BeMerged?',
      title: 'What am I trying to do in BeMerged?',
      disambiguation: 'This chunk is about the interaction between the BeMerged page and the goal-tracking shown during play, not a hidden optimization script.',
      mechanics: ['BeMerged Overview', 'BeMerged Goals and Run Stats'],
      tags: ['trackerai', 'bemerged', 'faq', 'goal', 'win condition', 'stats'],
      interaction_type: 'cross_system',
      interaction_summary: 'BeMerged Overview and BeMerged Goals and Run Stats work together to explain both the high-level point of the page and the run metrics users watch while pursuing that goal.',
      paragraphs: [
        'BeMerged Overview tells the user what page they are on, and BeMerged Goals and Run Stats explains the actual run objective and the on-page metrics that show whether the run is moving in the right direction.',
        'That pairing matters because players usually ask this question in practical terms: what counts as success here, and which numbers on the screen actually matter while playing?',
        'The clearest answer is to name those mechanics directly: use BeMerged Overview for orientation, then use BeMerged Goals and Run Stats for the win condition and the run numbers like time, moves, merges, and shards.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bemerged_faq_play_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I actually play BeMerged?',
      title: 'How do I actually play BeMerged?',
      disambiguation: 'This chunk is about the interaction between the BeMerged page, the normal turn flow, and the two main board actions, not a hidden autoplay script.',
      mechanics: ['BeMerged Overview', 'BeMerged Turn Flow', 'BeMerged Shattering and Cascades', 'BeMerged Merge Mode and Upgrade Rules'],
      tags: ['trackerai', 'bemerged', 'faq', 'how to play', 'turn flow', 'merge', 'shatter'],
      interaction_type: 'cross_system',
      interaction_summary: 'BeMerged Overview, BeMerged Turn Flow, BeMerged Shattering and Cascades, and BeMerged Merge Mode and Upgrade Rules explain the basic play loop from first move to ongoing board management.',
      paragraphs: [
        'BeMerged Overview tells the user what kind of page they opened, BeMerged Turn Flow explains the clear-merge-survive rhythm, BeMerged Shattering and Cascades explains how players make space and gain shards, and BeMerged Merge Mode and Upgrade Rules explains how real upgrade progress happens.',
        'Those mechanics belong together because new players usually struggle when they treat BeMerged like a simple match-3 board and miss that clearing and upgrading are separate actions with different rules.',
        'The clearest explanation is to name those mechanics directly: use BeMerged Shattering and Cascades when the board is cramped, use BeMerged Merge Mode and Upgrade Rules when upgrading a chosen piece, and let BeMerged Turn Flow tie those actions into a repeatable survival loop.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bemerged_faq_shatter_vs_merge_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What is the difference between shattering and merging?',
      title: 'What is the difference between shattering and merging?',
      disambiguation: 'This chunk is about the interaction between the two main BeMerged board actions, not a hidden combo exploit reference.',
      mechanics: ['BeMerged Shattering and Cascades', 'BeMerged Merge Mode and Upgrade Rules', 'BeMerged Goals and Run Stats'],
      tags: ['trackerai', 'bemerged', 'faq', 'shatter', 'merge', 'difference'],
      interaction_type: 'cross_system',
      interaction_summary: 'BeMerged Shattering and Cascades, BeMerged Merge Mode and Upgrade Rules, and BeMerged Goals and Run Stats explain why one action mainly creates space and resources while the other mainly advances upgrade progress.',
      paragraphs: [
        'BeMerged Shattering and Cascades explains the aligned match-three-or-more action that clears tiles and grants shards, while BeMerged Merge Mode and Upgrade Rules explains the long-press upgrade flow that can pull matching fodder from anywhere on the board.',
        'BeMerged Goals and Run Stats is the reason that difference matters, because a successful run needs both: enough shattering to keep the board alive and enough merging to move uniques toward 5★ Ancestral.',
        'When a user asks which one they should do, the practical answer is to name the mechanics directly: use BeMerged Shattering and Cascades for space and shards, and use BeMerged Merge Mode and Upgrade Rules for actual upgrade progress.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bemerged_faq_hazards_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why does the board suddenly get so dangerous?',
      title: 'Why does the board suddenly get so dangerous?',
      disambiguation: 'This chunk is about the interaction between BeMerged progression pressure and its hazard systems, not a bug report placeholder.',
      mechanics: ['BeMerged Goals and Run Stats', 'BeMerged Hazards and Boss Pressure', 'BeMerged Turn Flow'],
      tags: ['trackerai', 'bemerged', 'faq', 'hazards', 'bosses', 'mines', 'pressure'],
      interaction_type: 'conditional',
      interaction_summary: 'BeMerged Goals and Run Stats, BeMerged Hazards and Boss Pressure, and BeMerged Turn Flow explain why a run that felt stable can become dangerous once hazards, space pressure, and unfinished upgrades start stacking together.',
      paragraphs: [
        'BeMerged Hazards and Boss Pressure explains the direct danger from mines and bosses, BeMerged Turn Flow explains why players need to keep clearing and repositioning instead of drifting, and BeMerged Goals and Run Stats explains why unfinished progress eventually turns those hazards into a real run-ending problem.',
        'That interaction is the core tension of the page: the board is not only asking whether a player can merge correctly, but whether they can keep doing it under increasing pressure.',
        'The most helpful explanation is to name those mechanics clearly: if the board feels like it accelerated out of nowhere, check BeMerged Hazards and Boss Pressure first, then use BeMerged Turn Flow to explain what the player has to keep doing to stay ahead of it.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bemerged_faq_inventory_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why can’t I move or swap this unique?',
      title: 'Why can’t I move or swap this unique?',
      disambiguation: 'This chunk is about the interaction between BeMerged inventory rules and hazard restrictions, not a hidden input bug list.',
      mechanics: ['BeMerged Inventory and Loadouts', 'BeMerged Hazards and Boss Pressure'],
      tags: ['trackerai', 'bemerged', 'faq', 'inventory', 'swap', 'unique', 'hazards'],
      interaction_type: 'conditional',
      interaction_summary: 'BeMerged Inventory and Loadouts and BeMerged Hazards and Boss Pressure explain the most common reasons a player cannot freely move, equip, or swap a unique when they expect to.',
      paragraphs: [
        'BeMerged Inventory and Loadouts explains the same-type swap requirement and the one-per-type loadout structure, while BeMerged Hazards and Boss Pressure explains why boss presence and nearby hazards can lock down movement decisions at bad times.',
        'That is why the answer is usually a rules explanation rather than a glitch explanation. The page intentionally makes loadout timing part of the challenge.',
        'A clean answer should name both mechanics directly: use BeMerged Inventory and Loadouts for the legal swap rules, and use BeMerged Hazards and Boss Pressure when the real blocker is a boss or hazard making that swap unsafe or unavailable.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bemerged_faq_shards_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Should I spend shards or save them?',
      title: 'Should I spend shards or save them?',
      disambiguation: 'This chunk is about the interaction between BeMerged shard spending, run goals, and unique-driven strategy, not a single forced best answer.',
      mechanics: ['BeMerged Goals and Run Stats', 'BeMerged Shards and Spawn Tuning', 'BeMerged Unique Types and Effects'],
      tags: ['trackerai', 'bemerged', 'faq', 'shards', 'spending', 'strategy', 'pf'],
      interaction_type: 'conditional',
      interaction_summary: 'BeMerged Goals and Run Stats, BeMerged Shards and Spawn Tuning, and BeMerged Unique Types and Effects explain why shard decisions depend on what the run still needs and what kind of build the player is leaning into.',
      paragraphs: [
        'BeMerged Shards and Spawn Tuning explains the direct spend-versus-save tradeoff, BeMerged Goals and Run Stats explains what the run is still missing, and BeMerged Unique Types and Effects explains why some loadouts benefit more from stability while others benefit more from scaling.',
        'That means there is no one-line universal answer. A run that is starved for a module family may want short-term spawn help, while a stable run can afford to hold shards for stronger scaling.',
        'The useful answer is to name the mechanics directly: start with BeMerged Goals and Run Stats to see what is lagging, then use BeMerged Shards and Spawn Tuning to decide whether the board needs immediate help or can afford patience.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bemerged_faq_improve_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I improve my BeMerged results?',
      title: 'How do I improve my BeMerged results?',
      disambiguation: 'This chunk is about the interaction between BeMerged play decisions and BeMerged result tracking, not a promise of one dominant meta path.',
      mechanics: ['BeMerged Goals and Run Stats', 'BeMerged Turn Flow', 'BeMerged Hazards and Boss Pressure', 'BeMerged Personal Bests and Publishing', 'BeMerged Leaderboard Connection'],
      tags: ['trackerai', 'bemerged', 'faq', 'improve', 'leaderboard', 'personal best', 'strategy'],
      interaction_type: 'conditional',
      interaction_summary: 'BeMerged Goals and Run Stats, BeMerged Turn Flow, BeMerged Hazards and Boss Pressure, BeMerged Personal Bests and Publishing, and BeMerged Leaderboard Connection explain how stronger play turns into better tracked results on-page and on leaderboard.',
      paragraphs: [
        'BeMerged Goals and Run Stats defines what good progress looks like, BeMerged Turn Flow explains how strong runs stay efficient, and BeMerged Hazards and Boss Pressure explains why survival mistakes often ruin otherwise promising attempts.',
        'BeMerged Personal Bests and Publishing and BeMerged Leaderboard Connection then explain how those cleaner runs become visible as better personal records and stronger leaderboard entries.',
        'For practical help, the assistant should name those mechanics directly: improve the run through BeMerged Turn Flow and BeMerged Hazards and Boss Pressure first, then use BeMerged Personal Bests and Publishing and BeMerged Leaderboard Connection to explain how that improvement appears on the page and the leaderboard.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bemerged_faq_early_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What should I focus on early in a BeMerged run?',
      title: 'What should I focus on early in a BeMerged run?',
      disambiguation: 'This chunk is about the interaction between BeMerged turn flow, run phases, and run goals, not a rigid scripted opener.',
      mechanics: ['BeMerged Goals and Run Stats', 'BeMerged Turn Flow', 'BeMerged Run Phases and Priorities'],
      tags: ['trackerai', 'bemerged', 'faq', 'early game', 'strategy', 'priorities'],
      interaction_type: 'conditional',
      interaction_summary: 'BeMerged Goals and Run Stats, BeMerged Turn Flow, and BeMerged Run Phases and Priorities explain why early BeMerged play is usually about space, stability, and setup before greedier upgrades.',
      paragraphs: [
        'BeMerged Goals and Run Stats explains the long-term win condition, BeMerged Turn Flow explains the repeating clear-merge-survive rhythm, and BeMerged Run Phases and Priorities explains why the early phase is usually about staying flexible rather than forcing one flashy line immediately.',
        'That combination matters because early-run failures often start when players chase upgrade spikes before the board can safely support them.',
        'The clearest help is to name those mechanics directly: use BeMerged Turn Flow to keep the board open, and use BeMerged Run Phases and Priorities to explain why early consistency usually beats early greed.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bemerged_faq_boss_prep_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How should I prepare for the next boss?',
      title: 'How should I prepare for the next boss?',
      disambiguation: 'This chunk is about the interaction between BeMerged boss prep, hazards, inventory rules, and family planning, not a hidden boss exploit guide.',
      mechanics: ['BeMerged Boss Preparation', 'BeMerged Hazards and Boss Pressure', 'BeMerged Inventory and Loadouts', 'BeMerged Family Planning'],
      tags: ['trackerai', 'bemerged', 'faq', 'boss', 'prep', 'inventory', 'loadout'],
      interaction_type: 'conditional',
      interaction_summary: 'BeMerged Boss Preparation, BeMerged Hazards and Boss Pressure, BeMerged Inventory and Loadouts, and BeMerged Family Planning explain why good boss cycles begin before the boss spawns.',
      paragraphs: [
        'BeMerged Boss Preparation explains the timing mindset, BeMerged Hazards and Boss Pressure explains what the boss will punish, BeMerged Inventory and Loadouts explains why swaps have to be handled in advance, and BeMerged Family Planning explains which effects are worth bringing into the next cycle.',
        'That is why strong boss play usually looks calm before the spawn and controlled during the fight instead of frantic once the boss is already locking pieces down.',
        'A useful answer should name those mechanics directly: prepare the board with BeMerged Boss Preparation, lock in the right equipped uniques through BeMerged Inventory and Loadouts and BeMerged Family Planning, then use BeMerged Hazards and Boss Pressure to explain the danger you are trying to avoid.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bemerged_faq_families_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do the four BeMerged families change my strategy?',
      title: 'How do the four BeMerged families change my strategy?',
      disambiguation: 'This chunk is about the interaction between BeMerged family effects, inventory choices, and shard planning, not a single fixed meta ranking.',
      mechanics: ['BeMerged Unique Types and Effects', 'BeMerged Family Planning', 'BeMerged Inventory and Loadouts', 'BeMerged Shards and Spawn Tuning'],
      tags: ['trackerai', 'bemerged', 'faq', 'families', 'cannon', 'armor', 'generator', 'core'],
      interaction_type: 'cross_system',
      interaction_summary: 'BeMerged Unique Types and Effects, BeMerged Family Planning, BeMerged Inventory and Loadouts, and BeMerged Shards and Spawn Tuning explain how the four families push players toward different short-term priorities without changing the overall win condition.',
      paragraphs: [
        'BeMerged Unique Types and Effects explains what each family tends to do, BeMerged Family Planning explains when to lean on one family more heavily, BeMerged Inventory and Loadouts explains how those choices become active on the board, and BeMerged Shards and Spawn Tuning explains why shard choices often follow the same plan.',
        'Together, those mechanics explain why Cannons, Armors, Generators, and Cores do not just add flavor. They change what the run most needs right now.',
        'The best answer is to name those mechanics directly: use BeMerged Unique Types and Effects for the role summary, then use BeMerged Family Planning and BeMerged Inventory and Loadouts to explain how that role turns into an actual play decision.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bemerged_faq_save_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Does BeMerged save my results?',
      title: 'Does BeMerged save my results?',
      disambiguation: 'This chunk is about the interaction between local BeMerged progress handling and leaderboard publishing, not a backend storage internals guide.',
      mechanics: ['BeMerged Overview', 'BeMerged Personal Bests and Publishing', 'BeMerged Leaderboard Connection'],
      tags: ['trackerai', 'bemerged', 'faq', 'save', 'personal best', 'leaderboard'],
      interaction_type: 'conditional',
      interaction_summary: 'BeMerged Overview, BeMerged Personal Bests and Publishing, and BeMerged Leaderboard Connection explain how BeMerged can keep local bests while also feeding a shared leaderboard flow for eligible signed-in results.',
      paragraphs: [
        'BeMerged Overview frames the page, BeMerged Personal Bests and Publishing explains the local best-shards behavior and attempt-summary publishing path, and BeMerged Leaderboard Connection explains how those results show up in the dedicated BeMerged leaderboard mode.',
        'That is why users may still see meaningful BeMerged progress on the page even before worrying about leaderboard visibility, while signed-in play can also feed shared rankings.',
        'For clear help, the assistant should say those mechanics by name: BeMerged Personal Bests and Publishing covers the save path, and BeMerged Leaderboard Connection covers the leaderboard side of the same story.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bemerged_faq_settings_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What settings can I change in BeMerged?',
      title: 'What settings can I change in BeMerged?',
      disambiguation: 'This chunk is about the interaction between BeMerged page use and visible settings controls, not a hidden developer-only tuning reference.',
      mechanics: ['BeMerged Overview', 'BeMerged Page Settings'],
      tags: ['trackerai', 'bemerged', 'faq', 'settings', 'orientation', 'autoplay'],
      interaction_type: 'cross_system',
      interaction_summary: 'BeMerged Overview and BeMerged Page Settings connect the game page to the visible options users can change for comfort, layout, and autoplay behavior.',
      paragraphs: [
        'BeMerged Overview explains that this is a standalone game page inside the site, and BeMerged Page Settings explains the visible settings panel where users can change how that page behaves for them.',
        'That matters because people often ask whether a control belongs to the game itself or to the surrounding tracker site, and on this page the settings panel is part of the BeMerged experience they are already using.',
        'A good answer should point to BeMerged Page Settings directly for orientation, hints, background, and autoplay-related preferences instead of treating the page like it has no customization at all.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bemerged_faq_leaderboard_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How does BeMerged connect to leaderboard?',
      title: 'How does BeMerged connect to leaderboard?',
      disambiguation: 'This chunk is about the interaction between the BeMerged page and the dedicated BeMerged leaderboard mode, not a generic Tower leaderboard explanation.',
      mechanics: ['BeMerged Leaderboard Connection', 'Leaderboard Modes and Tiers', 'Leaderboard BeMerged View'],
      tags: ['trackerai', 'bemerged', 'faq', 'leaderboard', 'metrics', 'mode'],
      interaction_type: 'cross_system',
      interaction_summary: 'BeMerged Leaderboard Connection, Leaderboard Modes and Tiers, and Leaderboard BeMerged View explain how BeMerged results become a dedicated leaderboard experience instead of just another Tower tier.',
      paragraphs: [
        'BeMerged Leaderboard Connection explains that BeMerged has its own ranking path, Leaderboard Modes and Tiers explains where users switch into that mode on the main leaderboard page, and Leaderboard BeMerged View explains the BeMerged-specific columns they will see there.',
        'This is the bridge that keeps the site consistent: the game page and leaderboard page are separate surfaces, but they are describing the same class of BeMerged attempt results.',
        'When users ask how the two pages connect, the assistant should name those mechanics directly rather than answering vaguely: use Leaderboard Modes and Tiers to open the mode, use Leaderboard BeMerged View to read it, and use BeMerged Leaderboard Connection to explain why the numbers belong there.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bemerged_faq_eligibility_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why didn’t my BeMerged run qualify for leaderboard?',
      title: 'Why didn’t my BeMerged run qualify for leaderboard?',
      disambiguation: 'This chunk is about the interaction between BeMerged result tracking, eligibility, and AI-help boundaries, not a hidden enforcement workflow.',
      mechanics: ['BeMerged Personal Bests and Publishing', 'BeMerged Leaderboard Connection', 'BeMerged Leaderboard Eligibility', 'BeMerged AI Help Coverage'],
      tags: ['trackerai', 'bemerged', 'faq', 'leaderboard', 'eligibility', 'ai'],
      interaction_type: 'conditional',
      interaction_summary: 'BeMerged Personal Bests and Publishing, BeMerged Leaderboard Connection, BeMerged Leaderboard Eligibility, and BeMerged AI Help Coverage explain why a run can still exist locally without qualifying as a normal leaderboard result.',
      paragraphs: [
        'BeMerged Personal Bests and Publishing explains why the page can still retain personal progress context, BeMerged Leaderboard Connection explains where ranked BeMerged results belong, BeMerged Leaderboard Eligibility explains the extra ranking boundary, and BeMerged AI Help Coverage explains why assisted play is treated differently from normal ranked play.',
        'That distinction is important because users may still see a real run summary on the page even when the attempt is not meant to appear as a standard leaderboard placement.',
        'The clearest answer is to name those mechanics directly: use BeMerged Leaderboard Eligibility for the rule, BeMerged Personal Bests and Publishing for the local record side, and BeMerged Leaderboard Connection for the ranked-result side.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_bemerged_faq_ai_01',
      source: 'BeMerged Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do with BeMerged?',
      title: 'What can TrackerAI help me do with BeMerged?',
      disambiguation: 'This chunk is about the interaction between BeMerged page knowledge and TrackerAI help boundaries, not unrestricted control or hidden dev actions.',
      mechanics: ['BeMerged Overview', 'BeMerged Goals and Run Stats', 'BeMerged Page Settings', 'BeMerged AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'bemerged', 'faq', 'ai help', 'autoplay', 'guidance'],
      interaction_type: 'conditional',
      interaction_summary: 'BeMerged Overview, BeMerged Goals and Run Stats, BeMerged Page Settings, BeMerged AI Help Coverage, and TrackerAI Safety Guardrails define the useful help the assistant can give on BeMerged without turning the page into an unrestricted automation surface.',
      paragraphs: [
        'BeMerged Overview is the orientation layer, BeMerged Goals and Run Stats covers the run objective and visible metrics, and BeMerged Page Settings covers the user-facing controls that affect how the page plays and displays.',
        'BeMerged AI Help Coverage explains why this is a good place for explanation and guided help, especially when the user wants to understand progress, settings, or the meaning of a BeMerged leaderboard result.',
        'TrackerAI Safety Guardrails is the limit that keeps the answer honest: the assistant can explain and guide those mechanics clearly without pretending every unusual action should happen automatically just because AI exists on the page.',
      ],
    }),
  ]
}
