import {
  UW_CALCULATOR_INPUT_FACTS,
  UW_CALCULATOR_OUTPUT_FACTS,
  UW_CALCULATOR_OVERVIEW_FACTS,
  UW_TRACKER_AI_FACTS,
  UW_TRACKER_CALCULATOR_LINK_FACTS,
  UW_TRACKER_OVERVIEW_FACTS,
  UW_TRACKER_OVERVIEW_TAB_FACTS,
  UW_TRACKER_PROGRESS_FACTS,
  UW_TRACKER_SYNC_FACTS,
  UW_TRACKER_UPLOAD_FACTS,
} from './trackerAiUwSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiUwCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_uw_overview_01',
      source: 'Ultimate Weapons Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Ultimate Weapons Tracker',
      title: 'Ultimate Weapons Tracker Overview',
      disambiguation: 'This chunk describes the Ultimate Weapons Tracker Overview mechanic itself, not its interactions. It is not the structured Ultimate Weapon reference layer or the underlying game mechanics of each weapon.',
      mechanics: ['Ultimate Weapons Tracker Overview'],
      tags: ['trackerai', 'ultimate weapons', 'tracker', 'site page', 'overview'],
      paragraphs: [...UW_TRACKER_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_uw_progress_01',
      source: 'Ultimate Weapons Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Progress Planning Table',
      title: 'Ultimate Weapons Tracker Progress Planning Table',
      disambiguation: 'This chunk describes the Ultimate Weapons Tracker Progress Planning Table mechanic itself, not its interactions. It is not the full calculator view or a generic stone guide.',
      mechanics: ['Ultimate Weapons Tracker Progress Planning Table'],
      tags: ['trackerai', 'ultimate weapons', 'tracker', 'progress', 'stones', 'tournaments'],
      paragraphs: [...UW_TRACKER_PROGRESS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_uw_overview_tab_01',
      source: 'Ultimate Weapons Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'All Ultimate Weapons Tab',
      title: 'Ultimate Weapons Tracker All Ultimate Weapons Tab',
      disambiguation: 'This chunk describes the Ultimate Weapons Tracker All Ultimate Weapons Tab mechanic itself, not its interactions. It is not the calculator table or the general Ultimate Weapon encyclopedia.',
      mechanics: ['Ultimate Weapons Tracker All Ultimate Weapons Tab'],
      tags: ['trackerai', 'ultimate weapons', 'tracker', 'overview', 'unlocks', 'cards'],
      paragraphs: [...UW_TRACKER_OVERVIEW_TAB_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_uw_sync_01',
      source: 'Ultimate Weapons Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Local Save and Sync',
      title: 'Ultimate Weapons Tracker Local Save and Sync',
      disambiguation: 'This chunk describes the Ultimate Weapons Tracker Local Save and Sync mechanic itself, not its interactions. It is not a low-level sync protocol dump.',
      mechanics: ['Ultimate Weapons Tracker Local Save and Sync'],
      tags: ['trackerai', 'ultimate weapons', 'tracker', 'sync', 'local save', 'cloud'],
      paragraphs: [...UW_TRACKER_SYNC_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_uw_upload_01',
      source: 'Ultimate Weapons Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Upload Placeholder',
      title: 'Ultimate Weapons Tracker Upload Placeholder',
      disambiguation: 'This chunk describes the Ultimate Weapons Tracker Upload Placeholder mechanic itself, not its interactions. It is not a real OCR system or a promise that screenshot import already exists.',
      mechanics: ['Ultimate Weapons Tracker Upload Placeholder'],
      tags: ['trackerai', 'ultimate weapons', 'tracker', 'upload', 'ocr', 'placeholder'],
      paragraphs: [...UW_TRACKER_UPLOAD_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_uw_calculator_overview_01',
      source: 'Ultimate Weapons Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Ultimate Weapons Calculator',
      title: 'Ultimate Weapons Calculator Overview',
      disambiguation: 'This chunk describes the Ultimate Weapons Calculator Overview mechanic itself, not its interactions. It is not the whole tracker page or the global Ultimate Weapon knowledge base.',
      mechanics: ['Ultimate Weapons Calculator Overview'],
      tags: ['trackerai', 'ultimate weapons', 'calculator', 'site page', 'overview'],
      paragraphs: [...UW_CALCULATOR_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_uw_calculator_inputs_01',
      source: 'Ultimate Weapons Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Calculator Inputs and Filters',
      title: 'Ultimate Weapons Calculator Inputs and Filters',
      disambiguation: 'This chunk describes the Ultimate Weapons Calculator Inputs and Filters mechanic itself, not its interactions. It is not the tracker progress table or a raw stone dataset export.',
      mechanics: ['Ultimate Weapons Calculator Inputs and Filters'],
      tags: ['trackerai', 'ultimate weapons', 'calculator', 'inputs', 'filters', 'targets'],
      paragraphs: [...UW_CALCULATOR_INPUT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_uw_calculator_outputs_01',
      source: 'Ultimate Weapons Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Calculator Outputs',
      title: 'Ultimate Weapons Calculator Outputs',
      disambiguation: 'This chunk describes the Ultimate Weapons Calculator Outputs mechanic itself, not its interactions. It is not a tracker sync explanation.',
      mechanics: ['Ultimate Weapons Calculator Outputs'],
      tags: ['trackerai', 'ultimate weapons', 'calculator', 'outputs', 'stones', 'cumulative'],
      paragraphs: [...UW_CALCULATOR_OUTPUT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_uw_link_01',
      source: 'Ultimate Weapons Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Tracker and Calculator Link',
      title: 'Ultimate Weapons Tracker and Calculator Link',
      disambiguation: 'This chunk describes the Ultimate Weapons Tracker and Calculator Link mechanic itself, not its interactions. It is not a claim that the tracker and calculator are identical views.',
      mechanics: ['Ultimate Weapons Tracker and Calculator Link'],
      tags: ['trackerai', 'ultimate weapons', 'tracker', 'calculator', 'shared state'],
      paragraphs: [...UW_TRACKER_CALCULATOR_LINK_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_uw_ai_01',
      source: 'Ultimate Weapons Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on Ultimate Weapons Pages',
      title: 'Ultimate Weapons Tracker and Calculator AI Help Coverage',
      disambiguation: 'This chunk describes the Ultimate Weapons Tracker and Calculator AI Help Coverage mechanic itself, not its interactions. It is not unrestricted bulk editing or sync control.',
      mechanics: ['Ultimate Weapons Tracker and Calculator AI Help Coverage'],
      tags: ['trackerai', 'ultimate weapons', 'ai help', 'tracker', 'calculator'],
      paragraphs: [...UW_TRACKER_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_uw_faq_use_01',
      source: 'Ultimate Weapons Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I use the Ultimate Weapons tracker page?',
      title: 'How do I use the Ultimate Weapons tracker page?',
      disambiguation: 'This chunk is about the interaction between the main Ultimate Weapons tracker tabs, not the game strategy for choosing a weapon.',
      mechanics: ['Ultimate Weapons Tracker Overview', 'Ultimate Weapons Tracker Progress Planning Table', 'Ultimate Weapons Tracker All Ultimate Weapons Tab', 'Ultimate Weapons Tracker Upload Placeholder'],
      tags: ['trackerai', 'ultimate weapons', 'faq', 'tracker', 'tabs', 'workflow'],
      interaction_type: 'cross_system',
      interaction_summary: 'Ultimate Weapons Tracker Overview, Ultimate Weapons Tracker Progress Planning Table, Ultimate Weapons Tracker All Ultimate Weapons Tab, and Ultimate Weapons Tracker Upload Placeholder explain how the tracker splits roster management, progress planning, and future upload space into separate tabs.',
      paragraphs: [
        'Ultimate Weapons Tracker Overview explains the full page, Ultimate Weapons Tracker Progress Planning Table covers saved targets and estimates, Ultimate Weapons Tracker All Ultimate Weapons Tab covers roster-wide editing, and Ultimate Weapons Tracker Upload Placeholder explains the current upload limitation.',
        'That matters because users often ask where a specific Ultimate Weapon task belongs before they ask about the numbers themselves.',
        'The clearest answer is to name those mechanics directly: use the progress table for planning, use All Ultimate Weapons for broad roster edits, and do not treat Upload as a real OCR workflow yet.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_uw_faq_tracker_vs_calc_01',
      source: 'Ultimate Weapons Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What is the difference between the Ultimate Weapons tracker and calculator?',
      title: 'What is the difference between the Ultimate Weapons tracker and calculator?',
      disambiguation: 'This chunk is about the interaction between the Ultimate Weapons tracker and calculator, not a claim that one replaces the other.',
      mechanics: ['Ultimate Weapons Tracker Overview', 'Ultimate Weapons Calculator Overview', 'Ultimate Weapons Tracker and Calculator Link'],
      tags: ['trackerai', 'ultimate weapons', 'faq', 'tracker', 'calculator', 'difference'],
      interaction_type: 'cross_system',
      interaction_summary: 'Ultimate Weapons Tracker Overview, Ultimate Weapons Calculator Overview, and Ultimate Weapons Tracker and Calculator Link explain why one page manages long-term progress while the other focuses on one-weapon stone planning.',
      paragraphs: [
        'Ultimate Weapons Tracker Overview explains the broader management page, Ultimate Weapons Calculator Overview explains the focused per-weapon planning page, and Ultimate Weapons Tracker and Calculator Link explains why they share state instead of acting like unrelated tools.',
        'That relationship is the practical answer for users who want to know where to start.',
        'The cleanest answer is to name those mechanics directly: use the tracker for long-term saved progress, use the calculator for one-weapon cost planning, and use the tracker-calculator link for how those two surfaces stay aligned.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_uw_faq_tournaments_01',
      source: 'Ultimate Weapons Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why does the Ultimate Weapons tracker ask for average stones per tournament?',
      title: 'Why does the Ultimate Weapons tracker ask for average stones per tournament?',
      disambiguation: 'This chunk is about the interaction between Ultimate Weapons Tracker Overview and Ultimate Weapons Tracker Progress Planning Table, not the individual mechanics or a universal stone-income formula.',
      mechanics: ['Ultimate Weapons Tracker Overview', 'Ultimate Weapons Tracker Progress Planning Table'],
      tags: ['trackerai', 'ultimate weapons', 'faq', 'tournaments', 'stones', 'finish date'],
      interaction_type: 'conditional',
      interaction_summary: 'Ultimate Weapons Tracker Overview and Ultimate Weapons Tracker Progress Planning Table explain why tournament and finish-date estimates need a personal stone-income input instead of assuming one fixed value for everyone.',
      paragraphs: [
        'Ultimate Weapons Tracker Overview explains the page context, and Ultimate Weapons Tracker Progress Planning Table explains that the tracker estimates tournaments needed, time to target, and finish dates from the user’s own stones-per-tournament pace.',
        'That is why the field exists: those estimates are only useful if they match the account pace the user actually expects.',
        'The clearest answer is to name that mechanic directly: average stones per tournament is the input that personalizes the progress table’s tournament and finish-date estimates.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_uw_faq_save_progress_01',
      source: 'Ultimate Weapons Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What does Save to Progress do on the Ultimate Weapons calculator?',
      title: 'What does Save to Progress do on the Ultimate Weapons calculator?',
      disambiguation: 'This chunk is about the interaction between the embedded Ultimate Weapons calculator and tracker progress, not a promise that standalone calculator use always performs the same tracker action.',
      mechanics: ['Ultimate Weapons Calculator Inputs and Filters', 'Ultimate Weapons Tracker and Calculator Link', 'Ultimate Weapons Tracker Progress Planning Table'],
      tags: ['trackerai', 'ultimate weapons', 'faq', 'save to progress', 'calculator', 'tracker'],
      interaction_type: 'cross_system',
      interaction_summary: 'Ultimate Weapons Calculator Inputs and Filters, Ultimate Weapons Tracker and Calculator Link, and Ultimate Weapons Tracker Progress Planning Table explain how a calculator plan becomes saved tracker progress.',
      paragraphs: [
        'Ultimate Weapons Calculator Inputs and Filters explains the editable start-and-target plan, Ultimate Weapons Tracker and Calculator Link explains the shared state between both pages, and Ultimate Weapons Tracker Progress Planning Table explains where that saved plan becomes visible and useful as tracked progress.',
        'That matters because users often want to know whether the calculator is only a temporary lookup or part of the tracker workflow.',
        'The clearest answer is to name those mechanics directly: Save to Progress is the bridge from calculator planning into the tracker’s saved progress table.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_uw_faq_upload_01',
      source: 'Ultimate Weapons Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Can I import Ultimate Weapons from screenshots?',
      title: 'Can I import Ultimate Weapons from screenshots?',
      disambiguation: 'This chunk is about the interaction between Ultimate Weapons Tracker Overview and Ultimate Weapons Tracker Upload Placeholder, not the individual mechanics or a future roadmap promise.',
      mechanics: ['Ultimate Weapons Tracker Overview', 'Ultimate Weapons Tracker Upload Placeholder'],
      tags: ['trackerai', 'ultimate weapons', 'faq', 'upload', 'ocr', 'screenshots'],
      interaction_type: 'conditional',
      interaction_summary: 'Ultimate Weapons Tracker Overview and Ultimate Weapons Tracker Upload Placeholder explain that the page includes an Upload tab but does not currently provide a working OCR import flow.',
      paragraphs: [
        'Ultimate Weapons Tracker Overview explains where the Upload tab sits on the page, and Ultimate Weapons Tracker Upload Placeholder explains that Ultimate Weapon OCR is not available yet.',
        'That means the honest answer is a boundary answer, not a workaround disguised as a feature.',
        'The clearest answer is to name that mechanic directly: the tracker has an Upload placeholder, but screenshot import is not currently available for Ultimate Weapons.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_uw_faq_sync_01',
      source: 'Ultimate Weapons Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Does the Ultimate Weapons tracker save and sync with the calculator?',
      title: 'Does the Ultimate Weapons tracker save and sync with the calculator?',
      disambiguation: 'This chunk is about the interaction between Ultimate Weapons sync behavior and the shared tracker-calculator workflow, not a low-level store contract.',
      mechanics: ['Ultimate Weapons Tracker Local Save and Sync', 'Ultimate Weapons Tracker and Calculator Link', 'Ultimate Weapons Calculator Inputs and Filters'],
      tags: ['trackerai', 'ultimate weapons', 'faq', 'sync', 'shared state', 'calculator'],
      interaction_type: 'conditional',
      interaction_summary: 'Ultimate Weapons Tracker Local Save and Sync, Ultimate Weapons Tracker and Calculator Link, and Ultimate Weapons Calculator Inputs and Filters explain how the tracker persists state and why calculator context often follows it.',
      paragraphs: [
        'Ultimate Weapons Tracker Local Save and Sync explains the persistence layer, Ultimate Weapons Tracker and Calculator Link explains the shared-state relationship, and Ultimate Weapons Calculator Inputs and Filters explains the practical calculator context users see being reused.',
        'That is why the calculator often feels like it already knows the weapon plan the tracker was using.',
        'The cleanest answer is to name those mechanics directly: use the sync chunk for persistence, then use the tracker-calculator link for how that saved context carries into the calculator.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_uw_faq_ai_01',
      source: 'Ultimate Weapons Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do with the Ultimate Weapons tracker and calculator?',
      title: 'What can TrackerAI help me do with the Ultimate Weapons tracker and calculator?',
      disambiguation: 'This chunk is about the interaction between Ultimate Weapons page knowledge and TrackerAI help boundaries, not unrestricted bulk edits or sync control.',
      mechanics: ['Ultimate Weapons Tracker Overview', 'Ultimate Weapons Calculator Overview', 'Ultimate Weapons Tracker and Calculator Link', 'Ultimate Weapons Tracker and Calculator AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'ultimate weapons', 'faq', 'ai help', 'tracker', 'calculator'],
      interaction_type: 'conditional',
      interaction_summary: 'Ultimate Weapons Tracker Overview, Ultimate Weapons Calculator Overview, Ultimate Weapons Tracker and Calculator Link, Ultimate Weapons Tracker and Calculator AI Help Coverage, and TrackerAI Safety Guardrails define the kinds of page help the assistant can give without pretending it should silently rewrite tracked progress.',
      paragraphs: [
        'Ultimate Weapons Tracker Overview and Ultimate Weapons Calculator Overview provide the two page contexts, Ultimate Weapons Tracker and Calculator Link explains why users move between them, and Ultimate Weapons Tracker and Calculator AI Help Coverage explains why this is a strong explanation-and-guidance area for the assistant.',
        'This is where TrackerAI is most useful for normal users: deciding which page to use, understanding tracker estimate columns, and explaining why a calculator total and a tracker target are related.',
        'TrackerAI Safety Guardrails is the boundary that keeps that help honest, because explanation and interpretation are different from silently changing saved progress or sync decisions.',
      ],
    }),
  ]
}
