import {
  USER_RUNS_ADD_RUNS_FACTS,
  USER_RUNS_AI_FACTS,
  USER_RUNS_ANALYSIS_FACTS,
  USER_RUNS_GUILD_FACTS,
  USER_RUNS_MANAGE_FACTS,
  USER_RUNS_OVERVIEW_FACTS,
  USER_RUNS_SCREENSHOT_FACTS,
  USER_RUNS_SYNC_FACTS,
} from './trackerAiUserRunsSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiUserRunsCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_user_runs_overview_01',
      source: 'Run Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Run Tracker',
      title: 'Run Tracker Overview',
      disambiguation: 'This chunk is about the Run Tracker Overview mechanic itself, not its interactions. It is not a gameplay guide, a hidden admin tool, or a raw storage implementation note.',
      mechanics: ['Run Tracker Overview'],
      tags: ['trackerai', 'run tracker', 'site page', 'runs', 'overview'],
      paragraphs: [...USER_RUNS_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_user_runs_add_01',
      source: 'Run Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Adding Runs',
      title: 'Run Tracker Add Runs',
      disambiguation: 'This chunk is about the Run Tracker Add Runs mechanic itself, not its interactions. It is not a screenshot parser spec, a CSV schema dump, or a cloud API contract.',
      mechanics: ['Run Tracker Add Runs'],
      tags: ['trackerai', 'run tracker', 'add runs', 'ocr', 'paste', 'csv', 'manual'],
      paragraphs: [...USER_RUNS_ADD_RUNS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_user_runs_manage_01',
      source: 'Run Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Managing Runs',
      title: 'Run Tracker Manage Runs',
      disambiguation: 'This chunk is about the Run Tracker Manage Runs mechanic itself, not its interactions. It is not a moderation log, a raw database diff, or a hidden cleanup queue description.',
      mechanics: ['Run Tracker Manage Runs'],
      tags: ['trackerai', 'run tracker', 'edit', 'delete', 'export', 'bulk actions'],
      paragraphs: [...USER_RUNS_MANAGE_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_user_runs_analysis_01',
      source: 'Run Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Analysis',
      title: 'Run Tracker Analysis and Charts',
      disambiguation: 'This chunk is about the Run Tracker Analysis and Charts mechanic itself, not its interactions. It is not a stat formula guide or a promise that every chart answers every question automatically.',
      mechanics: ['Run Tracker Analysis and Charts'],
      tags: ['trackerai', 'run tracker', 'analysis', 'charts', 'timeline', 'filters'],
      paragraphs: [...USER_RUNS_ANALYSIS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_user_runs_guild_01',
      source: 'Run Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Guild Tab',
      title: 'Run Tracker Guild Tab',
      disambiguation: 'This chunk is about the Run Tracker Guild Tab mechanic itself, not its interactions. It is not a full guild rules page or an admin-only guild control panel.',
      mechanics: ['Run Tracker Guild Tab'],
      tags: ['trackerai', 'run tracker', 'guild', 'guild tab', 'leaderboard'],
      paragraphs: [...USER_RUNS_GUILD_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_user_runs_sync_01',
      source: 'Run Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Sync and Cloud',
      title: 'Run Tracker Sync and Cloud',
      disambiguation: 'This chunk is about the Run Tracker Sync and Cloud mechanic itself, not its interactions. It is not a backend architecture note or a guarantee that every save path is always online.',
      mechanics: ['Run Tracker Sync and Cloud'],
      tags: ['trackerai', 'run tracker', 'sync', 'cloud', 'local-first'],
      paragraphs: [...USER_RUNS_SYNC_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_user_runs_screenshots_01',
      source: 'Run Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Screenshots and Verification',
      title: 'Run Tracker Screenshots and Verification',
      disambiguation: 'This chunk is about the Run Tracker Screenshots and Verification mechanic itself, not its interactions. It is not a promise that every screenshot will parse perfectly or that every run becomes leaderboard-ready automatically.',
      mechanics: ['Run Tracker Screenshots and Verification'],
      tags: ['trackerai', 'run tracker', 'screenshots', 'verification', 'ocr', 'leaderboard'],
      paragraphs: [...USER_RUNS_SCREENSHOT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_user_runs_ai_01',
      source: 'Run Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on Run Tracker',
      title: 'Run Tracker AI Help Coverage',
      disambiguation: 'This chunk is about the Run Tracker AI Help Coverage mechanic itself, not its interactions. It is not a hidden command list or a claim that the assistant should act without guardrails.',
      mechanics: ['Run Tracker AI Help Coverage'],
      tags: ['trackerai', 'run tracker', 'ai help', 'questions', 'actions'],
      paragraphs: [...USER_RUNS_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_user_runs_faq_add_01',
      source: 'Run Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I add a run in Run Tracker?',
      title: 'How do I add a run in Run Tracker?',
      disambiguation: 'This chunk is about the interaction between the main Run Tracker page and its run-entry methods, not a raw OCR parser reference or a full screenshot review spec.',
      mechanics: ['Run Tracker Overview', 'Run Tracker Add Runs', 'Run Tracker Screenshots and Verification'],
      tags: ['trackerai', 'run tracker', 'faq', 'add run', 'ocr', 'manual'],
      interaction_type: 'cross_system',
      interaction_summary: 'Run Tracker Overview, Run Tracker Add Runs, and Run Tracker Screenshots and Verification fit together to answer the most common add-run question: which input method makes the most sense for the material the user already has.',
      paragraphs: [
        'Run Tracker Overview explains that this page is the main home for logging and reviewing runs, while Run Tracker Add Runs breaks down the practical entry choices such as screenshot OCR, pasted summary, CSV import, fast upload, and manual entry.',
        'Run Tracker Screenshots and Verification is the part that tells users why screenshots can matter beyond convenience: they help with OCR, review, and stronger confidence in what was uploaded.',
        'Taken together, those three mechanics answer the user-facing question clearly: start with the easiest source you already have, review extracted values before saving, and use screenshots when you want OCR help or stronger verification support.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_user_runs_faq_analysis_01',
      source: 'Run Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can I do in the Run Tracker Analysis tab?',
      title: 'What can I do in the Run Tracker Analysis tab?',
      disambiguation: 'This chunk is about the interaction between Run Tracker overview and Run Tracker analysis features, not a niche chart-configuration reference.',
      mechanics: ['Run Tracker Overview', 'Run Tracker Analysis and Charts'],
      tags: ['trackerai', 'run tracker', 'faq', 'analysis', 'charts', 'timeline'],
      interaction_type: 'cross_system',
      interaction_summary: 'Run Tracker Overview and Run Tracker Analysis and Charts work together so saved runs can be turned into trends, summaries, and visual comparisons instead of staying trapped in a raw table.',
      paragraphs: [
        'Run Tracker Overview establishes that the page is more than a logbook, and Run Tracker Analysis and Charts is the part that turns stored runs into averages, charts, trend views, and filterable comparisons.',
        'Users usually care about questions like whether their averages are improving, which tier is performing best, or how coins per hour changed over time. Run Tracker Analysis and Charts exists for exactly that kind of question.',
        'For AI help, this relationship matters because the assistant can use Run Tracker Overview to orient the user, then lean on Run Tracker Analysis and Charts to explain chart behavior, filters, and what changed between groups of runs.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_user_runs_faq_sync_01',
      source: 'Run Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Will my Run Tracker data sync or stay local?',
      title: 'Will my Run Tracker data sync or stay local?',
      disambiguation: 'This chunk is about the interaction between Run Tracker page usage and Run Tracker sync behavior, not a backend replication diagram or account-admin access rule.',
      mechanics: ['Run Tracker Overview', 'Run Tracker Sync and Cloud'],
      tags: ['trackerai', 'run tracker', 'faq', 'sync', 'cloud', 'guest'],
      interaction_type: 'conditional',
      interaction_summary: 'Run Tracker Overview and Run Tracker Sync and Cloud explain the two-part user story: the page is local-first for convenience, but signed-in users can also load, save, and sync cloud data when they want account-backed continuity.',
      paragraphs: [
        'Run Tracker Overview tells the user what the page is for, and Run Tracker Sync and Cloud explains how that same page can either stay local or participate in account-backed sync depending on sign-in state and user choice.',
        'That matters because users often worry about losing local progress or overwriting data. Run Tracker Sync and Cloud addresses that by separating load, save, and sync choices instead of hiding everything behind one vague button.',
        'For AI answers, this bridge is useful because it frames the conversation around the actual user concern: are they asking about local-only use, account sync, or the difference between loading cloud data and saving local changes up to the cloud?',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_user_runs_faq_guilds_01',
      source: 'Run Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How does Run Tracker connect to guilds?',
      title: 'How does Run Tracker connect to guilds?',
      disambiguation: 'This chunk is about the interaction between Run Tracker and its guild-facing tab, not a full guild management manual or private guild moderation record.',
      mechanics: ['Run Tracker Overview', 'Run Tracker Guild Tab'],
      tags: ['trackerai', 'run tracker', 'faq', 'guilds', 'guild tab'],
      interaction_type: 'cross_system',
      interaction_summary: 'Run Tracker Overview and Run Tracker Guild Tab connect personal run tracking to guild-facing workflows when guild features are enabled.',
      paragraphs: [
        'Run Tracker Overview makes it clear that the main page is the home for run data, and Run Tracker Guild Tab explains how that same run data can be reused for guild-related views when the feature is enabled.',
        'Users do not need to think of Run Tracker Guild Tab as a separate app. It is part of the same Run Tracker experience when guilds are turned on in settings.',
        'If the Guild tab is missing, the friendly explanation should name the mechanic directly: Run Tracker Guild Tab is hidden because guild features are turned off, not because the user is on the wrong page.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_user_runs_faq_ai_01',
      source: 'Run Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do on the Run Tracker page?',
      title: 'What can TrackerAI help me do on the Run Tracker page?',
      disambiguation: 'This chunk is about the interaction between Run Tracker page knowledge and TrackerAI help coverage, not hidden commands or unrestricted automation.',
      mechanics: ['Run Tracker Overview', 'Run Tracker Manage Runs', 'Run Tracker Analysis and Charts', 'Run Tracker AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'run tracker', 'faq', 'ai help', 'page actions'],
      interaction_type: 'conditional',
      interaction_summary: 'Run Tracker Overview, Run Tracker Manage Runs, Run Tracker Analysis and Charts, Run Tracker AI Help Coverage, and TrackerAI Safety Guardrails together define what the assistant can help with on this page and where it should slow down.',
      paragraphs: [
        'Run Tracker Overview is the starting point, Run Tracker Manage Runs covers edits and day-to-day record handling, and Run Tracker Analysis and Charts covers interpretation help for charts, summaries, and filters.',
        'Run Tracker AI Help Coverage then explains why this page is a good fit for conversational help, especially when the user wants practical guidance rather than a raw data dump.',
        'TrackerAI Safety Guardrails is the boundary that keeps the answer honest: reading, explaining, and normal field updates are easier to help with directly, while creating new records or deleting records should be handled more carefully.',
      ],
    }),
  ]
}
