import {
  RELICS_TRACKER_AI_FACTS,
  RELICS_TRACKER_BATCH_FACTS,
  RELICS_TRACKER_MERGE_FACTS,
  RELICS_TRACKER_OVERVIEW_FACTS,
  RELICS_TRACKER_PROGRESS_FACTS,
  RELICS_TRACKER_RELICS_TAB_FACTS,
  RELICS_TRACKER_SYNC_FACTS,
  RELICS_TRACKER_THEMES_FACTS,
  RELICS_TRACKER_TOTALS_FACTS,
  RELICS_TRACKER_UI_FACTS,
} from './trackerAiRelicsSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiRelicsCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_relics_overview_01',
      source: 'Relics Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Relics and Themes Tracker',
      title: 'Relics and Themes Tracker Overview',
      disambiguation: 'This chunk describes the Relics and Themes Tracker Overview mechanic itself, not its interactions. It is not the general relic encyclopedia or event-shop explanation outside the tracker page.',
      mechanics: ['Relics and Themes Tracker Overview'],
      tags: ['trackerai', 'relics', 'themes', 'tracker', 'site page', 'overview'],
      paragraphs: [...RELICS_TRACKER_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_relics_progress_01',
      source: 'Relics Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Progress Panels',
      title: 'Relics Tracker Progress Panels',
      disambiguation: 'This chunk describes the Relics Tracker Progress Panels mechanic itself, not its interactions. It is not the relic browser or the themes browsing tab.',
      mechanics: ['Relics Tracker Progress Panels'],
      tags: ['trackerai', 'relics', 'themes', 'tracker', 'progress', 'panels'],
      paragraphs: [...RELICS_TRACKER_PROGRESS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_relics_totals_01',
      source: 'Relics Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Total Bonuses Panel',
      title: 'Relics Tracker Total Bonuses Panel',
      disambiguation: 'This chunk describes the Relics Tracker Total Bonuses Panel mechanic itself, not its interactions. It is not a separate relic calculator or a raw data dump of every bonus source.',
      mechanics: ['Relics Tracker Total Bonuses Panel'],
      tags: ['trackerai', 'relics', 'themes', 'tracker', 'totals', 'bonuses'],
      paragraphs: [...RELICS_TRACKER_TOTALS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_relics_relics_tab_01',
      source: 'Relics Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Relics Tab',
      title: 'Relics Tracker Relics Tab',
      disambiguation: 'This chunk describes the Relics Tracker Relics Tab mechanic itself, not its interactions. It is not the progress summary or the themes browsing tab.',
      mechanics: ['Relics Tracker Relics Tab'],
      tags: ['trackerai', 'relics', 'tracker', 'browser', 'selection', 'filters'],
      paragraphs: [...RELICS_TRACKER_RELICS_TAB_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_relics_themes_tab_01',
      source: 'Relics Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Themes and Skins Tab',
      title: 'Relics Tracker Themes and Skins Tab',
      disambiguation: 'This chunk describes the Relics Tracker Themes and Skins Tab mechanic itself, not its interactions. It is not the relic browser or a generic themes catalog outside the tracker.',
      mechanics: ['Relics Tracker Themes and Skins Tab'],
      tags: ['trackerai', 'themes', 'skins', 'tracker', 'browser', 'collection'],
      paragraphs: [...RELICS_TRACKER_THEMES_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_relics_batch_01',
      source: 'Relics Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Bulk Add Workflow',
      title: 'Relics Tracker Bulk Add Workflow',
      disambiguation: 'This chunk describes the Relics Tracker Bulk Add Workflow mechanic itself, not its interactions. It is not a generic multi-select pattern outside the relics and themes page.',
      mechanics: ['Relics Tracker Bulk Add Workflow'],
      tags: ['trackerai', 'relics', 'themes', 'tracker', 'bulk add', 'selection'],
      paragraphs: [...RELICS_TRACKER_BATCH_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_relics_sync_01',
      source: 'Relics Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Local Save and Sync',
      title: 'Relics Tracker Local Save and Sync',
      disambiguation: 'This chunk describes the Relics Tracker Local Save and Sync mechanic itself, not its interactions. It is not a low-level cloud-save protocol dump.',
      mechanics: ['Relics Tracker Local Save and Sync'],
      tags: ['trackerai', 'relics', 'themes', 'tracker', 'sync', 'local save'],
      paragraphs: [...RELICS_TRACKER_SYNC_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_relics_merge_01',
      source: 'Relics Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Merge Restore Behavior',
      title: 'Relics Tracker Merge Restore Behavior',
      disambiguation: 'This chunk describes the Relics Tracker Merge Restore Behavior mechanic itself, not its interactions. It is not a promise that every sync path always merges instead of asking the user.',
      mechanics: ['Relics Tracker Merge Restore Behavior'],
      tags: ['trackerai', 'relics', 'themes', 'tracker', 'sync', 'merge'],
      paragraphs: [...RELICS_TRACKER_MERGE_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_relics_ui_01',
      source: 'Relics Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Saved UI State',
      title: 'Relics Tracker Saved UI State',
      disambiguation: 'This chunk describes the Relics Tracker Saved UI State mechanic itself, not its interactions. It is not a cloud conflict policy or a general browser preference system outside this tracker.',
      mechanics: ['Relics Tracker Saved UI State'],
      tags: ['trackerai', 'relics', 'themes', 'tracker', 'ui state', 'tabs'],
      paragraphs: [...RELICS_TRACKER_UI_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_relics_ai_01',
      source: 'Relics Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on Relics Tracker',
      title: 'Relics Tracker AI Help Coverage',
      disambiguation: 'This chunk describes the Relics Tracker AI Help Coverage mechanic itself, not its interactions. It is not unrestricted bulk editing or silent resets.',
      mechanics: ['Relics Tracker AI Help Coverage'],
      tags: ['trackerai', 'relics', 'themes', 'ai help', 'tracker'],
      paragraphs: [...RELICS_TRACKER_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_relics_faq_use_01',
      source: 'Relics Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I use the Relics and Themes tracker page?',
      title: 'How do I use the Relics and Themes tracker page?',
      disambiguation: 'This chunk is about the interaction between the main relics tracker tabs, not the deeper game meaning of individual relics or theme bonuses.',
      mechanics: ['Relics and Themes Tracker Overview', 'Relics Tracker Progress Panels', 'Relics Tracker Relics Tab', 'Relics Tracker Themes and Skins Tab'],
      tags: ['trackerai', 'relics', 'themes', 'faq', 'tracker', 'tabs'],
      interaction_type: 'cross_system',
      interaction_summary: 'Relics and Themes Tracker Overview, Relics Tracker Progress Panels, Relics Tracker Relics Tab, and Relics Tracker Themes and Skins Tab explain how the page splits progress review from relic browsing and theme collection browsing.',
      paragraphs: [
        'Relics and Themes Tracker Overview explains the page as a whole, Relics Tracker Progress Panels explains the collection-progress view, Relics Tracker Relics Tab explains the relic browser, and Relics Tracker Themes and Skins Tab explains the theme collection browser.',
        'That matters because users often know they want to mark collection progress without yet knowing which tab owns the right action.',
        'The clearest answer is to name those mechanics directly: use Progress to review collected status and bulk removals, use Relics to browse and mark relic collection, and use Themes and Skins to browse and mark theme collection.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_relics_faq_bulk_add_01',
      source: 'Relics Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why does Select all not add everything immediately?',
      title: 'Why does Select all not add everything immediately?',
      disambiguation: 'This chunk is about the interaction between search and filter state and the staged bulk-add workflow, not a bug claim that the button is broken.',
      mechanics: ['Relics Tracker Relics Tab', 'Relics Tracker Themes and Skins Tab', 'Relics Tracker Bulk Add Workflow'],
      tags: ['trackerai', 'relics', 'themes', 'faq', 'bulk add', 'selection'],
      interaction_type: 'conditional',
      interaction_summary: 'Relics Tracker Relics Tab, Relics Tracker Themes and Skins Tab, and Relics Tracker Bulk Add Workflow explain why the page stages a visible selection first before committing a bulk add.',
      paragraphs: [
        'Relics Tracker Relics Tab and Relics Tracker Themes and Skins Tab explain where the bulk-select controls live, and Relics Tracker Bulk Add Workflow explains that Select all is intentionally a staging step before the actual add action.',
        'That is why the first click can populate a selection without instantly marking every visible item collected.',
        'The clearest answer is to name those mechanics directly: Select all prepares the current visible uncollected set so the user can review or trim it, and Add selected is the commit step that actually writes collection progress.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_relics_faq_totals_01',
      source: 'Relics Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Why does the Total Bonuses panel change when I switch tabs?',
      title: 'Why does the Total Bonuses panel change when I switch tabs?',
      disambiguation: 'This chunk is about the interaction between the active tracker tab and the shared totals panel, not a bug report about bonus values changing at random.',
      mechanics: ['Relics and Themes Tracker Overview', 'Relics Tracker Total Bonuses Panel', 'Relics Tracker Themes and Skins Tab'],
      tags: ['trackerai', 'relics', 'themes', 'faq', 'totals', 'bonuses'],
      interaction_type: 'conditional',
      interaction_summary: 'Relics and Themes Tracker Overview, Relics Tracker Total Bonuses Panel, and Relics Tracker Themes and Skins Tab explain why the totals area pivots to match the active relic or theme context.',
      paragraphs: [
        'Relics and Themes Tracker Overview explains the multi-tab workspace, Relics Tracker Total Bonuses Panel explains that the panel is context-sensitive, and Relics Tracker Themes and Skins Tab explains why theme totals are handled differently from relic-only totals.',
        'That is why the numbers can legitimately change when the user changes tabs without any collection data being lost.',
        'The clearest answer is to name those mechanics directly: the totals panel is designed to summarize the current tracker context, so it intentionally switches between collected progress totals, all-relic totals, and theme summaries.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_relics_faq_sync_01',
      source: 'Relics Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Does the relics tracker sync both relics and themes?',
      title: 'Does the relics tracker sync both relics and themes?',
      disambiguation: 'This chunk is about the interaction between relic collection, theme collection, and tracker sync behavior, not a low-level cloud-save API contract.',
      mechanics: ['Relics and Themes Tracker Overview', 'Relics Tracker Local Save and Sync', 'Relics Tracker Saved UI State'],
      tags: ['trackerai', 'relics', 'themes', 'faq', 'sync', 'ui state'],
      interaction_type: 'conditional',
      interaction_summary: 'Relics and Themes Tracker Overview, Relics Tracker Local Save and Sync, and Relics Tracker Saved UI State explain why syncing the page preserves both collection state and browsing preferences.',
      paragraphs: [
        'Relics and Themes Tracker Overview explains that the tracker manages both relics and themes in one workspace, Relics Tracker Local Save and Sync explains the collection-sync behavior, and Relics Tracker Saved UI State explains that browsing preferences are also part of the saved page state.',
        'That is why a synced restore can bring back both collected relics and collected themes together with the page preferences the user was using.',
        'The clearest answer is to name those mechanics directly: the relics tracker syncs both relic and theme collection state, and it also preserves the saved page UI context around them.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_relics_faq_merge_01',
      source: 'Relics Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What happens if my local relic progress and cloud progress both have data?',
      title: 'What happens if my local relic progress and cloud progress both have data?',
      disambiguation: 'This chunk is about the interaction between local-first restore, automatic cloud load, and explicit sync conflict choices, not a guarantee that every mismatch resolves the same way.',
      mechanics: ['Relics Tracker Local Save and Sync', 'Relics Tracker Merge Restore Behavior', 'Relics Tracker Saved UI State'],
      tags: ['trackerai', 'relics', 'themes', 'faq', 'merge', 'sync'],
      interaction_type: 'conditional',
      interaction_summary: 'Relics Tracker Local Save and Sync, Relics Tracker Merge Restore Behavior, and Relics Tracker Saved UI State explain why this tracker can restore additively while still preserving explicit sync decisions and page context.',
      paragraphs: [
        'Relics Tracker Local Save and Sync explains the conflict-aware restore and save model, Relics Tracker Merge Restore Behavior explains the additive auto-load path, and Relics Tracker Saved UI State explains why the restored workspace includes browsing preferences as well as collection state.',
        'That means local and cloud progress do not always behave like a simple overwrite race when both sides already contain valid relic and theme data.',
        'The clearest answer is to name those mechanics directly: automatic restore can merge the local and remote collected sets, while manual conflict prompts still let the user explicitly choose load or save behavior when needed.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_relics_faq_ai_01',
      source: 'Relics Tracker Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do with the Relics tracker?',
      title: 'What can TrackerAI help me do with the Relics tracker?',
      disambiguation: 'This chunk is about the interaction between relics-tracker page knowledge and TrackerAI help boundaries, not unrestricted bulk edits or silent resets.',
      mechanics: ['Relics and Themes Tracker Overview', 'Relics Tracker AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'relics', 'themes', 'faq', 'ai help', 'tracker'],
      interaction_type: 'conditional',
      interaction_summary: 'Relics and Themes Tracker Overview, Relics Tracker AI Help Coverage, and TrackerAI Safety Guardrails define the kinds of relics-tracker help the assistant can give without pretending it should silently rewrite collection data.',
      paragraphs: [
        'Relics and Themes Tracker Overview provides the page context, and Relics Tracker AI Help Coverage explains why this is a strong explanation-and-guidance area for the assistant.',
        'This is where TrackerAI is most useful for normal users: clarifying which tab to use, explaining why totals change by tab, and helping interpret how collected relics and collected themes affect the tracker summaries.',
        'TrackerAI Safety Guardrails is the boundary that keeps that help honest, because explanation and interpretation are different from silently removing collected items or forcing a sync decision on the user\'s behalf.',
      ],
    }),
  ]
}
