import {
  UPTIME_CALCULATOR_AI_FACTS,
  UPTIME_CALCULATOR_COLUMNS_FACTS,
  UPTIME_CALCULATOR_INPUT_FACTS,
  UPTIME_CALCULATOR_OVERVIEW_FACTS,
  UPTIME_CALCULATOR_PERSISTENCE_FACTS,
  UPTIME_CALCULATOR_RESET_FACTS,
  UPTIME_CALCULATOR_RESULTS_FACTS,
  UPTIME_CALCULATOR_VISUALIZER_FACTS,
} from './trackerAiUptimeSource'
import { buildAtomicKbChunk, buildRelationalKbChunk, type KBChunkRecord } from './shared'

export function buildTrackerAiUptimeCanonicalKbChunks(): KBChunkRecord[] {
  return [
    buildAtomicKbChunk({
      chunk_id: 'trackerai_uptime_overview_01',
      source: 'Uptime Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Uptime Calculator Workspace',
      title: 'Uptime Calculator Workspace Overview',
      disambiguation: 'This chunk describes the Uptime Calculator Workspace Overview mechanic itself, not its interactions. It is not the lower-level Ultimate Weapon encyclopedia or a generic sync theory article.',
      mechanics: ['Uptime Calculator Workspace Overview'],
      tags: ['trackerai', 'uptime', 'calculator', 'site page', 'overview'],
      paragraphs: [...UPTIME_CALCULATOR_OVERVIEW_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_uptime_inputs_01',
      source: 'Uptime Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Grouped Input Panels',
      title: 'Uptime Calculator Grouped Input Panels',
      disambiguation: 'This chunk describes the Uptime Calculator Grouped Input Panels mechanic itself, not its interactions. It is not the results table or visualizer output.',
      mechanics: ['Uptime Calculator Grouped Input Panels'],
      tags: ['trackerai', 'uptime', 'calculator', 'inputs', 'weapons', 'bots', 'guardians'],
      paragraphs: [...UPTIME_CALCULATOR_INPUT_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_uptime_reset_01',
      source: 'Uptime Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Reset All Inputs',
      title: 'Uptime Calculator Reset All Inputs',
      disambiguation: 'This chunk describes the Uptime Calculator Reset All Inputs mechanic itself, not its interactions. It is not a site-wide data reset.',
      mechanics: ['Uptime Calculator Reset All Inputs'],
      tags: ['trackerai', 'uptime', 'calculator', 'reset', 'workspace'],
      paragraphs: [...UPTIME_CALCULATOR_RESET_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_uptime_results_01',
      source: 'Uptime Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Results Table',
      title: 'Uptime Calculator Results Table',
      disambiguation: 'This chunk describes the Uptime Calculator Results Table mechanic itself, not its interactions. It is not the visualizer canvas or raw source formulas.',
      mechanics: ['Uptime Calculator Results Table'],
      tags: ['trackerai', 'uptime', 'calculator', 'results', 'table', 'rows'],
      paragraphs: [...UPTIME_CALCULATOR_RESULTS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_uptime_columns_01',
      source: 'Uptime Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Results Columns',
      title: 'Uptime Calculator Results Columns',
      disambiguation: 'This chunk describes the Uptime Calculator Results Columns mechanic itself, not its interactions. It is not a statement that all columns are always visible.',
      mechanics: ['Uptime Calculator Results Columns'],
      tags: ['trackerai', 'uptime', 'calculator', 'columns', 'results'],
      paragraphs: [...UPTIME_CALCULATOR_COLUMNS_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_uptime_visualizer_01',
      source: 'Uptime Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Activation Visualizer',
      title: 'Uptime Calculator Activation Visualizer',
      disambiguation: 'This chunk describes the Uptime Calculator Activation Visualizer mechanic itself, not its interactions. It is not the main results table or a static screenshot explanation.',
      mechanics: ['Uptime Calculator Activation Visualizer'],
      tags: ['trackerai', 'uptime', 'calculator', 'chart', 'visualizer', 'sync'],
      paragraphs: [...UPTIME_CALCULATOR_VISUALIZER_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_uptime_persistence_01',
      source: 'Uptime Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'Saved Calculator State',
      title: 'Uptime Calculator Saved Calculator State',
      disambiguation: 'This chunk describes the Uptime Calculator Saved Calculator State mechanic itself, not its interactions. It is not a cloud-sync contract or a claim that every calculator shares the same storage record.',
      mechanics: ['Uptime Calculator Saved Calculator State'],
      tags: ['trackerai', 'uptime', 'calculator', 'saved state', 'dexie', 'local'],
      paragraphs: [...UPTIME_CALCULATOR_PERSISTENCE_FACTS],
    }),
    buildAtomicKbChunk({
      chunk_id: 'trackerai_uptime_ai_01',
      source: 'Uptime Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'AI Help on Uptime Calculator',
      title: 'Uptime Calculator AI Help Coverage',
      disambiguation: 'This chunk describes the Uptime Calculator AI Help Coverage mechanic itself, not its interactions. It is not unrestricted batch editing or silent resets.',
      mechanics: ['Uptime Calculator AI Help Coverage'],
      tags: ['trackerai', 'uptime', 'calculator', 'ai help'],
      paragraphs: [...UPTIME_CALCULATOR_AI_FACTS],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_uptime_faq_use_01',
      source: 'Uptime Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'How do I use the Uptime calculator?',
      title: 'How do I use the Uptime calculator?',
      disambiguation: 'This chunk is about the interaction between the main uptime calculator surfaces, not the deeper theory of Ultimate Weapon sync outside the page.',
      mechanics: ['Uptime Calculator Workspace Overview', 'Uptime Calculator Grouped Input Panels', 'Uptime Calculator Results Table', 'Uptime Calculator Activation Visualizer'],
      tags: ['trackerai', 'uptime', 'faq', 'calculator', 'workflow'],
      interaction_type: 'cross_system',
      interaction_summary: 'Uptime Calculator Workspace Overview, Uptime Calculator Grouped Input Panels, Uptime Calculator Results Table, and Uptime Calculator Activation Visualizer explain how the page moves from scenario input to numeric comparison to overlap visualization.',
      paragraphs: [
        'Uptime Calculator Workspace Overview explains the page as a whole, Uptime Calculator Grouped Input Panels explains where scenario inputs live, Uptime Calculator Results Table explains the numeric comparison surface, and Uptime Calculator Activation Visualizer explains the overlap-analysis chart.',
        'That matters because users often know they want a better sync answer without yet knowing whether the best evidence will be a table comparison or a visual overlap view.',
        'The clearest answer is to name those mechanics directly: build the scenario in the grouped inputs, read the detailed output in the results table, and use the visualizer when the question is really about overlap timing across activations.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_uptime_faq_table_vs_chart_01',
      source: 'Uptime Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What is the difference between the Uptime results table and the visualizer?',
      title: 'What is the difference between the Uptime results table and the visualizer?',
      disambiguation: 'This chunk is about the interaction between the results table and the visualizer, not a claim that one of them is redundant.',
      mechanics: ['Uptime Calculator Results Table', 'Uptime Calculator Results Columns', 'Uptime Calculator Activation Visualizer'],
      tags: ['trackerai', 'uptime', 'faq', 'results', 'visualizer', 'chart'],
      interaction_type: 'cross_system',
      interaction_summary: 'Uptime Calculator Results Table, Uptime Calculator Results Columns, and Uptime Calculator Activation Visualizer explain why the page offers both dense numeric outputs and an overlap-focused chart.',
      paragraphs: [
        'Uptime Calculator Results Table explains the row-by-row numeric output, Uptime Calculator Results Columns explains how that numeric view can be tailored, and Uptime Calculator Activation Visualizer explains the timing-and-overlap chart.',
        'That is why the tool keeps both surfaces instead of forcing all uptime interpretation into one representation.',
        'The clearest answer is to name those mechanics directly: use the table for exact cooldown, duration, uptime, and perma-style comparisons, and use the visualizer for seeing how activation timing lines up over repeated cycles.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_uptime_faq_reset_01',
      source: 'Uptime Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What does Reset All Inputs do on the Uptime calculator?',
      title: 'What does Reset All Inputs do on the Uptime calculator?',
      disambiguation: 'This chunk is about the interaction between the saved calculator workspace and the reset action, not a site-wide destructive reset.',
      mechanics: ['Uptime Calculator Workspace Overview', 'Uptime Calculator Reset All Inputs', 'Uptime Calculator Saved Calculator State'],
      tags: ['trackerai', 'uptime', 'faq', 'reset', 'saved state'],
      interaction_type: 'conditional',
      interaction_summary: 'Uptime Calculator Workspace Overview, Uptime Calculator Reset All Inputs, and Uptime Calculator Saved Calculator State explain why the reset clears the current modeled scenario instead of unrelated tracker data.',
      paragraphs: [
        'Uptime Calculator Workspace Overview explains that the page is one saved calculator workspace, Uptime Calculator Reset All Inputs explains the reset action itself, and Uptime Calculator Saved Calculator State explains why that action matters for a persisted local model.',
        'That is why the reset should be understood as clearing the current uptime scenario rather than deleting progress from some other page.',
        'The clearest answer is to name those mechanics directly: Reset All Inputs restores the uptime calculator workspace to its defaults and replaces the previously saved local modeling state for that page.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_uptime_faq_saved_01',
      source: 'Uptime Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What does the Uptime calculator remember between visits?',
      title: 'What does the Uptime calculator remember between visits?',
      disambiguation: 'This chunk is about the interaction between the main calculator store and the visualizer store, not a cloud-sync guarantee.',
      mechanics: ['Uptime Calculator Saved Calculator State', 'Uptime Calculator Results Table', 'Uptime Calculator Activation Visualizer'],
      tags: ['trackerai', 'uptime', 'faq', 'saved state', 'visualizer', 'table'],
      interaction_type: 'cross_system',
      interaction_summary: 'Uptime Calculator Saved Calculator State, Uptime Calculator Results Table, and Uptime Calculator Activation Visualizer explain why both the numeric workspace and the chart setup can return with the page.',
      paragraphs: [
        'Uptime Calculator Saved Calculator State explains the persisted calculator and chart storage, Uptime Calculator Results Table explains the saved row and column workspace, and Uptime Calculator Activation Visualizer explains the separate persisted chart configuration.',
        'That means returning to the page can restore more than raw inputs alone.',
        'The clearest answer is to name those mechanics directly: the uptime calculator remembers the scenario inputs, row and column configuration, panel state, and the chart orientation, view, comparator, order, and styling setup.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_uptime_faq_dw_kill_wave_01',
      source: 'Uptime Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What does Include DW Kill Wave change in the Uptime calculator?',
      title: 'What does Include DW Kill Wave change in the Uptime calculator?',
      disambiguation: 'This chunk is about the interaction between the results table row settings and the shared visualizer model, not a generic Death Wave encyclopedia entry.',
      mechanics: ['Uptime Calculator Results Table', 'Uptime Calculator Activation Visualizer'],
      tags: ['trackerai', 'uptime', 'faq', 'death wave', 'kill wave', 'visualizer'],
      interaction_type: 'conditional',
      interaction_summary: 'Uptime Calculator Results Table and Uptime Calculator Activation Visualizer explain why the Death Wave kill-wave toggle changes both the numeric output and the overlap model shown in the chart.',
      paragraphs: [
        'Uptime Calculator Results Table explains where the Include DW Kill Wave toggle lives, and Uptime Calculator Activation Visualizer explains that the same uptime model drives the chart below.',
        'That is why changing this toggle is more than a cosmetic row preference. It changes how Death Wave duration is interpreted for the modeled uptime scenario.',
        'The clearest answer is to name those mechanics directly: Include DW Kill Wave switches the calculator between a shorter overlap-style Death Wave treatment and a fuller kill-wave-inclusive duration model that also feeds the visualizer.',
      ],
    }),
    buildRelationalKbChunk({
      chunk_id: 'trackerai_uptime_faq_ai_01',
      source: 'Uptime Calculator Site Knowledge Source',
      section: 'TrackerAI',
      topic: 'What can TrackerAI help me do with the Uptime calculator?',
      title: 'What can TrackerAI help me do with the Uptime calculator?',
      disambiguation: 'This chunk is about the interaction between uptime-calculator page knowledge and TrackerAI help boundaries, not unrestricted state mutation or silent resets.',
      mechanics: ['Uptime Calculator Workspace Overview', 'Uptime Calculator AI Help Coverage', 'TrackerAI Safety Guardrails'],
      tags: ['trackerai', 'uptime', 'faq', 'ai help', 'calculator'],
      interaction_type: 'conditional',
      interaction_summary: 'Uptime Calculator Workspace Overview, Uptime Calculator AI Help Coverage, and TrackerAI Safety Guardrails define the kinds of uptime-calculator guidance the assistant can give without pretending it should silently rewrite the entire model.',
      paragraphs: [
        'Uptime Calculator Workspace Overview provides the page context, and Uptime Calculator AI Help Coverage explains why this tool is a good fit for explanation, interpretation, and workflow guidance.',
        'This is where TrackerAI is most useful for normal users: clarifying which inputs matter for a sync question, explaining what the results table is showing, and helping interpret the visualizer when overlap timing is the real concern.',
        'TrackerAI Safety Guardrails is the boundary that keeps that help honest, because guidance and explanation are different from silently resetting the full calculator or rewriting a user\'s modeled scenario without clear intent.',
      ],
    }),
  ]
}
