export interface CardTemplate {
  id: string
  name: string
  // Static human-readable description of the card's effect (doesn't change per level)
  description: string
  rarity: 'common' | 'rare' | 'epic'
  // Type for all levels
  levelType: 'percent' | 'flat' | 'duration' | 'multi'
  // Numeric values for each level (index 0 -> level 1)
  levelValues: number[]
  // Name for mastery
  masteryName: string
  // Description for mastery
  masteryDescription: string
  // Type for all mastery levels
  masteryType: 'percent' | 'flat' | 'duration' | 'multi'
  // Numeric values for each mastery level (index 0 -> mastery 1)
  masteryValues: number[]
}

export const CARD_MAX_COPIES = 80 // Total copies required to reach max level (level 7)

export const RARITY_CHANCES = {
  common: 0.8,
  rare: 0.17,
  epic: 0.03,
} as const

export const CARD_LEVELS = [1, 2, 3, 4, 5, 6, 7] as const
export const CARD_MASTERY_LEVELS = [1, 2, 3, 4, 5, 6, 7, 8, 9] as const

const cardTemplates: CardTemplate[] = [
  {
    id: 'dmg',
    name: 'Damage',
    description: 'Increases tower damage by x',
    rarity: 'common',
    levelType: 'multi',
    levelValues: [1.5, 2, 2.4, 2.8, 3.2, 3.6, 4],
    masteryName: 'Damage+',
    masteryDescription: "Increases the card's stat multiplier",
    masteryType: 'multi',
    masteryValues: [1.4, 1.8, 2.2, 2.6, 3, 3.4, 3.8, 4.2, 4.6, 5],
  },
  {
    id: 'as',
    name: 'Attack Speed',
    description: 'Increases tower attack speed by x',
    rarity: 'common',
    levelType: 'multi',
    levelValues: [1.25, 1.4, 1.55, 1.7, 1.85, 2, 2.15],
    masteryName: 'Attack Speed+',
    masteryDescription: "Increases the card's stat multiplier",
    masteryType: 'multi',
    masteryValues: [1.03, 1.06, 1.09, 1.12, 1.15, 1.18, 1.21, 1.24, 1.27, 1.3],
  },
  {
    id: 'hp',
    name: 'Health',
    description: 'Increases the tower health by x',
    rarity: 'common',
    levelType: 'multi',
    levelValues: [1.5, 2, 2.4, 2.8, 3.2, 3.6, 4],
    masteryName: 'Health+',
    masteryDescription: "Increases the card's stat multiplier",
    masteryType: 'multi',
    masteryValues: [1.2, 1.4, 1.6, 1.8, 2, 2.2, 2.4, 2.6, 2.8, 3],
  },
  {
    id: 'regen',
    name: 'Health Regen',
    description: 'Increases the tower health regen by x /sec',
    rarity: 'common',
    levelType: 'multi',
    levelValues: [1.4, 1.6, 1.8, 2, 2.2, 2.4, 2.6],
    masteryName: 'Health Regen+',
    masteryDescription: "Increases the card's stat multiplier",
    masteryType: 'multi',
    masteryValues: [1.4, 1.8, 2.2, 2.6, 3, 3.4, 3.8, 4.2, 4.6, 5],
  },
  {
    id: 'range',
    name: 'Range',
    description: 'Increases the tower max range by x',
    rarity: 'common',
    levelType: 'multi',
    levelValues: [1.15, 1.2, 1.25, 1.3, 1.35, 1.4, 1.45],
    masteryName: 'Damage / Meter',
    masteryDescription: 'Adds an additional multiplier to increase Damage / Meter',
    masteryType: 'multi',
    masteryValues: [1.2, 1.4, 1.6, 1.8, 2, 2.2, 2.4, 2.6, 2.8, 3],
  },
  {
    id: 'cash',
    name: 'Cash',
    description: 'Increase all cash earned by x',
    rarity: 'common',
    levelType: 'multi',
    levelValues: [1.2, 1.4, 1.6, 1.8, 2, 2.2, 2.4],
    masteryName: 'Elite Farming',
    masteryDescription: 'Adds a chance for Elites to drop Reroll Dice',
    masteryType: 'percent',
    masteryValues: [0.4, 0.8, 1.2, 1.6, 2, 2.24, 2.8, 3.2, 3.6, 4],
  },
  {
    id: 'coins',
    name: 'Coins',
    description: 'Increase all coin earned by x',
    rarity: 'common',
    levelType: 'multi',
    levelValues: [1.15, 1.2, 1.25, 1.3, 1.35, 1.4, 1.45],
    masteryName: 'Coins+',
    masteryDescription: "Increases the card's stat multiplier",
    masteryType: 'multi',
    masteryValues: [1.03, 1.06, 1.09, 1.12, 1.15, 1.18, 1.21, 1.24, 1.27, 1.3],
  },
  {
    id: 'sa',
    name: 'Slow Aura',
    description: 'All enemies in tower range speed decreased by x%',
    rarity: 'common',
    levelType: 'percent',
    levelValues: [13, 16, 19, 22, 25, 28, 31],
    masteryName: 'Slow Attack',
    masteryDescription: 'Adds an additional time delay between attacks from slowed enemies',
    masteryType: 'percent',
    masteryValues: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50],
  },
  {
    id: 'crit-chance',
    name: 'Critical Chance',
    description: 'Increase critical chance by +x%',
    rarity: 'common',
    levelType: 'percent',
    levelValues: [5, 6, 7, 8, 9, 10, 11],
    masteryName: 'Slow Attack',
    masteryDescription: 'Adds an additional bonus to increase Crit Chance, Super Crit Chance and Super Crit Factor',
    masteryType: 'percent',
    masteryValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    id: 'eb',
    name: 'Enemy Balance',
    description: 'Increase enemies spawned each wave, cash earned per kill increased by x',
    rarity: 'common',
    levelType: 'multi',
    levelValues: [1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9],
    masteryName: 'Elite Balance',
    masteryDescription: 'Adds a chance to double spawn Elites',
    masteryType: 'percent',
    masteryValues: [6, 12, 18, 24, 30, 36, 42, 28, 54, 60],
  },
  {
    id: 'def',
    name: 'Extra Defense',
    description: 'Increase defense percent by +x',
    rarity: 'common',
    levelType: 'percent',
    levelValues: [5, 6, 7, 8, 9, 10, 11],
    masteryName: 'Extra Defense+',
    masteryDescription: "Increases the card's stat multiplier",
    masteryType: 'percent',
    masteryValues: [0.7, 1.4, 2.1, 2.8, 3.5, 4.2, 4.9, 5.6, 6.3, 7],
  },
  {
    id: 'fort',
    name: 'Fortress',
    description: 'Increase defense absolute by x',
    rarity: 'common',
    levelType: 'multi',
    levelValues: [1.3, 1.45, 1.6, 0.75, 1.9, 2.05, 2.2],
    masteryName: 'Fortress Walls',
    masteryDescription: 'Reduces Wall rebuild time',
    masteryType: 'duration',
    masteryValues: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
  },
  {
    id: 'freeups',
    name: 'Free Upgrades',
    description: 'Increases all free upgrade chances per wave by x%',
    rarity: 'rare',
    levelType: 'percent',
    levelValues: [4, 5, 6, 7, 8, 9, 10],
    masteryName: 'Locked Upgrade',
    masteryDescription: 'Adds a number of locked stats that are not impacted by free upgrades. This is set before the run starts, and cannot by changed mid run',
    masteryType: 'flat',
    masteryValues: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
  },
  {
    id: 'x-orb',
    name: 'Extra Orb',
    description: 'A spinning orb with a speed of x that destroys enemies on contact (except bosses)',
    rarity: 'rare',
    levelType: 'flat',
    levelValues: [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
    masteryName: 'Coin Orb',
    masteryDescription: 'Adds a coin bonus to enemies hit by orbs',
    masteryType: 'multi',
    masteryValues: [1.04, 1.08, 1.12, 1.16, 1.2, 1.24, 1.28, 1.32, 1.36, 1.4],
  },
  {
    id: 'pc',
    name: 'Plasma Cannon',
    description: 'Fire one big plasma shot at a boss, dropping its health by x%',
    rarity: 'rare',
    levelType: 'percent',
    levelValues: [30, 34, 38, 42, 46, 50, 54],
    masteryName: 'Elite Cannon',
    masteryDescription: 'Plasma Cannon fires at Elite enemies for a % reduction in damage',
    masteryType: 'percent',
    masteryValues: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50],
  },
  {
    id: 'crit-coin',
    name: 'Critical Coin',
    description: 'Basic enemies destroyed by critical damage have a chance of dropping coins of x%',
    rarity: 'rare',
    levelType: 'percent',
    levelValues: [15, 18, 21, 24, 27, 30, 33],
    masteryName: 'Double Coins',
    masteryDescription: 'Adds a chance to drop 2 coins instead of 1',
    masteryType: 'percent',
    masteryValues: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
  },
  {
    id: 'ws',
    name: 'Wave Skip',
    description: 'Gain a x% chance of skipping waves, while still earning cash and coins equal to x1.10 the value of the wave enemies',
    rarity: 'rare',
    levelType: 'percent',
    levelValues: [9, 10, 11, 13, 15, 17, 19],
    masteryName: 'Double Wave Skip',
    masteryDescription: 'Adds a distinct chance to double wave skip',
    masteryType: 'percent',
    masteryValues: [10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
  },
  {
    id: 'is',
    name: 'Intro Sprint',
    description: 'Waves increment by 10 for the first x waves or up to your highest wave, and no coins are earned during Intro Sprint',
    rarity: 'rare',
    levelType: 'flat',
    levelValues: [20, 30, 40, 50, 60, 80, 100],
    masteryName: 'Warp Speed',
    masteryDescription: 'Dramatically increase how many waves Intro Sprint stays active',
    masteryType: 'multi',
    masteryValues: [1.8, 3.6, 5.4, 7.2, 9, 10.8, 12.6, 14.4, 16.2, 18],
  },
  {
    id: 'lms',
    name: 'Land Mine Stun',
    description: 'Land mines have a 40% chance of stunning enemies for x sec (except bosses)',
    rarity: 'rare',
    levelType: 'duration',
    levelValues: [1.4, 1.8, 2.2, 2.6, 3, 3.4, 3.8],
    masteryName: 'Flashbang',
    masteryDescription: 'Causes enemies stunned by a Land Mine to have a chance to miss their attacks',
    masteryType: 'percent',
    masteryValues: [2.7, 5.4, 8.1, 10.8, 13.5, 16.2, 18.9, 21.6, 24.3, 27],
  },
  {
    id: 'rpc',
    name: 'Recovery Package Chance',
    description: 'Increases recovery package spawn chance by +x%',
    rarity: 'rare',
    levelType: 'percent',
    levelValues: [15, 18, 21, 24, 27, 30, 33],
    masteryName: 'Care Package',
    masteryDescription: 'Gives packages a chance to also deliver a common module',
    masteryType: 'percent',
    masteryValues: [0.4, 0.8, 1.2, 1.4, 1.8, 2.4, 2.8, 3.2, 3.6, 4],
  },
  {
    id: 'dr',
    name: 'Death Ray',
    description: 'A powerful ray that destroys enemies on contact (except bosses), with a duration of x sec',
    rarity: 'epic',
    levelType: 'duration',
    levelValues: [2.3, 2.7, 3.1, 3.5, 3.9, 4.4, 4.9],
    masteryName: 'Enhanced Ray',
    masteryDescription: 'Allows Death Ray a chance to partially pierce protector\'s shields',
    masteryType: 'percent',
    masteryValues: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50],
  },
  {
    id: 'en',
    name: 'Energy Net',
    description: 'Fires a special net at a boss immobilizing it for x sec',
    rarity: 'epic',
    levelType: 'duration',
    levelValues: [2.5, 2.8, 3.1, 3.4, 3.7, 4, 4.3],
    masteryName: 'Electrified Net',
    masteryDescription: 'Adds a damage multiplier to bosses while trapped by the net, lingers for 10s after',
    masteryType: 'multi',
    masteryValues: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
  },
  {
    id: 'st',
    name: 'Super Tower',
    description: 'The tower becomes super for 15 sec, tower projectile damage increased by x (30 sec cooldown)',
    rarity: 'epic',
    levelType: 'multi',
    levelValues: [4.75, 5.51, 6.27, 7.03, 7.79, 8.55, 9.5],
    masteryName: 'Ultimate Tower',
    masteryDescription: 'Causes 35% of card\'s multiplier effect to increase all Ultimate Weapon damage and decreases Super Tower Cooldown',
    masteryType: 'duration',
    masteryValues: [3, 6, 9, 12, 15, 18, 21, 24, 27, 30],
  },
  {
    id: 'sw',
    name: 'Second Wind',
    description: 'Revive the tower with half health once per round and creates an invincible shield for x sec',
    rarity: 'epic',
    levelType: 'duration',
    levelValues: [10,15,20,25,30,35,40],
    masteryName: 'Angel Wings',
    masteryDescription: 'Unlocks a lingering health regen buff when activated which lasts for 400 waves',
    masteryType: 'multi',
    masteryValues: [1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1, 10],
  },
  {
    id: 'dm',
    name: 'Demon Mode',
    description: 'Once per round, activate Demon Mode, inceasing the damage by x3 and becoming invincible for x sec',
    rarity: 'epic',
    levelType: 'duration',
    levelValues: [180, 200, 220, 240, 260, 280, 300],
    masteryName: 'Demon Revenge',
    masteryDescription: 'Unlocks a lingering damage buff when activated which lasts for 300 waves',
    masteryType: 'multi',
    masteryValues: [1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6],
  },
  {
    id: 'es',
    name: 'Energy Shield',
    description: 'Shield that ignores a single attack, replenishes after x min',
    rarity: 'epic',
    levelType: 'duration',
    levelValues: [20, 18, 16, 14, 12, 10, 8],
    masteryName: 'Repel',
    masteryDescription: 'Energy Shield activates a blast that repels all enemies back by a percent of tower max range and destroys all enemy projectiles. The charge times of Rays are reset.',
    masteryType: 'percent',
    masteryValues: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50],
  },
  {
    id: 'wa',
    name: 'Wave Accelerator',
    description: 'Reduce the cooldown between waves by x%',
    rarity: 'epic',
    levelType: 'percent',
    levelValues: [30, 34, 38, 42, 48, 50, 54],
    masteryName: 'Spawn Accelerator',
    masteryDescription: 'Increases the rate at which spawn rates accelerate causing more enemies to spawn in earlier waves',
    masteryType: 'percent',
    masteryValues: [110, 120, 130, 140, 150, 160, 170, 180, 190, 200],
  },
  {
    id: 'zerk',
    name: 'Berzerker',
    description: 'Increases damage by x% of total damage absorbed this round (max of x8 tower damage)',
    rarity: 'epic',
    levelType: 'percent',
    levelValues: [0.8, 0.9, 1, 1.1, 1.2, 1.3, 1.4],
    masteryName: 'Viking Funeral',
    masteryDescription: 'Increases the damage cap to x500 for a duration when Death Defy is activated',
    masteryType: 'duration',
    masteryValues: [30, 60, 90, 120, 150, 180, 210, 240, 270, 300],
  },
  {
    id: 'uwc',
    name: 'Ultimate Crit',
    description: 'Ultimate Weapons gain a chance of x% to deal critical damage equal to current tower critical factor',
    rarity: 'epic',
    levelType: 'percent',
    levelValues: [1, 1.33, 1.66, 2, 2.33, 2.66, 3],
    masteryName: 'Ultimate Crit+',
    masteryDescription: 'Increases the card\'s stat multiplier',
    masteryType: 'percent',
    masteryValues: [0.3, 0.7, 1, 1.3, 1.7, 2, 2.3, 2.7, 3, 3.3],
  },
  {
    id: 'nuke',
    name: 'Nuke',
    description: 'Destroy x% of current on screen enemies',
    rarity: 'epic',
    levelType: 'percent',
    levelValues: [25, 35, 45, 55, 65, 80, 100],
    masteryName: 'Radiation',
    masteryDescription: 'Unlocks a lingering attack speed slow which lasts for 300 waves after the Nuke',
    masteryType: 'percent',
    masteryValues: [5, 10, 15, 20, 25, 30, 35, 40, 45, 50],
  },
  {
    id: 'aoe',
    name: 'Area of Effect',
    description: 'Increases area of effect damage for Inner Land Mines, Poison Swamp, Smart Missile, Flame Bot and Land Mine by x%.',
    rarity: 'epic',
    levelType: 'percent',
    levelValues: [5, 8, 11, 14, 17, 20, 25],
    masteryName: 'Blast Zone',
    masteryDescription: 'Increases the range of all damage area of effects.',
    masteryType: 'percent',
    masteryValues: [2.5, 5, 7.5, 10, 12.5, 15, 17.5, 20, 22.5, 25],
  },
]

export const CARDS_BY_RARITY = {
  common: ['dmg', 'as', 'hp', 'regen', 'range', 'cash', 'coins', 'sa', 'crit-chance', 'eb', 'def', 'fort'],
  rare: ['freeups', 'x-orb', 'pc', 'crit-coin', 'is', 'lms', 'rpc'],
  epic: ['dr', 'en', 'st', 'sw', 'dm', 'es', 'wa', 'zerk', 'uwc', 'nuke', 'aoe'],
} as const

export const CARD_TEMPLATES = cardTemplates
export const CARD_TEMPLATE_MAP: Record<string, CardTemplate> = CARD_TEMPLATES.reduce((map, card) => {
  map[card.id] = card
  return map
}, {} as Record<string, CardTemplate>)

export function getCardTemplate(id: string): CardTemplate | undefined {
  return CARD_TEMPLATE_MAP[id]
}
