export type ModuleCategory = 'Cannon' | 'Armor' | 'Generator' | 'Core'
export type ModuleRarityLabel = string

export interface ModuleRarityBonus {
  rarity: ModuleRarityLabel
  value: number
}

export interface ModuleTemplate {
  id: string
  name: string
  initials: string
  type: ModuleCategory
  unique: boolean
  minRarity: ModuleRarityLabel
  maxRarity: ModuleRarityLabel
  description: (value?: number) => string
  baseEffect?: string
  rarityBonuses?: ModuleRarityBonus[]
}

export const MODULE_MAX_COPIES = 18

export const MODULE_RARITIES: ModuleRarityLabel[] = [
  'Common',
  'Rare',
  'Rare +',
  'Epic',
  'Epic +',
  'Legendary',
  'Legendary +',
  'Mythic',
  'Mythic +',
  'Ancestral',
  'Ancestral 1',
  'Ancestral 2',
  'Ancestral 3',
  'Ancestral 4',
  'Ancestral 5',
]

const uniqueModules: ModuleTemplate[] = [
  {
    id: 'astral-deliverance',
    name: 'Astral Deliverance',
    initials: 'AD',
    type: 'Cannon',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Bounce Shot's range is increased by 3% of the Tower's total range. Each bounce increases the projectile damage by +${value ?? 80}%.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 20 },
      { rarity: 'Legendary', value: 40 },
      { rarity: 'Mythic', value: 60 },
      { rarity: 'Ancestral', value: 80 },
    ],
  },
  {
    id: 'being-annihilator',
    name: 'Being Annihilator',
    initials: 'BA',
    type: 'Cannon',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `When you super crit, your next ${value ?? 6} shots are guaranteed super crits.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 3 },
      { rarity: 'Legendary', value: 4 },
      { rarity: 'Mythic', value: 5 },
      { rarity: 'Ancestral', value: 6 },
    ],
  },
  {
    id: 'death-penalty',
    name: 'Death Penalty',
    initials: 'DP',
    type: 'Cannon',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Chance of ${value ?? 15}% to mark an enemy for death when it spawns, causing the first hit to destroy it.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 5 },
      { rarity: 'Legendary', value: 8 },
      { rarity: 'Mythic', value: 11 },
      { rarity: 'Ancestral', value: 15 },
    ],
  },
  {
    id: 'havoc-bringer',
    name: 'Havoc Bringer',
    initials: 'HB',
    type: 'Cannon',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `${value ?? 20}% chance for Rend Armor to instantly go to max.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 10 },
      { rarity: 'Legendary', value: 13 },
      { rarity: 'Mythic', value: 15 },
      { rarity: 'Ancestral', value: 20 },
    ],
  },
  {
    id: 'shrink-ray',
    name: 'Shrink Ray',
    initials: 'SR',
    type: 'Cannon',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Attacks have a 1% chance to apply a non-stacking effect that decreases the enemy mass by ${value ?? 40}%.`,
    baseEffect: '1% chance on hit to apply Shrink Ray.',
    rarityBonuses: [
      { rarity: 'Epic', value: 10 },
      { rarity: 'Legendary', value: 20 },
      { rarity: 'Mythic', value: 30 },
      { rarity: 'Ancestral', value: 40 },
    ],
  },
  {
    id: 'amplifying-strike',
    name: 'Amplifying Strike',
    initials: 'AS',
    type: 'Cannon',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Killing a Boss or Elite enemy increases Tower damage by 5x for ${value ?? 26} seconds.`,
    baseEffect: 'Defeating a boss or elite multiplies Tower damage by 5x.',
    rarityBonuses: [
      { rarity: 'Epic', value: 5 },
      { rarity: 'Legendary', value: 11 },
      { rarity: 'Mythic', value: 18 },
      { rarity: 'Ancestral', value: 26 },
    ],
  },
  {
    id: 'anti-cube-portal',
    name: 'Anti-Cube Portal',
    initials: 'ACP',
    type: 'Armor',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Enemies take x${value ?? 25} damage for 7s after they are hit by a shockwave.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 10 },
      { rarity: 'Legendary', value: 15 },
      { rarity: 'Mythic', value: 20 },
      { rarity: 'Ancestral', value: 25 },
    ],
  },
  {
    id: 'negative-mass-projector',
    name: 'Negative Mass Projector',
    initials: 'NMP',
    type: 'Armor',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `If an orb doesn't kill the enemy it will apply a stacking debuff, reducing its damage and speed by ${value ?? 2.5}% per hit, to a max reduction of 50%.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 1 },
      { rarity: 'Legendary', value: 1.5 },
      { rarity: 'Mythic', value: 2 },
      { rarity: 'Ancestral', value: 2.5 },
    ],
  },
  {
    id: 'wormhole-redirector',
    name: 'Wormhole Redirector',
    initials: 'WR',
    type: 'Armor',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Health Regen can heal up to ${value ?? 100}% of Package Max Recovery.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 25 },
      { rarity: 'Legendary', value: 50 },
      { rarity: 'Mythic', value: 75 },
      { rarity: 'Ancestral', value: 100 },
    ],
  },
  {
    id: 'space-displacer',
    name: 'Space Displacer',
    initials: 'SD',
    type: 'Armor',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Landmines have a ${value ?? 30}% chance to spawn as Inner Land Mines (20 max) instead of a normal mine. These mines autonomously move and organize around the tower.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 15 },
      { rarity: 'Legendary', value: 20 },
      { rarity: 'Mythic', value: 25 },
      { rarity: 'Ancestral', value: 30 },
    ],
  },
  {
    id: 'sharp-fortitude',
    name: 'Sharp Fortitude',
    initials: 'SF',
    type: 'Armor',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Increases wall's health and regen by x${value ?? 2.5}. Enemies take +1% increased damage from wall thorns per subsequent hit.`,
    baseEffect: 'Each subsequent thorn hit deals an additional 1% damage.',
    rarityBonuses: [
      { rarity: 'Epic', value: 1.25 },
      { rarity: 'Legendary', value: 1.5 },
      { rarity: 'Mythic', value: 2 },
      { rarity: 'Ancestral', value: 2.5 },
    ],
  },
  {
    id: 'orbital-augment',
    name: 'Orbital Augment',
    initials: 'OA',
    type: 'Armor',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Adds ${value ?? 8} orbiting Electrons around the tower. Each Electron deals damage equal to 10% of wave health to any enemies they hit.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 2 },
      { rarity: 'Legendary', value: 4 },
      { rarity: 'Mythic', value: 6 },
      { rarity: 'Ancestral', value: 8 },
    ],
  },
  {
    id: 'singularity-harness',
    name: 'Singularity Harness',
    initials: 'SH',
    type: 'Generator',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Increases the range of each bot by +${value ?? 15}m. Enemies hit by the Flame bot receive double damage.`,
    baseEffect: 'Enemies hit by the Flame bot take double damage.',
    rarityBonuses: [
      { rarity: 'Epic', value: 5 },
      { rarity: 'Legendary', value: 8 },
      { rarity: 'Mythic', value: 11 },
      { rarity: 'Ancestral', value: 15 },
    ],
  },
  {
    id: 'galaxy-compressor',
    name: 'Galaxy Compressor',
    initials: 'GC',
    type: 'Generator',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Collecting a recovery package reduces the cooldown of all Ultimate Weapons by ${value ?? 20}s.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 10 },
      { rarity: 'Legendary', value: 13 },
      { rarity: 'Mythic', value: 17 },
      { rarity: 'Ancestral', value: 20 },
    ],
  },
  {
    id: 'pulsar-harvester',
    name: 'Pulsar Harvester',
    initials: 'PH',
    type: 'Generator',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Each time a projectile hits an enemy, there is a ${value ?? 2.5}% chance that it will reduce the enemy's Health and Attack level by 1.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 1 },
      { rarity: 'Legendary', value: 1.5 },
      { rarity: 'Mythic', value: 2 },
      { rarity: 'Ancestral', value: 2.5 },
    ],
  },
  {
    id: 'black-hole-digestor',
    name: 'Black Hole Digestor',
    initials: 'BHD',
    type: 'Generator',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Temporarily get +${value ?? 10}% extra Coins/Kill bonus for each free upgrade you got on the current wave. Free upgrades cannot increase the Tower Range.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 3 },
      { rarity: 'Legendary', value: 5 },
      { rarity: 'Mythic', value: 7 },
      { rarity: 'Ancestral', value: 10 },
    ],
  },
  {
    id: 'project-funding',
    name: 'Project Funding',
    initials: 'PF',
    type: 'Generator',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Tower damage is multiplied by ${value ?? 100}% of the number of digits in your current cash.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 12.5 },
      { rarity: 'Legendary', value: 25 },
      { rarity: 'Mythic', value: 50 },
      { rarity: 'Ancestral', value: 100 },
    ],
  },
  {
    id: 'restorative-bonus',
    name: 'Restorative Bonus',
    initials: 'RB',
    type: 'Generator',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Packages grant a 50% attack speed boost for ${value ?? 30}s, decaying for 60 seconds.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 15 },
      { rarity: 'Legendary', value: 20 },
      { rarity: 'Mythic', value: 25 },
      { rarity: 'Ancestral', value: 30 },
    ],
  },
  {
    id: 'om-chip',
    name: 'Om Chip',
    initials: 'OC',
    type: 'Core',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Spotlight will rotate to focus a boss. Boss reflects the light around it to nearby enemies, increasing by x${value ?? 15} the damage they receive.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 2 },
      { rarity: 'Legendary', value: 4 },
      { rarity: 'Mythic', value: 7 },
      { rarity: 'Ancestral', value: 15 },
    ],
  },
  {
    id: 'harmony-conductor',
    name: 'Harmony Conductor',
    initials: 'HC',
    type: 'Core',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `${value ?? 30}% chance of poisoned enemies to miss attack. Boss chance is halved.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 15 },
      { rarity: 'Legendary', value: 20 },
      { rarity: 'Mythic', value: 25 },
      { rarity: 'Ancestral', value: 30 },
    ],
  },
  {
    id: 'dimension-core',
    name: 'Dimension Core',
    initials: 'DC',
    type: 'Core',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Chain Lightning have 60% chance of hitting the initial target. Shock chance and miltiplier is doubled. If the shock is applied to the same enemy the shock multiplier will add up to a max stack of ${value ?? 20}.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 5 },
      { rarity: 'Legendary', value: 10 },
      { rarity: 'Mythic', value: 15 },
      { rarity: 'Ancestral', value: 20 },
    ],
  },
  {
    id: 'multiverse-nexus',
    name: 'Multiverse Nexus',
    initials: 'MVN',
    type: 'Core',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Death Wave, Golden Tower and Black Hole will always activate at the same time, but the cooldown will be the average of those ${value !== undefined && value >= 0 ? '+' : ''}${value ?? -10}s.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 20 },
      { rarity: 'Legendary', value: 10 },
      { rarity: 'Mythic', value: 1 },
      { rarity: 'Ancestral', value: -10 },
    ],
  },
  {
    id: 'magnetic-hook',
    name: 'Magnetic Hook',
    initials: 'MH',
    type: 'Core',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `${value ?? 4} Inner Land Mines are fired at Bosses as they enter Tower range. 25% of Elites have Inner Land Mines fired at them as they enter tower range.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 1 },
      { rarity: 'Legendary', value: 2 },
      { rarity: 'Mythic', value: 3 },
      { rarity: 'Ancestral', value: 4 },
    ],
  },
  {
    id: 'primordial-collapse',
    name: 'Primordial Collapse',
    initials: 'PC',
    type: 'Core',
    unique: true,
    minRarity: 'Epic',
    maxRarity: 'Ancestral 5',
    description: (value?: number) => `Spawns one additional Black Hole. Damage from enemies within a Black Hole is decreased by ${value ?? 80}%.`,
    rarityBonuses: [
      { rarity: 'Epic', value: 50 },
      { rarity: 'Legendary', value: 55 },
      { rarity: 'Mythic', value: 65 },
      { rarity: 'Ancestral', value: 80 },
    ],
  },
]

const rareModules: ModuleTemplate[] = [
  {
    id: 'rare-ob',
    name: 'Omniboost Blitzer',
    initials: 'OB',
    type: 'Cannon',
    unique: false,
    minRarity: 'Rare',
    maxRarity: 'Legendary +',
    description: () => 'Increases overall Tower damage output.',
  },
  {
    id: 'rare-rb',
    name: 'Rapidreach Blitzer',
    initials: 'RB',
    type: 'Cannon',
    unique: false,
    minRarity: 'Rare',
    maxRarity: 'Legendary +',
    description: () => 'Extends Tower attack range.',
  },
  {
    id: 'rare-bb',
    name: 'Bounce Blitzer',
    initials: 'BB',
    type: 'Cannon',
    unique: false,
    minRarity: 'Rare',
    maxRarity: 'Legendary +',
    description: () => 'Projectiles bounce between enemies.',
  },
  {
    id: 'rare-sb',
    name: 'Swiftstrike Blitzer',
    initials: 'SB',
    type: 'Cannon',
    unique: false,
    minRarity: 'Rare',
    maxRarity: 'Legendary +',
    description: () => 'Increases Tower attack speed.',
  },
  {
    id: 'rare-ni',
    name: 'Nano Intercept',
    initials: 'NI',
    type: 'Armor',
    unique: false,
    minRarity: 'Rare',
    maxRarity: 'Legendary +',
    description: () => 'Intercepts incoming projectiles.',
  },
  {
    id: 'rare-pc',
    name: 'Photon Counter',
    initials: 'PC',
    type: 'Armor',
    unique: false,
    minRarity: 'Rare',
    maxRarity: 'Legendary +',
    description: () => 'Counters enemy attacks with photon bursts.',
  },
  {
    id: 'rare-sr',
    name: 'Solar Reflector',
    initials: 'SR',
    type: 'Armor',
    unique: false,
    minRarity: 'Rare',
    maxRarity: 'Legendary +',
    description: () => 'Reflects solar energy to damage enemies.',
  },
  {
    id: 'rare-dn',
    name: 'Diamond Nanowall',
    initials: 'DN',
    type: 'Armor',
    unique: false,
    minRarity: 'Rare',
    maxRarity: 'Legendary +',
    description: () => 'Creates diamond-hard defensive barriers.',
  },
  {
    id: 'rare-sl',
    name: 'Stellar Lift',
    initials: 'SL',
    type: 'Generator',
    unique: false,
    minRarity: 'Rare',
    maxRarity: 'Legendary +',
    description: () => 'Lifts enemies off the ground with stellar forces.',
  },
  {
    id: 'rare-os',
    name: 'Orbital Sail',
    initials: 'OS',
    type: 'Generator',
    unique: false,
    minRarity: 'Rare',
    maxRarity: 'Legendary +',
    description: () => 'Harnesses orbital energy for Tower enhancements.',
  },
  {
    id: 'rare-ar',
    name: 'Antimatter Reactor',
    initials: 'AR',
    type: 'Generator',
    unique: false,
    minRarity: 'Rare',
    maxRarity: 'Legendary +',
    description: () => 'Generates power through antimatter reactions.',
  },
  {
    id: 'rare-sds',
    name: 'Solar Dyson Sphere',
    initials: 'SDS',
    type: 'Generator',
    unique: false,
    minRarity: 'Rare',
    maxRarity: 'Legendary +',
    description: () => 'Collects solar energy on a massive scale.',
  },
  {
    id: 'rare-gl',
    name: 'Galactic Librarian',
    initials: 'GL',
    type: 'Core',
    unique: false,
    minRarity: 'Rare',
    maxRarity: 'Legendary +',
    description: () => 'Accesses galactic knowledge for strategic advantages.',
  },
  {
    id: 'rare-ms',
    name: 'Matrix Sim',
    initials: 'MS',
    type: 'Core',
    unique: false,
    minRarity: 'Rare',
    maxRarity: 'Legendary +',
    description: () => 'Simulates matrix effects for enhanced capabilities.',
  },
  {
    id: 'rare-em',
    name: 'Eon Mind',
    initials: 'EM',
    type: 'Core',
    unique: false,
    minRarity: 'Rare',
    maxRarity: 'Legendary +',
    description: () => 'Enhances mental processing for better Tower control.',
  },
  {
    id: 'rare-cs',
    name: 'Chronosync',
    initials: 'CS',
    type: 'Core',
    unique: false,
    minRarity: 'Rare',
    maxRarity: 'Legendary +',
    description: () => 'Synchronizes time-based effects and abilities.',
  },
]

const commonModules: ModuleTemplate[] = [
  {
    id: 'common-ec-cannon',
    name: 'Energy Cannon',
    initials: 'EC',
    type: 'Cannon',
    unique: false,
    minRarity: 'Common',
    maxRarity: 'Common',
    description: () => 'Basic energy-based projectile weapon.',
  },
  {
    id: 'common-mc-cannon',
    name: 'Matter Cannon',
    initials: 'MC',
    type: 'Cannon',
    unique: false,
    minRarity: 'Common',
    maxRarity: 'Common',
    description: () => 'Basic matter-based projectile weapon.',
  },
  {
    id: 'common-eb',
    name: 'Energy Barrier',
    initials: 'EB',
    type: 'Armor',
    unique: false,
    minRarity: 'Common',
    maxRarity: 'Common',
    description: () => 'Basic energy-based defensive barrier.',
  },
  {
    id: 'common-mb',
    name: 'Matter Barrier',
    initials: 'MB',
    type: 'Armor',
    unique: false,
    minRarity: 'Common',
    maxRarity: 'Common',
    description: () => 'Basic matter-based defensive barrier.',
  },
  {
    id: 'common-mc-generator',
    name: 'Matter Converter',
    initials: 'MC',
    type: 'Generator',
    unique: false,
    minRarity: 'Common',
    maxRarity: 'Common',
    description: () => 'Converts matter into usable energy.',
  },
  {
    id: 'common-ec-generator',
    name: 'Energy Converter',
    initials: 'EC',
    type: 'Generator',
    unique: false,
    minRarity: 'Common',
    maxRarity: 'Common',
    description: () => 'Converts energy into usable matter.',
  },
  {
    id: 'common-ec-core',
    name: 'Energy Chip',
    initials: 'EC',
    type: 'Core',
    unique: false,
    minRarity: 'Common',
    maxRarity: 'Common',
    description: () => 'Basic energy processing core.',
  },
  {
    id: 'common-mc-core',
    name: 'Matter Chip',
    initials: 'MC',
    type: 'Core',
    unique: false,
    minRarity: 'Common',
    maxRarity: 'Common',
    description: () => 'Basic matter processing core.',
  },
]

export const UNIQUE_MODULE_TEMPLATES = uniqueModules
export const RARE_MODULE_TEMPLATES = rareModules
export const COMMON_MODULE_TEMPLATES = commonModules

export const MODULE_TEMPLATES: ModuleTemplate[] = [
  ...uniqueModules,
  ...rareModules,
  ...commonModules,
]

export const MODULE_TEMPLATE_MAP: Record<string, ModuleTemplate> = MODULE_TEMPLATES.reduce((map, module) => {
  map[module.id] = module
  return map
}, {} as Record<string, ModuleTemplate>)

export function getModuleTemplate(id: string): ModuleTemplate | undefined {
  return MODULE_TEMPLATE_MAP[id]
}

export function getModulesByType(type: ModuleCategory): ModuleTemplate[] {
  return MODULE_TEMPLATES.filter(module => module.type === type)
}
