export type RelicTemplate = {
  id: string
  name: string
  description?: string
  requirement?: string
  icon?: string
  bonusType?: string
  value?: string
  rarity?: string
  event?: string
  type?: string
}

const RELIC_TEMPLATES: RelicTemplate[] = [
  { id: '1-Rare-1', name: 'No Spoon', bonusType: 'Defense Absolute', value: '2%', rarity: 'Rare', event: 'Into the Matrix', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-2', name: 'Copper Badge', bonusType: 'Damage', value: '3%', rarity: 'Rare', event: '4th in Copper', type: 'Tournament', requirement: '4th in Copper' },
  { id: '1-Rare-3', name: 'Silver Badge', bonusType: 'Coins', value: '5%', rarity: 'Rare', event: '4th in Silver', type: 'Tournament', requirement: '4th in Silver' },
  { id: '1-Rare-4', name: 'T:I Flux', bonusType: 'Coins', value: '2%', rarity: 'Rare', event: 'T1 W4500', type: 'Milestone', requirement: '4500 Waves in T1' },
  { id: '1-Rare-5', name: 'T:2 Lumin', bonusType: 'Lab Speed', value: '1.5%', rarity: 'Rare', event: 'T2 W4500', type: 'Milestone', requirement: '4500 Waves in T2' },
  { id: '1-Rare-6', name: 'T:3 Pulse', bonusType: 'Crit Factor', value: '2%', rarity: 'Rare', event: 'T3 W4500', type: 'Milestone', requirement: '4500 Waves in T3' },
  { id: '1-Rare-7', name: 'T:IV Harmonic', bonusType: 'Damage', value: '2%', rarity: 'Rare', event: 'T4 W4500', type: 'Milestone', requirement: '4500 Waves in T4' },
  { id: '1-Rare-8', name: 'T:V Ether', bonusType: 'Health', value: '2%', rarity: 'Rare', event: 'T5 W4500', type: 'Milestone', requirement: '4500 Waves in T5' },
  { id: '1-Rare-9', name: '1st Tower Birthday', bonusType: 'Damage', value: '2%', rarity: 'Rare', event: '1 Year Played', type: 'Anniversary', requirement: 'Play for 1 year' },
  { id: '1-Rare-10', name: '2nd Tower Birthday', bonusType: 'Crit Factor', value: '2%', rarity: 'Rare', event: '2 Years Played', type: 'Anniversary', requirement: 'Play for 2 years' },
  { id: '1-Rare-11', name: '3rd Tower Birthday', bonusType: 'Damage / Meter', value: '2%', rarity: 'Rare', event: '3 Years Played', type: 'Anniversary', requirement: 'Play for 3 years' },
  { id: '1-Rare-12', name: '4th  Tower Birthday', bonusType: 'Health', value: '2%', rarity: 'Rare', event: '4 Years Played', type: 'Anniversary', requirement: 'Play for 4 years' },
  { id: '1-Rare-13', name: '5th Tower Birthday', bonusType: 'Crit Factor', value: '2%', rarity: 'Rare', event: '5 Years Played', type: 'Anniversary', requirement: 'Play for 5 years' },
  { id: '1-Rare-14', name: '6th Tower Birthday', bonusType: 'Damage / Meter', value: '2%', rarity: 'Rare', event: '6 Years Played', type: 'Anniversary', requirement: 'Play for 6 years' },
  { id: '1-Rare-15', name: 'Dreamcatcher', bonusType: 'Coins', value: '2%', rarity: 'Rare', event: 'Howling Wolf', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-16', name: 'Bacteriophage', bonusType: 'Damage', value: '2%', rarity: 'Rare', event: 'Viral Outbreak', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-17', name: 'Ionized Plasma', bonusType: 'Defense Absolute', value: '2%', rarity: 'Rare', event: 'Plasma Returns', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-18', name: 'Ancient Tome', bonusType: 'Lab Speed', value: '1.5%', rarity: 'Rare', event: 'Sands of Time', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-19', name: 'Tower Latte', bonusType: 'Damage / Meter', value: '2%', rarity: 'Rare', event: 'Autumn', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-20', name: 'Spooky Bat', bonusType: 'Crit Factor', value: '2%', rarity: 'Rare', event: 'Halloween', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-21', name: 'Cherry', bonusType: 'Defense Absolute', value: '2%', rarity: 'Rare', event: 'Cherry Blossom', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-22', name: 'Holy Joystick', bonusType: 'Damage', value: '2%', rarity: 'Rare', event: 'Retro Arcade', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-23', name: 'Honey Drop', bonusType: 'Damage', value: '2%', rarity: 'Rare', event: 'Honey (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-24', name: 'Firework', bonusType: 'Health', value: '2%', rarity: 'Rare', event: 'New Year', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-25', name: 'Aurora Vortex', bonusType: 'Health', value: '2%', rarity: 'Rare', event: 'Aurora (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-26', name: 'Dark Sight', bonusType: 'Damage / Meter', value: '2%', rarity: 'Rare', event: 'Dark Strands', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-27', name: 'Palm Tree', bonusType: 'Lab Speed', value: '2%', rarity: 'Rare', event: 'Retrowave (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-28', name: 'Submarine', bonusType: 'Crit Factor', value: '2%', rarity: 'Rare', event: 'Deep Blue Sea', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-29', name: 'Alien Head', bonusType: 'Coins', value: '2%', rarity: 'Rare', event: 'Aliens', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-30', name: 'Warp Gate', bonusType: 'Coins', value: '2%', rarity: 'Rare', event: 'Faster Than Light', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-31', name: 'Barnacle', bonusType: 'Health', value: '2%', rarity: 'Rare', event: 'Ocean Night', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-32', name: 'Pizza', bonusType: 'Damage', value: '2%', rarity: 'Rare', event: 'Invaders', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-33', name: 'Refraction Array', bonusType: 'Coins', value: '2%', rarity: 'Rare', event: 'Prismatic Lines', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-34', name: 'Hook', bonusType: 'Damage / Meter', value: '2%', rarity: 'Rare', event: 'Sunset Fishing', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-35', name: 'Cobweb', bonusType: 'Health', value: '2%', rarity: 'Rare', event: 'Cobweb', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-36', name: 'Gale Winds', bonusType: 'Coins', value: '2%', rarity: 'Rare', event: 'Eye of the Storm', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-37', name: 'Clip Ons', bonusType: 'Crit Factor', value: '2%', rarity: 'Rare', event: 'Into the Matrix (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-38', name: 'Rain Jacket', bonusType: 'Health', value: '2%', rarity: 'Rare', event: 'Storm', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-39', name: 'Rabies', bonusType: 'Lab Speed', value: '2%', rarity: 'Rare', event: 'Viral Outbreak (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-40', name: 'Comet', bonusType: 'Damage', value: '2%', rarity: 'Rare', event: 'Interstellar', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-41', name: 'Remote Control', bonusType: 'Damage / Meter', value: '2%', rarity: 'Rare', event: "Tower's Channel", type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-42', name: 'Anubis', bonusType: 'Coins', value: '2%', rarity: 'Rare', event: 'Sands of Time (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-43', name: 'Lava Flow', bonusType: 'Health', value: '2%', rarity: 'Rare', event: 'Volcano', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-44', name: 'Abduction Room', bonusType: 'Health', value: '2%', rarity: 'Rare', event: 'Abduction', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-45', name: 'Acorn', bonusType: 'Damage / Meter', value: '2%', rarity: 'Rare', event: 'Autumn', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-46', name: 'Cauldron', bonusType: 'Lab Speed', value: '2%', rarity: 'Rare', event: 'Halloween (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-47', name: 'Icicle', bonusType: 'Damage', value: '2%', rarity: 'Rare', event: 'Snowstorm', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-48', name: 'Koi Fish', bonusType: 'Lab Speed', value: '2%', rarity: 'Rare', event: 'Cherry Blossom (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-49', name: 'Tea Ceremony', bonusType: 'Health', value: '2%', rarity: 'Rare', event: 'Cherry Blossom (2)', type: 'Standard', requirement: '200 Medals' },
  { id: '1-Rare-50', name: 'Lunar Cat Paw', bonusType: 'Crit Chance', value: '1%', rarity: 'Rare', event: 'Meowy Night', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-51', name: 'Confetti Ball', bonusType: 'Free Attack Upgrade', value: '1%', rarity: 'Rare', event: 'New Year (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-52', name: 'Summit Starlight', bonusType: 'Lab Speed', value: '2%', rarity: 'Rare', event: 'Howling Wolf (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-53', name: 'Falling Apple', bonusType: 'Free Defense Upgrade', value: '1%', rarity: 'Rare', event: 'Gravity', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-54', name: 'Power Glove', bonusType: 'Damage', value: '2%', rarity: 'Rare', event: 'Retro Arcade (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-55', name: 'Coral Crown', bonusType: 'Health Regen', value: '2%', rarity: 'Rare', event: 'Deep Blue Sea (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-56', name: 'Temporal Rift', bonusType: 'Cash', value: '2%', rarity: 'Rare', event: 'What Time Is It?', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-57', name: 'Hourglass', bonusType: 'Coins', value: '2%', rarity: 'Rare', event: 'What Time Is It?', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-58', name: 'Throne', bonusType: 'Health', value: '2%', rarity: 'Rare', event: 'Guild Season 1', type: 'Standard', requirement: '75 Tokens' },
  { id: '1-Rare-59', name: 'Haunted Mirror', bonusType: 'Wall Rebuild', value: '2s', rarity: 'Rare', event: 'Dark Strands (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-60', name: 'Whispering Web', bonusType: 'Free Defense Upgrade', value: '1%', rarity: 'Rare', event: 'Dark Strands (2)', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-61', name: 'Pulsar Core', bonusType: 'Recovery Amount', value: '2%', rarity: 'Rare', event: 'Faster Than Light (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-62', name: 'Quantum Drive', bonusType: 'Bot Range', value: '1m', rarity: 'Rare', event: 'Faster Than Light (2)', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-63', name: 'Bloom Burst', bonusType: 'Cash', value: '2%', rarity: 'Rare', event: 'Easter', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-64', name: 'Mystic Bunny', bonusType: 'Coins', value: '2%', rarity: 'Rare', event: 'Easter', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-65', name: 'Fancy Wires', bonusType: 'Health Regen', value: '2%', rarity: 'Rare', event: 'Guild Season 2', type: 'Standard', requirement: '75 Tokens' },
  { id: '1-Rare-66', name: 'Infinite Ruler', bonusType: 'Free Utility Upgrade', value: '1%', rarity: 'Rare', event: 'Pi', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-67', name: 'Pi Seal', bonusType: 'Lab Speed', value: '2%', rarity: 'Rare', event: 'Pi', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-68', name: 'UFO Beam', bonusType: 'Knockback Force', value: '2%', rarity: 'Rare', event: 'Invaders (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-69', name: 'Abduction Signal', bonusType: 'Crit Factor', value: '2%', rarity: 'Rare', event: 'Invaders (2)', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-70', name: 'Honey Jar', bonusType: 'Attack Speed', value: '1%', rarity: 'Rare', event: 'Honey (3)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-71', name: 'Heavenly Sweet', bonusType: 'Health', value: '2%', rarity: 'Rare', event: 'Honey (3)', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-72', name: 'Duck', bonusType: 'Ultimate Damage', value: '2%', rarity: 'Rare', event: 'Koi Pond', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-73', name: 'Grass', bonusType: 'Free Defense Upgrade', value: '1%', rarity: 'Rare', event: 'Koi Pond', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-74', name: "Let's Mix", bonusType: 'Coins', value: '2%', rarity: 'Rare', event: 'Guild Season 3', type: 'Standard', requirement: '75 Tokens' },
  { id: '1-Rare-75', name: 'Plasma Globe', bonusType: 'Bot Range', value: '1m', rarity: 'Rare', event: 'Plasma Returns (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-76', name: 'Plasma Vortex', bonusType: 'Damage', value: '2%', rarity: 'Rare', event: 'Plasma Returns (2)', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-77', name: 'Floppy Disk', bonusType: 'Free Utility Upgrade', value: '1%', rarity: 'Rare', event: 'Retrowave (3)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-78', name: 'Magic Cube', bonusType: 'Crit Factor', value: '2%', rarity: 'Rare', event: 'Retrowave (3)', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-79', name: 'Safe Path', bonusType: 'Damage', value: '2%', rarity: 'Rare', event: 'Camping', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-80', name: 'Shining Light', bonusType: 'Crit Chance', value: '1%', rarity: 'Rare', event: 'Camping', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-81', name: 'Fisherman Set', bonusType: 'Defense Absolute', value: '2%', rarity: 'Rare', event: 'Sunset Fishing (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-82', name: 'Sunset Boat', bonusType: 'Attack Speed', value: '1%', rarity: 'Rare', event: 'Sunset Fishing (2)', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-83', name: 'World Domination', bonusType: 'Health', value: '2%', rarity: 'Rare', event: 'Guild Season 4', type: 'Standard', requirement: '75 Tokens' },
  { id: '1-Rare-84', name: 'Model Training', bonusType: 'Orb Speed', value: '2%', rarity: 'Rare', event: 'Into the Matrix (3)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-85', name: 'Gnosis', bonusType: 'Free Defense Upgrade', value: '1%', rarity: 'Rare', event: 'Into the Matrix (3)', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-86', name: 'Rlyeh', bonusType: 'Free Attack Upgrade', value: '1%', rarity: 'Rare', event: 'Cthulhu', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-87', name: 'Madness Induced', bonusType: 'Crit Factor', value: '2%', rarity: 'Rare', event: 'Cthulhu', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-88', name: 'Breaking News', bonusType: 'Bot Range', value: '1m', rarity: 'Rare', event: "Tower's Channel (2)", type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-89', name: 'Globalization', bonusType: 'Damage', value: '2%', rarity: 'Rare', event: "Tower's Channel (2)", type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-90', name: 'Brunch', bonusType: 'Knockback Force', value: '2%', rarity: 'Rare', event: 'Autumn (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-91', name: 'Dry leaves', bonusType: 'Free Attack Upgrade', value: '1%', rarity: 'Rare', event: 'Autumn (2)', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-92', name: 'Blood Monster', bonusType: 'Defense %', value: '1%', rarity: 'Rare', event: 'Guild Season 5', type: 'Standard', requirement: '75 Tokens' },
  { id: '1-Rare-93', name: 'Vr', bonusType: 'Thorns', value: '1%', rarity: 'Rare', event: 'Cyberpunk', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-94', name: 'Holographic Ads', bonusType: 'Lab Speed', value: '2%', rarity: 'Rare', event: 'Cyberpunk', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-95', name: 'Good Hunting', bonusType: 'Cash', value: '2%', rarity: 'Rare', event: 'Cobweb (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-96', name: 'Spider Vision', bonusType: 'Orb Speed', value: '2%', rarity: 'Rare', event: 'Cobweb (2)', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-97', name: 'Pinball', bonusType: 'Defense Absolute', value: '2%', rarity: 'Rare', event: 'Retro Arcade (3)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-98', name: 'To Infinity', bonusType: 'Health Regen', value: '2%', rarity: 'Rare', event: 'Retro Arcade (3)', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-99', name: 'Explorer\'s Helmet', bonusType: 'Health', value: '2%', rarity: 'Rare', event: 'Crystal Cave', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-100', name: 'Miner\'s Tool', bonusType: 'Defense %', value: '1%', rarity: 'Rare', event: 'Crystal Cave', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-101', name: 'Star Path', bonusType: 'Free Attack Upgrade', value: '2%', rarity: 'Rare', event: 'Guild Season 6', type: 'Standard', requirement: '75 Tokens' },
  { id: '1-Rare-102', name: 'Snow Globe', bonusType: 'Recovery Amount', value: '2%', rarity: 'Rare', event: 'Snowstorm (2)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-103', name: 'Winter Gloves', bonusType: 'Thorns', value: '1%', rarity: 'Rare', event: 'Snowstorm (2)', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-104', name: 'Party Popper', bonusType: 'Free Attack Upgrade', value: '1%', rarity: 'Rare', event: 'New Year (3)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-105', name: 'Champagne', bonusType: 'Attack Speed', value: '1%', rarity: 'Rare', event: 'New Year (3)', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-106', name: 'Hapiness Balloons', bonusType: 'Defense Absolute', value: '2%', rarity: 'Rare', event: 'Amusement Park', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-107', name: 'Delicious Food', bonusType: 'Cash', value: '2%', rarity: 'Rare', event: 'Amusement Park', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-108', name: "Sky's Curtain", bonusType: 'Free Defense Upgrade', value: '1%', rarity: 'Rare', event: 'Aurora (3)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-109', name: 'Solar Flare', bonusType: 'Crit Chance', value: '1%', rarity: 'Rare', event: 'Aurora (3)', type: 'Premium', requirement: '550 Medals' },
  { id: '1-Rare-110', name: 'Elemental Explosion', bonusType: 'Rend Armor Multi', value: '2%', rarity: 'Rare', event: 'Guild Season 7', type: 'Standard', requirement: '75 Tokens' },
  { id: '1-Rare-111', name: 'Sudden Attack', bonusType: 'Health Regen', value: '2%', rarity: 'Rare', event: 'Aliens (3)', type: 'Standard', requirement: '350 Medals' },
  { id: '1-Rare-112', name: 'Alien Experiment', bonusType: 'Bot Range', value: '1m', rarity: 'Rare', event: 'Aliens (3)', type: 'Premium', requirement: '550 Medals' },

  // Epic
  { id: '2-Epic-1', name: 'Red Pill', bonusType: 'Health', value: '5%', rarity: 'Epic', event: 'Into the Matrix', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-2', name: 'GoldBadge', bonusType: 'Crit Factor', value: '5%', rarity: 'Epic', event: '4th in Gold', type: 'Tournament', requirement: '4th in Gold' },
  { id: '2-Epic-3', name: 'Platinum Badge', bonusType: 'Lab Speed', value: '4%', rarity: 'Epic', event: '4th in Platinum', type: 'Tournament', requirement: '4th in Platinum' },
  { id: '2-Epic-4', name: 'T: VI Nova', bonusType: 'Defense Absolute', value: '5%', rarity: 'Epic', event: 'T6 W4500', type: 'Milestone', requirement: '4500 Waves in T6' },
  { id: '2-Epic-5', name: 'T: V2 Aether', bonusType: 'Coins', value: '5%', rarity: 'Epic', event: 'T7 W4500', type: 'Milestone', requirement: '4500 Waves in T7' },
  { id: '2-Epic-6', name: 'T: V3 Graviton', bonusType: 'Damage / Meter', value: '5%', rarity: 'Epic', event: 'T8 W4500', type: 'Milestone', requirement: '4500 Waves in T8' },
  { id: '2-Epic-7', name: 'T: IX Fusion', bonusType: 'Health', value: '5%', rarity: 'Epic', event: 'T9 W4500', type: 'Milestone', requirement: '4500 Waves in T9' },
  { id: '2-Epic-8', name: 'T: X Plasma', bonusType: 'Damage / Meter', value: '5%', rarity: 'Epic', event: 'T10 W4500', type: 'Milestone', requirement: '4500 Waves in T10' },
  { id: '2-Epic-9', name: 'Spirit Wolf', bonusType: 'Crit Factor', value: '5%', rarity: 'Epic', event: 'Howling Wolf', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-10', name: 'Neuron', bonusType: 'Health', value: '5%', rarity: 'Epic', event: 'Viral Outbreak', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-11', name: 'Plasma Arc', bonusType: 'Lab Speed', value: '4%', rarity: 'Epic', event: 'Plasma Returns', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-12', name: 'Space Sundial', bonusType: 'Damage', value: '5%', rarity: 'Epic', event: 'Sands of Time', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-13', name: 'Pumpkin', bonusType: 'Lab Speed', value: '4%', rarity: 'Epic', event: 'Autumn', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-14', name: 'Man Skull', bonusType: 'Health', value: '5%', rarity: 'Epic', event: 'Halloween', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-15', name: 'Sakura Latern', bonusType: 'Coins', value: '5%', rarity: 'Epic', event: 'Cherry Blossom', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-16', name: 'Controller', bonusType: 'Crit Factor', value: '5%', rarity: 'Epic', event: 'Retro Arcade', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-17', name: 'Stinger', bonusType: 'Crit Factor', value: '5%', rarity: 'Epic', event: 'Honey (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-18', name: 'Cheers', bonusType: 'Defense Absolute', value: '5%', rarity: 'Epic', event: 'New Year', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-19', name: 'Contained Ions', bonusType: 'Defense Absolute', value: '5%', rarity: 'Epic', event: 'Aurora (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-20', name: 'Creepy Smile', bonusType: 'Damage', value: '5%', rarity: 'Epic', event: 'Dark Strands', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-21', name: 'Pixel Cube Heart', bonusType: 'Health', value: '5%', rarity: 'Epic', event: 'Retrowave (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-22', name: 'The Kraken', bonusType: 'Defense Absolute', value: '5%', rarity: 'Epic', event: 'Deep Blue Sea', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-23', name: 'Alien Warp Drive', bonusType: 'Damage / Meter', value: '5%', rarity: 'Epic', event: 'Aliens', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-24', name: 'Star Ship', bonusType: 'Lab Speed', value: '4%', rarity: 'Epic', event: 'Faster Than Light', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-25', name: 'Wave', bonusType: 'Crit Factor', value: '5%', rarity: 'Epic', event: 'Ocean Night', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-26', name: 'Illuminati', bonusType: 'Defense Absolute', value: '5%', rarity: 'Epic', event: 'Invaders', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-27', name: 'Prismatic Shard', bonusType: 'Damage / Meter', value: '5%', rarity: 'Epic', event: 'Prismatic Lines', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-28', name: 'Fish', bonusType: 'Defense Absolute', value: '5%', rarity: 'Epic', event: 'Sunset Fishing', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-29', name: 'The Fly', bonusType: 'Defense Absolute', value: '5%', rarity: 'Epic', event: 'Cobweb', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-30', name: 'Flying House', bonusType: 'Damage', value: '5%', rarity: 'Epic', event: 'Eye of the Storm', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-31', name: 'Code Stream', bonusType: 'Damage', value: '5%', rarity: 'Epic', event: 'Into the Matrix (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-32', name: 'Cloud Lightning', bonusType: 'Crit Factor', value: '5%', rarity: 'Epic', event: 'Storm', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-33', name: 'Ebola', bonusType: 'Defense Absolute', value: '5%', rarity: 'Epic', event: 'Viral Outbreak (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-34', name: 'Planetary Rings', bonusType: 'Crit Factor', value: '5%', rarity: 'Epic', event: 'Interstellar', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-35', name: 'Cathode Ray Tube', bonusType: 'Coins', value: '5%', rarity: 'Epic', event: "Tower's Channel", type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-36', name: 'Sphinx', bonusType: 'Damage', value: '5%', rarity: 'Epic', event: 'Sands of Time (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-37', name: 'Ash Cloud', bonusType: 'Defense Absolute', value: '5%', rarity: 'Epic', event: 'Volcano', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-38', name: 'Crop Circle', bonusType: 'Crit Factor', value: '5%', rarity: 'Epic', event: 'Abduction', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-39', name: 'Scarf', bonusType: 'Defense Absolute', value: '5%', rarity: 'Epic', event: 'Autumn', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-40', name: 'Witch Hat', bonusType: 'Damage', value: '5%', rarity: 'Epic', event: 'Halloween (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-41', name: 'Sleigh Bell', bonusType: 'Health', value: '5%', rarity: 'Epic', event: 'Snowstorm', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-42', name: 'Bonsai Tree', bonusType: 'Coins', value: '5%', rarity: 'Epic', event: 'Cherry Blossom (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-43', name: 'Kimono', bonusType: 'Coins', value: '5%', rarity: 'Epic', event: 'Cherry Blossom (2)', type: 'Standard', requirement: '500 Medals' },
  { id: '2-Epic-44', name: 'Pet Cat', bonusType: 'Attack Speed', value: '2%', rarity: 'Epic', event: 'Meowy Night', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-45', name: 'Party Mask', bonusType: 'Ultimate Damage', value: '5%', rarity: 'Epic', event: 'New Year (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-46', name: 'Mountain Goat', bonusType: 'Health', value: '5%', rarity: 'Epic', event: 'Howling Wolf (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-47', name: '3 Body Solution', bonusType: 'Super Critical Chance', value: '2%', rarity: 'Epic', event: 'Gravity', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-48', name: 'Arcade Token', bonusType: 'Bot Range', value: '2m', rarity: 'Epic', event: 'Retro Arcade (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-49', name: 'Angler Fish', bonusType: 'Thorns', value: '2%', rarity: 'Epic', event: 'Deep Blue Sea (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-50', name: 'Dream Clock', bonusType: 'Orb Speed', value: '5%', rarity: 'Epic', event: 'What Time Is It?', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-51', name: 'Time Compass', bonusType: 'Attack Speed', value: '2%', rarity: 'Epic', event: 'What Time Is It?', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-52', name: 'Crown', bonusType: 'Crit Factor', value: '5%', rarity: 'Epic', event: 'Guild Season 1', type: 'Standard', requirement: '150 Tokens' },
  { id: '2-Epic-53', name: 'Shadow Puppet', bonusType: 'Super Critical Mult', value: '5%', rarity: 'Epic', event: 'Dark Strands (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-54', name: 'Cursed Candle', bonusType: 'Super Critical Chance', value: '2%', rarity: 'Epic', event: 'Dark Strands (2)', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-55', name: 'Light Speedometer', bonusType: 'Enemy Attack Level Skip', value: '2%', rarity: 'Epic', event: 'Faster Than Light (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-56', name: 'Photon Blade', bonusType: 'Damage', value: '5%', rarity: 'Epic', event: 'Faster Than Light (2)', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-57', name: 'Candy Core', bonusType: 'Damage', value: '5%', rarity: 'Epic', event: 'Easter', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-58', name: 'Magic Egg', bonusType: 'Free Attack Upgrade', value: '2%', rarity: 'Epic', event: 'Easter', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-59', name: 'Mech Head', bonusType: 'Bot Range', value: '2m', rarity: 'Epic', event: 'Guild Season 2', type: 'Standard', requirement: '150 Tokens' },
  { id: '2-Epic-60', name: 'Do While True', bonusType: 'Orb Speed', value: '5%', rarity: 'Epic', event: 'Pi', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-61', name: 'Psychohistorian Brain', bonusType: 'Super Critical Chance', value: '2%', rarity: 'Epic', event: 'Pi', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-62', name: 'Alien Egg', bonusType: 'Enemy Health Level Skip', value: '2%', rarity: 'Epic', event: 'Invaders (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-63', name: 'Monolith', bonusType: 'Ultimate Damage', value: '5%', rarity: 'Epic', event: 'Invaders (2)', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-64', name: 'Honey Society', bonusType: 'Knockback Force', value: '5%', rarity: 'Epic', event: 'Honey (3)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-65', name: 'The Queen', bonusType: 'Coins', value: '5%', rarity: 'Epic', event: 'Honey (3)', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-66', name: 'Wind', bonusType: 'Damage / Meter', value: '5%', rarity: 'Epic', event: 'Koi Pond', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-67', name: 'Lilies', bonusType: 'Recovery Amount', value: '5%', rarity: 'Epic', event: 'Koi Pond', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-68', name: 'Night Life', bonusType: 'Attack Speed', value: '2%', rarity: 'Epic', event: 'Guild Season 3', type: 'Standard', requirement: '150 Tokens' },
  { id: '2-Epic-69', name: 'Plasma Cell', bonusType: 'Crit Chance', value: '2%', rarity: 'Epic', event: 'Plasma Returns (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-70', name: 'Plasma Chamber', bonusType: 'Health', value: '5%', rarity: 'Epic', event: 'Plasma Returns (2)', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-71', name: 'Retro Camera', bonusType: 'Health Regen', value: '5%', rarity: 'Epic', event: 'Retrowave (3)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-72', name: 'Night City', bonusType: 'Cash', value: '5%', rarity: 'Epic', event: 'Retrowave (3)', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-73', name: 'Eternal Quest', bonusType: 'Health', value: '5%', rarity: 'Epic', event: 'Camping', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-74', name: 'Nature\'s Wrath', bonusType: 'Orb Speed', value: '5%', rarity: 'Epic', event: 'Camping', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-75', name: 'Good Catch', bonusType: 'Thorns', value: '2%', rarity: 'Epic', event: 'Sunset Fishing (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-76', name: 'River Of Plenty', bonusType: 'Coins', value: '5%', rarity: 'Epic', event: 'Sunset Fishing (2)', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-77', name: 'Brave Heroes', bonusType: 'Crit Factor', value: '5%', rarity: 'Epic', event: 'Guild Season 4', type: 'Standard', requirement: '150 Tokens' },
  { id: '2-Epic-78', name: 'Tower Agent', bonusType: 'Damage / Meter', value: '5%', rarity: 'Epic', event: 'Into the Matrix (3)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-79', name: 'Fake Reality', bonusType: 'Ultimate Damage', value: '5%', rarity: 'Epic', event: 'Into the Matrix (3)', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-80', name: 'Cosmic Freedom', bonusType: 'Health Regen', value: '5%', rarity: 'Epic', event: 'Cthulhu', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-81', name: 'Omniscience', bonusType: 'Cash', value: '5%', rarity: 'Epic', event: 'Cthulhu', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-82', name: 'No Signal', bonusType: 'Crit Chance', value: '2%', rarity: 'Epic', event: "Tower's Channel (2)", type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-83', name: 'Antenna', bonusType: 'Health', value: '5%', rarity: 'Epic', event: "Tower's Channel (2)", type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-84', name: 'Glowing Mushrooms', bonusType: 'Thorns', value: '2%', rarity: 'Epic', event: 'Autumn (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-85', name: 'Warm Clothes', bonusType: 'Lab Speed', value: '4%', rarity: 'Epic', event: 'Autumn (2)', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-86', name: 'Glimpse of Despair', bonusType: 'Crit Factor', value: '5%', rarity: 'Epic', event: 'Guild Season 5', type: 'Standard', requirement: '150 Tokens' },
  { id: '2-Epic-87', name: 'Tech Weapon', bonusType: 'Recovery Amount', value: '5%', rarity: 'Epic', event: 'Cyberpunk', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-88', name: 'Cybernetics', bonusType: 'Crit Chance', value: '2%', rarity: 'Epic', event: 'Cyberpunk', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-89', name: 'Spider Poison', bonusType: 'Ultimate Damage', value: '5%', rarity: 'Epic', event: 'Cobweb (3)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-90', name: 'Spider Forest', bonusType: 'Crit Factor', value: '5%', rarity: 'Epic', event: 'Cobweb (3)', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-91', name: "Let's Play", bonusType: 'Damage', value: '5%', rarity: 'Epic', event: 'Retro Arcade (3)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-92', name: 'Enemies', bonusType: 'Coins', value: '5%', rarity: 'Epic', event: 'Retro Arcade (3)', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-93', name: 'Crystals Bag', bonusType: 'Knockback Force', value: '5%', rarity: 'Epic', event: 'Crystal Cave', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-94', name: 'Full Minecart', bonusType: 'Bot Range', value: '2m', rarity: 'Epic', event: 'Crystal Cave', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-95', name: 'Star Planet', bonusType: 'Health Regen', value: '5%', rarity: 'Epic', event: 'Guild Season 6', type: 'Standard', requirement: '150 Tokens' },
  { id: '2-Epic-96', name: 'Snowflake', bonusType: 'Damage / Meter', value: '5%', rarity: 'Epic', event: 'Snowstorm (2)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-97', name: 'Wreath', bonusType: 'Damage', value: '5%', rarity: 'Epic', event: 'Snowstorm (2)', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-98', name: 'Firework Rocket', bonusType: 'Free Utility Upgrade', value: '2%', rarity: 'Epic', event: 'New Year (3)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-99', name: 'Gift box', bonusType: 'Lab Speed', value: '4%', rarity: 'Epic', event: 'New Year (3)', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-100', name: 'Amazing Prizes', bonusType: 'Thorns', value: '2%', rarity: 'Epic', event: 'Amusement Park', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-101', name: 'Carousel Of Joy', bonusType: 'Coins', value: '5%', rarity: 'Epic', event: 'Amusement Park', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-102', name: 'Northern Mountains', bonusType: 'Defense %', value: '2%', rarity: 'Epic', event: 'Aurora (3)', type: 'Standard', requirement: '700 Medals' },
  { id: '2-Epic-103', name: 'Cosmic Impact', bonusType: 'Orb Speed', value: '5%', rarity: 'Epic', event: 'Amusement Park', type: 'Premium', requirement: '1100 Medals' },
  { id: '2-Epic-104', name: 'Quasar', bonusType: 'Health Regen', value: '5%', rarity: 'Epic', event: 'Guild Season 7', type: 'Standard', requirement: '150 Tokens' },
  { id: '2-Epic-105', name: 'Crop Circles', bonusType: 'Knockback Force', value: '5%', rarity: 'Epic', event: 'Aliens (3)', type: 'Standard', requirement: '700 medals' },
  { id: '2-Epic-106', name: 'Alien Implants', bonusType: 'Ultimate Damage', value: '5%', rarity: 'Epic', event: 'Aliens (3)', type: 'Premium', requirement: '1100 Medals' },

  // Legendary
  { id: '3-Legendary-1', name: 'Champion Badge', bonusType: 'Damage / Meter', value: '10%', rarity: '3-Legendary', event: '4th  in Champion', type: 'Tournament', requirement: '4th  in Champion' },
  { id: '3-Legendary-2', name: 'Tower Master', bonusType: 'Health', value: '10%', rarity: '3-Legendary', event: '4th  in Legend', type: 'Tournament', requirement: '4th  in Legend' },
  { id: '3-Legendary-3', name: 'T: XI Resonance', bonusType: 'Defense Absolute', value: '10%', rarity: '3-Legendary', event: 'T11 W4500', type: 'Milestone', requirement: '4500 Waves in T11' },
  { id: '3-Legendary-4', name: 'T: X2 Chrono', bonusType: 'Lab Speed', value: '10%', rarity: '3-Legendary', event: 'T12 W4500', type: 'Milestone', requirement: '4500 Waves in T12' },
  { id: '3-Legendary-5', name: 'T: X3 Hyper', bonusType: 'Coins', value: '10%', rarity: '3-Legendary', event: 'T13 W4500', type: 'Milestone', requirement: '4500 Waves in T13' },
  { id: '3-Legendary-6', name: 'T: XIV Arcane', bonusType: 'Damage', value: '10%', rarity: '3-Legendary', event: 'T14 W4500', type: 'Milestone', requirement: '4500 Waves in T14' },
  { id: '3-Legendary-7', name: 'T: XV Celestial', bonusType: 'Crit Factor', value: '10%', rarity: '3-Legendary', event: 'T15 W4500', type: 'Milestone', requirement: '4500 Waves in T15' },
  { id: '3-Legendary-8', name: 'T: XVI Quantum', bonusType: 'Health', value: '10%', rarity: '3-Legendary', event: 'T16 W4500', type: 'Milestone', requirement: '4500 Waves in T16' },
  { id: '3-Legendary-9', name: 'T: XV2 Nebula', bonusType: 'Damage / Meter', value: '10%', rarity: '3-Legendary', event: 'T17 W4500', type: 'Milestone', requirement: '4500 Waves in T17' },
  { id: '3-Legendary-10', name: 'T: XV3 Sigularity', bonusType: 'Lab Speed', value: '10%', rarity: '3-Legendary', event: 'T18 W4500', type: 'Milestone', requirement: '4500 Waves in T18' },
  { id: '3-Legendary-11', name: 'T: XIX Atomic', bonusType: 'Damage', value: '10%', rarity: '3-Legendary', event: 'T19 W4500', type: 'Milestone', requirement: '4500 Waves in T19' },
  { id: '3-Legendary-12', name: 'T: XX Cyber', bonusType: 'Ultimate Damage', value: '8%', rarity: '3-Legendary', event: 'T20 W4500', type: 'Milestone', requirement: '4500 Waves in T20' },
  { id: '3-Legendary-13', name: 'T: XXI Eclipse', bonusType: 'Lab Speed', value: '10%', rarity: '3-Legendary', event: 'T21 W4500', type: 'Milestone', requirement: '4500 Waves in T21' },
  { id: '3-Legendary-14', name: 'Legend Badge', bonusType: 'Crit Factor', value: '10%', rarity: '3-Legendary', event: '1st in Legends', type: 'Tournament', requirement: 'Win Legend' },
]

export default RELIC_TEMPLATES
