export const towerAiUwWeaponAliases: Record<string, string> = {
  gt: 'Golden Tower',
  'golden tower': 'Golden Tower',
  bh: 'Black Hole',
  'black hole': 'Black Hole',
  cl: 'Chain Lightning',
  'chain lightning': 'Chain Lightning',
  cf: 'Chrono Field',
  'chrono field': 'Chrono Field',
  dw: 'Death Wave',
  'death wave': 'Death Wave',
  ilm: 'Inner Land Mines',
  'inner land mines': 'Inner Land Mines',
  ps: 'Poison Swamp',
  'poison swamp': 'Poison Swamp',
  sl: 'Spotlight',
  spotlight: 'Spotlight',
  sm: 'Smart Missiles',
  'smart missiles': 'Smart Missiles',
}

export const towerAiUwStatAliases: Record<string, string> = {
  duration: 'duration',
  dur: 'duration',
  cooldown: 'cooldown',
  cd: 'cooldown',
  cdr: 'cooldown',
  cdn: 'cooldown',
  bonus: 'bonus',
  quantity: 'quantity',
  qty: 'quantity',
  quant: 'quantity',
  damage: 'damage',
  dmg: 'damage',
  multiplier: 'multiplier',
  mult: 'multiplier',
  angle: 'angle',
  chance: 'chance',
  size: 'size',
  sz: 'size',
  'speed reduction': 'speed reduction',
  slowdown: 'speed reduction',
  slow: 'speed reduction',
  sr: 'speed reduction',
}

export const towerAiBotDisplayAliases: Record<string, string> = {
  fb: 'Flame Bot',
  'flame bot': 'Flame Bot',
  tb: 'Thunder Bot',
  'thunder bot': 'Thunder Bot',
  cb: 'Golden Bot',
  'coin bot': 'Golden Bot',
  'coin bonus': 'Golden Bot',
  gb: 'Golden Bot',
  'gold bot': 'Golden Bot',
  'golden bot': 'Golden Bot',
  ab: 'Amplify Bot',
  'amplify bot': 'Amplify Bot',
  'amp bot': 'Amplify Bot',
}

export const towerAiBotCalcAliases: Record<string, string> = {
  fb: 'flame bot',
  'flame bot': 'flame bot',
  tb: 'thunder bot',
  'thunder bot': 'thunder bot',
  cb: 'golden bot',
  'coin bot': 'golden bot',
  'coin bonus': 'golden bot',
  gb: 'golden bot',
  'gold bot': 'golden bot',
  'golden bot': 'golden bot',
  ab: 'amplify bot',
  'amplify bot': 'amplify bot',
  'amp bot': 'amplify bot',
}

export const towerAiBotStatAliases: Record<string, string> = {
  all: 'all',
  cooldown: 'cooldown',
  cd: 'cooldown',
  cdr: 'cooldown',
  duration: 'duration',
  dur: 'duration',
  bonus: 'bonus',
  range: 'range',
  rng: 'range',
  damage: 'damage',
  dmg: 'damage',
  'damage reduction': 'damage reduction',
  'dmg reduction': 'damage reduction',
  dr: 'damage reduction',
  linger: 'linger',
}
